include("../examples/lo1.jl")
include("../examples/cqo1.jl")
include("../examples/qo1.jl")
include("../examples/qcqo1.jl")
include("../examples/milo1.jl")
include("../examples/sdo1.jl")
include("../examples/eo1.jl")
include("../examples/nlo1.jl")
include("../examples/solvebasis.jl")
include("../examples/portfolio.jl")
include("../examples/production.jl")
include("../examples/callback.jl")

push!(ARGS, "$(dirname(dirname(@__FILE__)))/examples/feasrepair.lp")
include("../examples/feasrepairex1.jl")
