# Contents of this file is generated. Do not edit by hand!
# MOSEK 8.0.0.28

export
  MSK_SOLVE_DUAL,
  MSK_SOLVE_FREE,
  MSK_SOLVE_PRIMAL,
  MSK_SOLVE_BEGIN,
  MSK_SOLVE_END,
  MSK_PI_CON,
  MSK_PI_CONE,
  MSK_PI_VAR,
  MSK_PI_BEGIN,
  MSK_PI_END,
  MSK_ACC_CON,
  MSK_ACC_VAR,
  MSK_ACC_BEGIN,
  MSK_ACC_END,
  MSK_SENSITIVITY_TYPE_BASIS,
  MSK_SENSITIVITY_TYPE_OPTIMAL_PARTITION,
  MSK_SENSITIVITY_TYPE_BEGIN,
  MSK_SENSITIVITY_TYPE_END,
  MSK_UPLO_LO,
  MSK_UPLO_UP,
  MSK_UPLO_BEGIN,
  MSK_UPLO_END,
  MSK_INTPNT_HOTSTART_DUAL,
  MSK_INTPNT_HOTSTART_NONE,
  MSK_INTPNT_HOTSTART_PRIMAL,
  MSK_INTPNT_HOTSTART_PRIMAL_DUAL,
  MSK_INTPNT_HOTSTART_BEGIN,
  MSK_INTPNT_HOTSTART_END,
  MSK_SPAR_BAS_SOL_FILE_NAME,
  MSK_SPAR_DATA_FILE_NAME,
  MSK_SPAR_DEBUG_FILE_NAME,
  MSK_SPAR_INT_SOL_FILE_NAME,
  MSK_SPAR_ITR_SOL_FILE_NAME,
  MSK_SPAR_MIO_DEBUG_STRING,
  MSK_SPAR_PARAM_COMMENT_SIGN,
  MSK_SPAR_PARAM_READ_FILE_NAME,
  MSK_SPAR_PARAM_WRITE_FILE_NAME,
  MSK_SPAR_READ_MPS_BOU_NAME,
  MSK_SPAR_READ_MPS_OBJ_NAME,
  MSK_SPAR_READ_MPS_RAN_NAME,
  MSK_SPAR_READ_MPS_RHS_NAME,
  MSK_SPAR_REMOTE_ACCESS_TOKEN,
  MSK_SPAR_SENSITIVITY_FILE_NAME,
  MSK_SPAR_SENSITIVITY_RES_FILE_NAME,
  MSK_SPAR_SOL_FILTER_XC_LOW,
  MSK_SPAR_SOL_FILTER_XC_UPR,
  MSK_SPAR_SOL_FILTER_XX_LOW,
  MSK_SPAR_SOL_FILTER_XX_UPR,
  MSK_SPAR_STAT_FILE_NAME,
  MSK_SPAR_STAT_KEY,
  MSK_SPAR_STAT_NAME,
  MSK_SPAR_WRITE_LP_GEN_VAR_NAME,
  MSK_SPAR_BEGIN,
  MSK_SPAR_END,
  MSK_IPAR_ANA_SOL_BASIS,
  MSK_IPAR_ANA_SOL_PRINT_VIOLATED,
  MSK_IPAR_AUTO_SORT_A_BEFORE_OPT,
  MSK_IPAR_AUTO_UPDATE_SOL_INFO,
  MSK_IPAR_BASIS_SOLVE_USE_PLUS_ONE,
  MSK_IPAR_BI_CLEAN_OPTIMIZER,
  MSK_IPAR_BI_IGNORE_MAX_ITER,
  MSK_IPAR_BI_IGNORE_NUM_ERROR,
  MSK_IPAR_BI_MAX_ITERATIONS,
  MSK_IPAR_CACHE_LICENSE,
  MSK_IPAR_CHECK_CONVEXITY,
  MSK_IPAR_COMPRESS_STATFILE,
  MSK_IPAR_CONCURRENT_NUM_OPTIMIZERS,
  MSK_IPAR_CONCURRENT_PRIORITY_DUAL_SIMPLEX,
  MSK_IPAR_CONCURRENT_PRIORITY_FREE_SIMPLEX,
  MSK_IPAR_CONCURRENT_PRIORITY_INTPNT,
  MSK_IPAR_CONCURRENT_PRIORITY_PRIMAL_SIMPLEX,
  MSK_IPAR_FEASREPAIR_OPTIMIZE,
  MSK_IPAR_INFEAS_GENERIC_NAMES,
  MSK_IPAR_INFEAS_PREFER_PRIMAL,
  MSK_IPAR_INFEAS_REPORT_AUTO,
  MSK_IPAR_INFEAS_REPORT_LEVEL,
  MSK_IPAR_INTPNT_BASIS,
  MSK_IPAR_INTPNT_DIFF_STEP,
  MSK_IPAR_INTPNT_HOTSTART,
  MSK_IPAR_INTPNT_MAX_ITERATIONS,
  MSK_IPAR_INTPNT_MAX_NUM_COR,
  MSK_IPAR_INTPNT_MAX_NUM_REFINEMENT_STEPS,
  MSK_IPAR_INTPNT_MULTI_THREAD,
  MSK_IPAR_INTPNT_OFF_COL_TRH,
  MSK_IPAR_INTPNT_ORDER_METHOD,
  MSK_IPAR_INTPNT_REGULARIZATION_USE,
  MSK_IPAR_INTPNT_SCALING,
  MSK_IPAR_INTPNT_SOLVE_FORM,
  MSK_IPAR_INTPNT_STARTING_POINT,
  MSK_IPAR_LICENSE_DEBUG,
  MSK_IPAR_LICENSE_PAUSE_TIME,
  MSK_IPAR_LICENSE_SUPPRESS_EXPIRE_WRNS,
  MSK_IPAR_LICENSE_TRH_EXPIRY_WRN,
  MSK_IPAR_LICENSE_WAIT,
  MSK_IPAR_LOG,
  MSK_IPAR_LOG_ANA_PRO,
  MSK_IPAR_LOG_BI,
  MSK_IPAR_LOG_BI_FREQ,
  MSK_IPAR_LOG_CHECK_CONVEXITY,
  MSK_IPAR_LOG_CONCURRENT,
  MSK_IPAR_LOG_CUT_SECOND_OPT,
  MSK_IPAR_LOG_EXPAND,
  MSK_IPAR_LOG_FACTOR,
  MSK_IPAR_LOG_FEAS_REPAIR,
  MSK_IPAR_LOG_FILE,
  MSK_IPAR_LOG_HEAD,
  MSK_IPAR_LOG_INFEAS_ANA,
  MSK_IPAR_LOG_INTPNT,
  MSK_IPAR_LOG_MIO,
  MSK_IPAR_LOG_MIO_FREQ,
  MSK_IPAR_LOG_OPTIMIZER,
  MSK_IPAR_LOG_ORDER,
  MSK_IPAR_LOG_PRESOLVE,
  MSK_IPAR_LOG_RESPONSE,
  MSK_IPAR_LOG_SENSITIVITY,
  MSK_IPAR_LOG_SENSITIVITY_OPT,
  MSK_IPAR_LOG_SIM,
  MSK_IPAR_LOG_SIM_FREQ,
  MSK_IPAR_LOG_SIM_MINOR,
  MSK_IPAR_LOG_STORAGE,
  MSK_IPAR_MAX_NUM_WARNINGS,
  MSK_IPAR_MIO_BRANCH_DIR,
  MSK_IPAR_MIO_CONSTRUCT_SOL,
  MSK_IPAR_MIO_CUT_CLIQUE,
  MSK_IPAR_MIO_CUT_CMIR,
  MSK_IPAR_MIO_CUT_GMI,
  MSK_IPAR_MIO_CUT_IMPLIED_BOUND,
  MSK_IPAR_MIO_CUT_KNAPSACK_COVER,
  MSK_IPAR_MIO_CUT_SELECTION_LEVEL,
  MSK_IPAR_MIO_HEURISTIC_LEVEL,
  MSK_IPAR_MIO_MAX_NUM_BRANCHES,
  MSK_IPAR_MIO_MAX_NUM_RELAXS,
  MSK_IPAR_MIO_MAX_NUM_SOLUTIONS,
  MSK_IPAR_MIO_MODE,
  MSK_IPAR_MIO_MT_USER_CB,
  MSK_IPAR_MIO_NODE_OPTIMIZER,
  MSK_IPAR_MIO_NODE_SELECTION,
  MSK_IPAR_MIO_PERSPECTIVE_REFORMULATE,
  MSK_IPAR_MIO_PROBING_LEVEL,
  MSK_IPAR_MIO_RINS_MAX_NODES,
  MSK_IPAR_MIO_ROOT_OPTIMIZER,
  MSK_IPAR_MIO_ROOT_REPEAT_PRESOLVE_LEVEL,
  MSK_IPAR_MIO_VB_DETECTION_LEVEL,
  MSK_IPAR_MT_SPINCOUNT,
  MSK_IPAR_NUM_THREADS,
  MSK_IPAR_OPF_MAX_TERMS_PER_LINE,
  MSK_IPAR_OPF_WRITE_HEADER,
  MSK_IPAR_OPF_WRITE_HINTS,
  MSK_IPAR_OPF_WRITE_PARAMETERS,
  MSK_IPAR_OPF_WRITE_PROBLEM,
  MSK_IPAR_OPF_WRITE_SOL_BAS,
  MSK_IPAR_OPF_WRITE_SOL_ITG,
  MSK_IPAR_OPF_WRITE_SOL_ITR,
  MSK_IPAR_OPF_WRITE_SOLUTIONS,
  MSK_IPAR_OPTIMIZER,
  MSK_IPAR_PARAM_READ_CASE_NAME,
  MSK_IPAR_PARAM_READ_IGN_ERROR,
  MSK_IPAR_PRESOLVE_ELIMINATOR_MAX_FILL,
  MSK_IPAR_PRESOLVE_ELIMINATOR_MAX_NUM_TRIES,
  MSK_IPAR_PRESOLVE_LEVEL,
  MSK_IPAR_PRESOLVE_LINDEP_ABS_WORK_TRH,
  MSK_IPAR_PRESOLVE_LINDEP_REL_WORK_TRH,
  MSK_IPAR_PRESOLVE_LINDEP_USE,
  MSK_IPAR_PRESOLVE_MAX_NUM_REDUCTIONS,
  MSK_IPAR_PRESOLVE_USE,
  MSK_IPAR_PRIMAL_REPAIR_OPTIMIZER,
  MSK_IPAR_READ_DATA_COMPRESSED,
  MSK_IPAR_READ_DATA_FORMAT,
  MSK_IPAR_READ_DEBUG,
  MSK_IPAR_READ_KEEP_FREE_CON,
  MSK_IPAR_READ_LP_DROP_NEW_VARS_IN_BOU,
  MSK_IPAR_READ_LP_QUOTED_NAMES,
  MSK_IPAR_READ_MPS_FORMAT,
  MSK_IPAR_READ_MPS_WIDTH,
  MSK_IPAR_READ_TASK_IGNORE_PARAM,
  MSK_IPAR_SENSITIVITY_ALL,
  MSK_IPAR_SENSITIVITY_OPTIMIZER,
  MSK_IPAR_SENSITIVITY_TYPE,
  MSK_IPAR_SIM_BASIS_FACTOR_USE,
  MSK_IPAR_SIM_DEGEN,
  MSK_IPAR_SIM_DUAL_CRASH,
  MSK_IPAR_SIM_DUAL_PHASEONE_METHOD,
  MSK_IPAR_SIM_DUAL_RESTRICT_SELECTION,
  MSK_IPAR_SIM_DUAL_SELECTION,
  MSK_IPAR_SIM_EXPLOIT_DUPVEC,
  MSK_IPAR_SIM_HOTSTART,
  MSK_IPAR_SIM_HOTSTART_LU,
  MSK_IPAR_SIM_INTEGER,
  MSK_IPAR_SIM_MAX_ITERATIONS,
  MSK_IPAR_SIM_MAX_NUM_SETBACKS,
  MSK_IPAR_SIM_NON_SINGULAR,
  MSK_IPAR_SIM_PRIMAL_CRASH,
  MSK_IPAR_SIM_PRIMAL_PHASEONE_METHOD,
  MSK_IPAR_SIM_PRIMAL_RESTRICT_SELECTION,
  MSK_IPAR_SIM_PRIMAL_SELECTION,
  MSK_IPAR_SIM_REFACTOR_FREQ,
  MSK_IPAR_SIM_REFORMULATION,
  MSK_IPAR_SIM_SAVE_LU,
  MSK_IPAR_SIM_SCALING,
  MSK_IPAR_SIM_SCALING_METHOD,
  MSK_IPAR_SIM_SOLVE_FORM,
  MSK_IPAR_SIM_STABILITY_PRIORITY,
  MSK_IPAR_SIM_SWITCH_OPTIMIZER,
  MSK_IPAR_SOL_FILTER_KEEP_BASIC,
  MSK_IPAR_SOL_FILTER_KEEP_RANGED,
  MSK_IPAR_SOL_READ_NAME_WIDTH,
  MSK_IPAR_SOL_READ_WIDTH,
  MSK_IPAR_SOLUTION_CALLBACK,
  MSK_IPAR_TIMING_LEVEL,
  MSK_IPAR_WRITE_BAS_CONSTRAINTS,
  MSK_IPAR_WRITE_BAS_HEAD,
  MSK_IPAR_WRITE_BAS_VARIABLES,
  MSK_IPAR_WRITE_DATA_COMPRESSED,
  MSK_IPAR_WRITE_DATA_FORMAT,
  MSK_IPAR_WRITE_DATA_PARAM,
  MSK_IPAR_WRITE_FREE_CON,
  MSK_IPAR_WRITE_GENERIC_NAMES,
  MSK_IPAR_WRITE_GENERIC_NAMES_IO,
  MSK_IPAR_WRITE_IGNORE_INCOMPATIBLE_CONIC_ITEMS,
  MSK_IPAR_WRITE_IGNORE_INCOMPATIBLE_ITEMS,
  MSK_IPAR_WRITE_IGNORE_INCOMPATIBLE_NL_ITEMS,
  MSK_IPAR_WRITE_IGNORE_INCOMPATIBLE_PSD_ITEMS,
  MSK_IPAR_WRITE_INT_CONSTRAINTS,
  MSK_IPAR_WRITE_INT_HEAD,
  MSK_IPAR_WRITE_INT_VARIABLES,
  MSK_IPAR_WRITE_LP_FULL_OBJ,
  MSK_IPAR_WRITE_LP_LINE_WIDTH,
  MSK_IPAR_WRITE_LP_QUOTED_NAMES,
  MSK_IPAR_WRITE_LP_STRICT_FORMAT,
  MSK_IPAR_WRITE_LP_TERMS_PER_LINE,
  MSK_IPAR_WRITE_MPS_FORMAT,
  MSK_IPAR_WRITE_MPS_INT,
  MSK_IPAR_WRITE_PRECISION,
  MSK_IPAR_WRITE_SOL_BARVARIABLES,
  MSK_IPAR_WRITE_SOL_CONSTRAINTS,
  MSK_IPAR_WRITE_SOL_HEAD,
  MSK_IPAR_WRITE_SOL_IGNORE_INVALID_NAMES,
  MSK_IPAR_WRITE_SOL_VARIABLES,
  MSK_IPAR_WRITE_TASK_INC_SOL,
  MSK_IPAR_WRITE_XML_MODE,
  MSK_IPAR_BEGIN,
  MSK_IPAR_END,
  MSK_SOL_STA_DUAL_FEAS,
  MSK_SOL_STA_DUAL_ILLPOSED_CER,
  MSK_SOL_STA_DUAL_INFEAS_CER,
  MSK_SOL_STA_INTEGER_OPTIMAL,
  MSK_SOL_STA_NEAR_DUAL_FEAS,
  MSK_SOL_STA_NEAR_DUAL_INFEAS_CER,
  MSK_SOL_STA_NEAR_INTEGER_OPTIMAL,
  MSK_SOL_STA_NEAR_OPTIMAL,
  MSK_SOL_STA_NEAR_PRIM_AND_DUAL_FEAS,
  MSK_SOL_STA_NEAR_PRIM_FEAS,
  MSK_SOL_STA_NEAR_PRIM_INFEAS_CER,
  MSK_SOL_STA_OPTIMAL,
  MSK_SOL_STA_PRIM_AND_DUAL_FEAS,
  MSK_SOL_STA_PRIM_FEAS,
  MSK_SOL_STA_PRIM_ILLPOSED_CER,
  MSK_SOL_STA_PRIM_INFEAS_CER,
  MSK_SOL_STA_UNKNOWN,
  MSK_SOL_STA_BEGIN,
  MSK_SOL_STA_END,
  MSK_OBJECTIVE_SENSE_MAXIMIZE,
  MSK_OBJECTIVE_SENSE_MINIMIZE,
  MSK_OBJECTIVE_SENSE_BEGIN,
  MSK_OBJECTIVE_SENSE_END,
  MSK_SOL_ITEM_SLC,
  MSK_SOL_ITEM_SLX,
  MSK_SOL_ITEM_SNX,
  MSK_SOL_ITEM_SUC,
  MSK_SOL_ITEM_SUX,
  MSK_SOL_ITEM_XC,
  MSK_SOL_ITEM_XX,
  MSK_SOL_ITEM_Y,
  MSK_SOL_ITEM_BEGIN,
  MSK_SOL_ITEM_END,
  MSK_BK_FR,
  MSK_BK_FX,
  MSK_BK_LO,
  MSK_BK_RA,
  MSK_BK_UP,
  MSK_BK_BEGIN,
  MSK_BK_END,
  MSK_BI_ALWAYS,
  MSK_BI_IF_FEASIBLE,
  MSK_BI_NEVER,
  MSK_BI_NO_ERROR,
  MSK_BI_RESERVERED,
  MSK_BI_BEGIN,
  MSK_BI_END,
  MSK_BRANCH_DIR_DOWN,
  MSK_BRANCH_DIR_FAR,
  MSK_BRANCH_DIR_FREE,
  MSK_BRANCH_DIR_GUIDED,
  MSK_BRANCH_DIR_NEAR,
  MSK_BRANCH_DIR_PSEUDOCOST,
  MSK_BRANCH_DIR_ROOT_LP,
  MSK_BRANCH_DIR_UP,
  MSK_BRANCH_DIR_BEGIN,
  MSK_BRANCH_DIR_END,
  MSK_LIINF_BI_CLEAN_DUAL_DEG_ITER,
  MSK_LIINF_BI_CLEAN_DUAL_ITER,
  MSK_LIINF_BI_CLEAN_PRIMAL_DEG_ITER,
  MSK_LIINF_BI_CLEAN_PRIMAL_DUAL_DEG_ITER,
  MSK_LIINF_BI_CLEAN_PRIMAL_DUAL_ITER,
  MSK_LIINF_BI_CLEAN_PRIMAL_DUAL_SUB_ITER,
  MSK_LIINF_BI_CLEAN_PRIMAL_ITER,
  MSK_LIINF_BI_DUAL_ITER,
  MSK_LIINF_BI_PRIMAL_ITER,
  MSK_LIINF_INTPNT_FACTOR_NUM_NZ,
  MSK_LIINF_MIO_INTPNT_ITER,
  MSK_LIINF_MIO_PRESOLVED_ANZ,
  MSK_LIINF_MIO_SIM_MAXITER_SETBACKS,
  MSK_LIINF_MIO_SIMPLEX_ITER,
  MSK_LIINF_RD_NUMANZ,
  MSK_LIINF_RD_NUMQNZ,
  MSK_LIINF_BEGIN,
  MSK_LIINF_END,
  MSK_STREAM_ERR,
  MSK_STREAM_LOG,
  MSK_STREAM_MSG,
  MSK_STREAM_WRN,
  MSK_STREAM_BEGIN,
  MSK_STREAM_END,
  MSK_SIM_HOTSTART_FREE,
  MSK_SIM_HOTSTART_NONE,
  MSK_SIM_HOTSTART_STATUS_KEYS,
  MSK_SIM_HOTSTART_BEGIN,
  MSK_SIM_HOTSTART_END,
  MSK_CALLBACK_BEGIN_BI,
  MSK_CALLBACK_BEGIN_CONCURRENT,
  MSK_CALLBACK_BEGIN_CONIC,
  MSK_CALLBACK_BEGIN_DUAL_BI,
  MSK_CALLBACK_BEGIN_DUAL_SENSITIVITY,
  MSK_CALLBACK_BEGIN_DUAL_SETUP_BI,
  MSK_CALLBACK_BEGIN_DUAL_SIMPLEX,
  MSK_CALLBACK_BEGIN_DUAL_SIMPLEX_BI,
  MSK_CALLBACK_BEGIN_FULL_CONVEXITY_CHECK,
  MSK_CALLBACK_BEGIN_INFEAS_ANA,
  MSK_CALLBACK_BEGIN_INTPNT,
  MSK_CALLBACK_BEGIN_LICENSE_WAIT,
  MSK_CALLBACK_BEGIN_MIO,
  MSK_CALLBACK_BEGIN_NETWORK_DUAL_SIMPLEX,
  MSK_CALLBACK_BEGIN_NETWORK_PRIMAL_SIMPLEX,
  MSK_CALLBACK_BEGIN_NETWORK_SIMPLEX,
  MSK_CALLBACK_BEGIN_OPTIMIZER,
  MSK_CALLBACK_BEGIN_PRESOLVE,
  MSK_CALLBACK_BEGIN_PRIMAL_BI,
  MSK_CALLBACK_BEGIN_PRIMAL_DUAL_SIMPLEX,
  MSK_CALLBACK_BEGIN_PRIMAL_DUAL_SIMPLEX_BI,
  MSK_CALLBACK_BEGIN_PRIMAL_REPAIR,
  MSK_CALLBACK_BEGIN_PRIMAL_SENSITIVITY,
  MSK_CALLBACK_BEGIN_PRIMAL_SETUP_BI,
  MSK_CALLBACK_BEGIN_PRIMAL_SIMPLEX,
  MSK_CALLBACK_BEGIN_PRIMAL_SIMPLEX_BI,
  MSK_CALLBACK_BEGIN_QCQO_REFORMULATE,
  MSK_CALLBACK_BEGIN_READ,
  MSK_CALLBACK_BEGIN_ROOT_CUTGEN,
  MSK_CALLBACK_BEGIN_SIMPLEX,
  MSK_CALLBACK_BEGIN_SIMPLEX_BI,
  MSK_CALLBACK_BEGIN_SIMPLEX_NETWORK_DETECT,
  MSK_CALLBACK_BEGIN_TO_CONIC,
  MSK_CALLBACK_BEGIN_WRITE,
  MSK_CALLBACK_CONIC,
  MSK_CALLBACK_DUAL_SIMPLEX,
  MSK_CALLBACK_END_BI,
  MSK_CALLBACK_END_CONCURRENT,
  MSK_CALLBACK_END_CONIC,
  MSK_CALLBACK_END_DUAL_BI,
  MSK_CALLBACK_END_DUAL_SENSITIVITY,
  MSK_CALLBACK_END_DUAL_SETUP_BI,
  MSK_CALLBACK_END_DUAL_SIMPLEX,
  MSK_CALLBACK_END_DUAL_SIMPLEX_BI,
  MSK_CALLBACK_END_FULL_CONVEXITY_CHECK,
  MSK_CALLBACK_END_INFEAS_ANA,
  MSK_CALLBACK_END_INTPNT,
  MSK_CALLBACK_END_LICENSE_WAIT,
  MSK_CALLBACK_END_MIO,
  MSK_CALLBACK_END_NETWORK_DUAL_SIMPLEX,
  MSK_CALLBACK_END_NETWORK_PRIMAL_SIMPLEX,
  MSK_CALLBACK_END_NETWORK_SIMPLEX,
  MSK_CALLBACK_END_OPTIMIZER,
  MSK_CALLBACK_END_PRESOLVE,
  MSK_CALLBACK_END_PRIMAL_BI,
  MSK_CALLBACK_END_PRIMAL_DUAL_SIMPLEX,
  MSK_CALLBACK_END_PRIMAL_DUAL_SIMPLEX_BI,
  MSK_CALLBACK_END_PRIMAL_REPAIR,
  MSK_CALLBACK_END_PRIMAL_SENSITIVITY,
  MSK_CALLBACK_END_PRIMAL_SETUP_BI,
  MSK_CALLBACK_END_PRIMAL_SIMPLEX,
  MSK_CALLBACK_END_PRIMAL_SIMPLEX_BI,
  MSK_CALLBACK_END_QCQO_REFORMULATE,
  MSK_CALLBACK_END_READ,
  MSK_CALLBACK_END_ROOT_CUTGEN,
  MSK_CALLBACK_END_SIMPLEX,
  MSK_CALLBACK_END_SIMPLEX_BI,
  MSK_CALLBACK_END_SIMPLEX_NETWORK_DETECT,
  MSK_CALLBACK_END_TO_CONIC,
  MSK_CALLBACK_END_WRITE,
  MSK_CALLBACK_IM_BI,
  MSK_CALLBACK_IM_CONIC,
  MSK_CALLBACK_IM_DUAL_BI,
  MSK_CALLBACK_IM_DUAL_SENSIVITY,
  MSK_CALLBACK_IM_DUAL_SIMPLEX,
  MSK_CALLBACK_IM_FULL_CONVEXITY_CHECK,
  MSK_CALLBACK_IM_INTPNT,
  MSK_CALLBACK_IM_LICENSE_WAIT,
  MSK_CALLBACK_IM_LU,
  MSK_CALLBACK_IM_MIO,
  MSK_CALLBACK_IM_MIO_DUAL_SIMPLEX,
  MSK_CALLBACK_IM_MIO_INTPNT,
  MSK_CALLBACK_IM_MIO_PRIMAL_SIMPLEX,
  MSK_CALLBACK_IM_NETWORK_DUAL_SIMPLEX,
  MSK_CALLBACK_IM_NETWORK_PRIMAL_SIMPLEX,
  MSK_CALLBACK_IM_ORDER,
  MSK_CALLBACK_IM_PRESOLVE,
  MSK_CALLBACK_IM_PRIMAL_BI,
  MSK_CALLBACK_IM_PRIMAL_DUAL_SIMPLEX,
  MSK_CALLBACK_IM_PRIMAL_SENSIVITY,
  MSK_CALLBACK_IM_PRIMAL_SIMPLEX,
  MSK_CALLBACK_IM_QO_REFORMULATE,
  MSK_CALLBACK_IM_READ,
  MSK_CALLBACK_IM_ROOT_CUTGEN,
  MSK_CALLBACK_IM_SIMPLEX,
  MSK_CALLBACK_IM_SIMPLEX_BI,
  MSK_CALLBACK_INTPNT,
  MSK_CALLBACK_NEW_INT_MIO,
  MSK_CALLBACK_PRIMAL_SIMPLEX,
  MSK_CALLBACK_READ_OPF,
  MSK_CALLBACK_READ_OPF_SECTION,
  MSK_CALLBACK_SOLVING_REMOTE,
  MSK_CALLBACK_UPDATE_DUAL_BI,
  MSK_CALLBACK_UPDATE_DUAL_SIMPLEX,
  MSK_CALLBACK_UPDATE_DUAL_SIMPLEX_BI,
  MSK_CALLBACK_UPDATE_NETWORK_DUAL_SIMPLEX,
  MSK_CALLBACK_UPDATE_NETWORK_PRIMAL_SIMPLEX,
  MSK_CALLBACK_UPDATE_PRESOLVE,
  MSK_CALLBACK_UPDATE_PRIMAL_BI,
  MSK_CALLBACK_UPDATE_PRIMAL_DUAL_SIMPLEX,
  MSK_CALLBACK_UPDATE_PRIMAL_DUAL_SIMPLEX_BI,
  MSK_CALLBACK_UPDATE_PRIMAL_SIMPLEX,
  MSK_CALLBACK_UPDATE_PRIMAL_SIMPLEX_BI,
  MSK_CALLBACK_WRITE_OPF,
  MSK_CALLBACK_BEGIN,
  MSK_CALLBACK_END,
  MSK_SYMMAT_TYPE_SPARSE,
  MSK_SYMMAT_TYPE_BEGIN,
  MSK_SYMMAT_TYPE_END,
  MSK_FEATURE_PTON,
  MSK_FEATURE_PTS,
  MSK_FEATURE_BEGIN,
  MSK_FEATURE_END,
  MSK_MARK_LO,
  MSK_MARK_UP,
  MSK_MARK_BEGIN,
  MSK_MARK_END,
  MSK_CT_QUAD,
  MSK_CT_RQUAD,
  MSK_CT_BEGIN,
  MSK_CT_END,
  MSK_FEASREPAIR_OPTIMIZE_COMBINED,
  MSK_FEASREPAIR_OPTIMIZE_NONE,
  MSK_FEASREPAIR_OPTIMIZE_PENALTY,
  MSK_FEASREPAIR_BEGIN,
  MSK_FEASREPAIR_END,
  MSK_IOMODE_READ,
  MSK_IOMODE_READWRITE,
  MSK_IOMODE_WRITE,
  MSK_IOMODE_BEGIN,
  MSK_IOMODE_END,
  MSK_SIM_SELECTION_ASE,
  MSK_SIM_SELECTION_DEVEX,
  MSK_SIM_SELECTION_FREE,
  MSK_SIM_SELECTION_FULL,
  MSK_SIM_SELECTION_PARTIAL,
  MSK_SIM_SELECTION_SE,
  MSK_SIM_SELECTION_BEGIN,
  MSK_SIM_SELECTION_END,
  MSK_MSG_MPS_SELECTED,
  MSK_MSG_READING_FILE,
  MSK_MSG_WRITING_FILE,
  MSK_MIO_MODE_IGNORED,
  MSK_MIO_MODE_SATISFIED,
  MSK_MIO_MODE_BEGIN,
  MSK_MIO_MODE_END,
  MSK_DINF_BI_CLEAN_DUAL_TIME,
  MSK_DINF_BI_CLEAN_PRIMAL_DUAL_TIME,
  MSK_DINF_BI_CLEAN_PRIMAL_TIME,
  MSK_DINF_BI_CLEAN_TIME,
  MSK_DINF_BI_DUAL_TIME,
  MSK_DINF_BI_PRIMAL_TIME,
  MSK_DINF_BI_TIME,
  MSK_DINF_CONCURRENT_TIME,
  MSK_DINF_INTPNT_DUAL_FEAS,
  MSK_DINF_INTPNT_DUAL_OBJ,
  MSK_DINF_INTPNT_FACTOR_NUM_FLOPS,
  MSK_DINF_INTPNT_OPT_STATUS,
  MSK_DINF_INTPNT_ORDER_TIME,
  MSK_DINF_INTPNT_PRIMAL_FEAS,
  MSK_DINF_INTPNT_PRIMAL_OBJ,
  MSK_DINF_INTPNT_TIME,
  MSK_DINF_MIO_CLIQUE_SEPARATION_TIME,
  MSK_DINF_MIO_CMIR_SEPARATION_TIME,
  MSK_DINF_MIO_CONSTRUCT_SOLUTION_OBJ,
  MSK_DINF_MIO_DUAL_BOUND_AFTER_PRESOLVE,
  MSK_DINF_MIO_GMI_SEPARATION_TIME,
  MSK_DINF_MIO_HEURISTIC_TIME,
  MSK_DINF_MIO_IMPLIED_BOUND_TIME,
  MSK_DINF_MIO_KNAPSACK_COVER_SEPARATION_TIME,
  MSK_DINF_MIO_OBJ_ABS_GAP,
  MSK_DINF_MIO_OBJ_BOUND,
  MSK_DINF_MIO_OBJ_INT,
  MSK_DINF_MIO_OBJ_REL_GAP,
  MSK_DINF_MIO_OPTIMIZER_TIME,
  MSK_DINF_MIO_PROBING_TIME,
  MSK_DINF_MIO_ROOT_CUTGEN_TIME,
  MSK_DINF_MIO_ROOT_OPTIMIZER_TIME,
  MSK_DINF_MIO_ROOT_PRESOLVE_TIME,
  MSK_DINF_MIO_TIME,
  MSK_DINF_MIO_USER_OBJ_CUT,
  MSK_DINF_OPTIMIZER_TIME,
  MSK_DINF_PRESOLVE_ELI_TIME,
  MSK_DINF_PRESOLVE_LINDEP_TIME,
  MSK_DINF_PRESOLVE_TIME,
  MSK_DINF_PRIMAL_REPAIR_PENALTY_OBJ,
  MSK_DINF_QCQO_REFORMULATE_MAX_PERTURBATION,
  MSK_DINF_QCQO_REFORMULATE_TIME,
  MSK_DINF_QCQO_REFORMULATE_WORST_CHOLESKY_COLUMN_SCALING,
  MSK_DINF_QCQO_REFORMULATE_WORST_CHOLESKY_DIAG_SCALING,
  MSK_DINF_RD_TIME,
  MSK_DINF_SIM_DUAL_TIME,
  MSK_DINF_SIM_FEAS,
  MSK_DINF_SIM_NETWORK_DUAL_TIME,
  MSK_DINF_SIM_NETWORK_PRIMAL_TIME,
  MSK_DINF_SIM_NETWORK_TIME,
  MSK_DINF_SIM_OBJ,
  MSK_DINF_SIM_PRIMAL_DUAL_TIME,
  MSK_DINF_SIM_PRIMAL_TIME,
  MSK_DINF_SIM_TIME,
  MSK_DINF_SOL_BAS_DUAL_OBJ,
  MSK_DINF_SOL_BAS_DVIOLCON,
  MSK_DINF_SOL_BAS_DVIOLVAR,
  MSK_DINF_SOL_BAS_NRM_BARX,
  MSK_DINF_SOL_BAS_NRM_SLC,
  MSK_DINF_SOL_BAS_NRM_SLX,
  MSK_DINF_SOL_BAS_NRM_SUC,
  MSK_DINF_SOL_BAS_NRM_SUX,
  MSK_DINF_SOL_BAS_NRM_XC,
  MSK_DINF_SOL_BAS_NRM_XX,
  MSK_DINF_SOL_BAS_NRM_Y,
  MSK_DINF_SOL_BAS_PRIMAL_OBJ,
  MSK_DINF_SOL_BAS_PVIOLCON,
  MSK_DINF_SOL_BAS_PVIOLVAR,
  MSK_DINF_SOL_ITG_NRM_BARX,
  MSK_DINF_SOL_ITG_NRM_XC,
  MSK_DINF_SOL_ITG_NRM_XX,
  MSK_DINF_SOL_ITG_PRIMAL_OBJ,
  MSK_DINF_SOL_ITG_PVIOLBARVAR,
  MSK_DINF_SOL_ITG_PVIOLCON,
  MSK_DINF_SOL_ITG_PVIOLCONES,
  MSK_DINF_SOL_ITG_PVIOLITG,
  MSK_DINF_SOL_ITG_PVIOLVAR,
  MSK_DINF_SOL_ITR_DUAL_OBJ,
  MSK_DINF_SOL_ITR_DVIOLBARVAR,
  MSK_DINF_SOL_ITR_DVIOLCON,
  MSK_DINF_SOL_ITR_DVIOLCONES,
  MSK_DINF_SOL_ITR_DVIOLVAR,
  MSK_DINF_SOL_ITR_NRM_BARS,
  MSK_DINF_SOL_ITR_NRM_BARX,
  MSK_DINF_SOL_ITR_NRM_SLC,
  MSK_DINF_SOL_ITR_NRM_SLX,
  MSK_DINF_SOL_ITR_NRM_SNX,
  MSK_DINF_SOL_ITR_NRM_SUC,
  MSK_DINF_SOL_ITR_NRM_SUX,
  MSK_DINF_SOL_ITR_NRM_XC,
  MSK_DINF_SOL_ITR_NRM_XX,
  MSK_DINF_SOL_ITR_NRM_Y,
  MSK_DINF_SOL_ITR_PRIMAL_OBJ,
  MSK_DINF_SOL_ITR_PVIOLBARVAR,
  MSK_DINF_SOL_ITR_PVIOLCON,
  MSK_DINF_SOL_ITR_PVIOLCONES,
  MSK_DINF_SOL_ITR_PVIOLVAR,
  MSK_DINF_TO_CONIC_TIME,
  MSK_DINF_BEGIN,
  MSK_DINF_END,
  MSK_PAR_DOU_TYPE,
  MSK_PAR_INT_TYPE,
  MSK_PAR_INVALID_TYPE,
  MSK_PAR_STR_TYPE,
  MSK_PAR_BEGIN,
  MSK_PAR_END,
  MSK_RESPONSE_ERR,
  MSK_RESPONSE_OK,
  MSK_RESPONSE_TRM,
  MSK_RESPONSE_UNK,
  MSK_RESPONSE_WRN,
  MSK_RESPONSE_BEGIN,
  MSK_RESPONSE_END,
  MSK_PRO_STA_DUAL_FEAS,
  MSK_PRO_STA_DUAL_INFEAS,
  MSK_PRO_STA_ILL_POSED,
  MSK_PRO_STA_NEAR_DUAL_FEAS,
  MSK_PRO_STA_NEAR_PRIM_AND_DUAL_FEAS,
  MSK_PRO_STA_NEAR_PRIM_FEAS,
  MSK_PRO_STA_PRIM_AND_DUAL_FEAS,
  MSK_PRO_STA_PRIM_AND_DUAL_INFEAS,
  MSK_PRO_STA_PRIM_FEAS,
  MSK_PRO_STA_PRIM_INFEAS,
  MSK_PRO_STA_PRIM_INFEAS_OR_UNBOUNDED,
  MSK_PRO_STA_UNKNOWN,
  MSK_PRO_STA_BEGIN,
  MSK_PRO_STA_END,
  MSK_SCALING_AGGRESSIVE,
  MSK_SCALING_FREE,
  MSK_SCALING_MODERATE,
  MSK_SCALING_NONE,
  MSK_SCALING_BEGIN,
  MSK_SCALING_END,
  MSK_RES_ERR_AD_INVALID_CODELIST,
  MSK_RES_ERR_API_ARRAY_TOO_SMALL,
  MSK_RES_ERR_API_CB_CONNECT,
  MSK_RES_ERR_API_FATAL_ERROR,
  MSK_RES_ERR_API_INTERNAL,
  MSK_RES_ERR_ARG_IS_TOO_LARGE,
  MSK_RES_ERR_ARG_IS_TOO_SMALL,
  MSK_RES_ERR_ARGUMENT_DIMENSION,
  MSK_RES_ERR_ARGUMENT_IS_TOO_LARGE,
  MSK_RES_ERR_ARGUMENT_LENNEQ,
  MSK_RES_ERR_ARGUMENT_PERM_ARRAY,
  MSK_RES_ERR_ARGUMENT_TYPE,
  MSK_RES_ERR_BAR_VAR_DIM,
  MSK_RES_ERR_BASIS,
  MSK_RES_ERR_BASIS_FACTOR,
  MSK_RES_ERR_BASIS_SINGULAR,
  MSK_RES_ERR_BLANK_NAME,
  MSK_RES_ERR_CANNOT_CLONE_NL,
  MSK_RES_ERR_CANNOT_HANDLE_NL,
  MSK_RES_ERR_CBF_DUPLICATE_ACOORD,
  MSK_RES_ERR_CBF_DUPLICATE_BCOORD,
  MSK_RES_ERR_CBF_DUPLICATE_CON,
  MSK_RES_ERR_CBF_DUPLICATE_INT,
  MSK_RES_ERR_CBF_DUPLICATE_OBJ,
  MSK_RES_ERR_CBF_DUPLICATE_OBJACOORD,
  MSK_RES_ERR_CBF_DUPLICATE_VAR,
  MSK_RES_ERR_CBF_INVALID_CON_TYPE,
  MSK_RES_ERR_CBF_INVALID_DOMAIN_DIMENSION,
  MSK_RES_ERR_CBF_INVALID_INT_INDEX,
  MSK_RES_ERR_CBF_INVALID_VAR_TYPE,
  MSK_RES_ERR_CBF_NO_VARIABLES,
  MSK_RES_ERR_CBF_NO_VERSION_SPECIFIED,
  MSK_RES_ERR_CBF_OBJ_SENSE,
  MSK_RES_ERR_CBF_PARSE,
  MSK_RES_ERR_CBF_SYNTAX,
  MSK_RES_ERR_CBF_TOO_FEW_CONSTRAINTS,
  MSK_RES_ERR_CBF_TOO_FEW_INTS,
  MSK_RES_ERR_CBF_TOO_FEW_VARIABLES,
  MSK_RES_ERR_CBF_TOO_MANY_CONSTRAINTS,
  MSK_RES_ERR_CBF_TOO_MANY_INTS,
  MSK_RES_ERR_CBF_TOO_MANY_VARIABLES,
  MSK_RES_ERR_CBF_UNSUPPORTED,
  MSK_RES_ERR_CON_Q_NOT_NSD,
  MSK_RES_ERR_CON_Q_NOT_PSD,
  MSK_RES_ERR_CONCURRENT_OPTIMIZER,
  MSK_RES_ERR_CONE_INDEX,
  MSK_RES_ERR_CONE_OVERLAP,
  MSK_RES_ERR_CONE_OVERLAP_APPEND,
  MSK_RES_ERR_CONE_REP_VAR,
  MSK_RES_ERR_CONE_SIZE,
  MSK_RES_ERR_CONE_TYPE,
  MSK_RES_ERR_CONE_TYPE_STR,
  MSK_RES_ERR_DATA_FILE_EXT,
  MSK_RES_ERR_DUP_NAME,
  MSK_RES_ERR_DUPLICATE_AIJ,
  MSK_RES_ERR_DUPLICATE_BARVARIABLE_NAMES,
  MSK_RES_ERR_DUPLICATE_CONE_NAMES,
  MSK_RES_ERR_DUPLICATE_CONSTRAINT_NAMES,
  MSK_RES_ERR_DUPLICATE_VARIABLE_NAMES,
  MSK_RES_ERR_END_OF_FILE,
  MSK_RES_ERR_FACTOR,
  MSK_RES_ERR_FEASREPAIR_CANNOT_RELAX,
  MSK_RES_ERR_FEASREPAIR_INCONSISTENT_BOUND,
  MSK_RES_ERR_FEASREPAIR_SOLVING_RELAXED,
  MSK_RES_ERR_FILE_LICENSE,
  MSK_RES_ERR_FILE_OPEN,
  MSK_RES_ERR_FILE_READ,
  MSK_RES_ERR_FILE_WRITE,
  MSK_RES_ERR_FIRST,
  MSK_RES_ERR_FIRSTI,
  MSK_RES_ERR_FIRSTJ,
  MSK_RES_ERR_FIXED_BOUND_VALUES,
  MSK_RES_ERR_FLEXLM,
  MSK_RES_ERR_GLOBAL_INV_CONIC_PROBLEM,
  MSK_RES_ERR_HUGE_AIJ,
  MSK_RES_ERR_HUGE_C,
  MSK_RES_ERR_IDENTICAL_TASKS,
  MSK_RES_ERR_IN_ARGUMENT,
  MSK_RES_ERR_INDEX,
  MSK_RES_ERR_INDEX_ARR_IS_TOO_LARGE,
  MSK_RES_ERR_INDEX_ARR_IS_TOO_SMALL,
  MSK_RES_ERR_INDEX_IS_TOO_LARGE,
  MSK_RES_ERR_INDEX_IS_TOO_SMALL,
  MSK_RES_ERR_INF_DOU_INDEX,
  MSK_RES_ERR_INF_DOU_NAME,
  MSK_RES_ERR_INF_INT_INDEX,
  MSK_RES_ERR_INF_INT_NAME,
  MSK_RES_ERR_INF_LINT_INDEX,
  MSK_RES_ERR_INF_LINT_NAME,
  MSK_RES_ERR_INF_TYPE,
  MSK_RES_ERR_INFEAS_UNDEFINED,
  MSK_RES_ERR_INFINITE_BOUND,
  MSK_RES_ERR_INT64_TO_INT32_CAST,
  MSK_RES_ERR_INTERNAL,
  MSK_RES_ERR_INTERNAL_TEST_FAILED,
  MSK_RES_ERR_INV_APTRE,
  MSK_RES_ERR_INV_BK,
  MSK_RES_ERR_INV_BKC,
  MSK_RES_ERR_INV_BKX,
  MSK_RES_ERR_INV_CONE_TYPE,
  MSK_RES_ERR_INV_CONE_TYPE_STR,
  MSK_RES_ERR_INV_MARKI,
  MSK_RES_ERR_INV_MARKJ,
  MSK_RES_ERR_INV_NAME_ITEM,
  MSK_RES_ERR_INV_NUMI,
  MSK_RES_ERR_INV_NUMJ,
  MSK_RES_ERR_INV_OPTIMIZER,
  MSK_RES_ERR_INV_PROBLEM,
  MSK_RES_ERR_INV_QCON_SUBI,
  MSK_RES_ERR_INV_QCON_SUBJ,
  MSK_RES_ERR_INV_QCON_SUBK,
  MSK_RES_ERR_INV_QCON_VAL,
  MSK_RES_ERR_INV_QOBJ_SUBI,
  MSK_RES_ERR_INV_QOBJ_SUBJ,
  MSK_RES_ERR_INV_QOBJ_VAL,
  MSK_RES_ERR_INV_SK,
  MSK_RES_ERR_INV_SK_STR,
  MSK_RES_ERR_INV_SKC,
  MSK_RES_ERR_INV_SKN,
  MSK_RES_ERR_INV_SKX,
  MSK_RES_ERR_INV_VAR_TYPE,
  MSK_RES_ERR_INVALID_ACCMODE,
  MSK_RES_ERR_INVALID_AIJ,
  MSK_RES_ERR_INVALID_AMPL_STUB,
  MSK_RES_ERR_INVALID_BARVAR_NAME,
  MSK_RES_ERR_INVALID_COMPRESSION,
  MSK_RES_ERR_INVALID_CON_NAME,
  MSK_RES_ERR_INVALID_CONE_NAME,
  MSK_RES_ERR_INVALID_FILE_FORMAT_FOR_CONES,
  MSK_RES_ERR_INVALID_FILE_FORMAT_FOR_GENERAL_NL,
  MSK_RES_ERR_INVALID_FILE_FORMAT_FOR_SYM_MAT,
  MSK_RES_ERR_INVALID_FILE_NAME,
  MSK_RES_ERR_INVALID_FORMAT_TYPE,
  MSK_RES_ERR_INVALID_IDX,
  MSK_RES_ERR_INVALID_IOMODE,
  MSK_RES_ERR_INVALID_MAX_NUM,
  MSK_RES_ERR_INVALID_NAME_IN_SOL_FILE,
  MSK_RES_ERR_INVALID_NETWORK_PROBLEM,
  MSK_RES_ERR_INVALID_OBJ_NAME,
  MSK_RES_ERR_INVALID_OBJECTIVE_SENSE,
  MSK_RES_ERR_INVALID_PROBLEM_TYPE,
  MSK_RES_ERR_INVALID_SOL_FILE_NAME,
  MSK_RES_ERR_INVALID_STREAM,
  MSK_RES_ERR_INVALID_SURPLUS,
  MSK_RES_ERR_INVALID_SYM_MAT_DIM,
  MSK_RES_ERR_INVALID_TASK,
  MSK_RES_ERR_INVALID_UTF8,
  MSK_RES_ERR_INVALID_VAR_NAME,
  MSK_RES_ERR_INVALID_WCHAR,
  MSK_RES_ERR_INVALID_WHICHSOL,
  MSK_RES_ERR_JSON_DATA,
  MSK_RES_ERR_JSON_FORMAT,
  MSK_RES_ERR_JSON_MISSING_DATA,
  MSK_RES_ERR_JSON_NUMBER_OVERFLOW,
  MSK_RES_ERR_JSON_STRING,
  MSK_RES_ERR_JSON_SYNTAX,
  MSK_RES_ERR_LAST,
  MSK_RES_ERR_LASTI,
  MSK_RES_ERR_LASTJ,
  MSK_RES_ERR_LAU_ARG_K,
  MSK_RES_ERR_LAU_ARG_M,
  MSK_RES_ERR_LAU_ARG_N,
  MSK_RES_ERR_LAU_ARG_TRANS,
  MSK_RES_ERR_LAU_ARG_TRANSA,
  MSK_RES_ERR_LAU_ARG_TRANSB,
  MSK_RES_ERR_LAU_ARG_UPLO,
  MSK_RES_ERR_LAU_INVALID_LOWER_TRIANGULAR_MATRIX,
  MSK_RES_ERR_LAU_INVALID_SPARSE_SYMMETRIC_MATRIX,
  MSK_RES_ERR_LAU_NOT_POSITIVE_DEFINITE,
  MSK_RES_ERR_LAU_SINGULAR_MATRIX,
  MSK_RES_ERR_LAU_UNKNOWN,
  MSK_RES_ERR_LICENSE,
  MSK_RES_ERR_LICENSE_CANNOT_ALLOCATE,
  MSK_RES_ERR_LICENSE_CANNOT_CONNECT,
  MSK_RES_ERR_LICENSE_EXPIRED,
  MSK_RES_ERR_LICENSE_FEATURE,
  MSK_RES_ERR_LICENSE_INVALID_HOSTID,
  MSK_RES_ERR_LICENSE_MAX,
  MSK_RES_ERR_LICENSE_MOSEKLM_DAEMON,
  MSK_RES_ERR_LICENSE_NO_SERVER_LINE,
  MSK_RES_ERR_LICENSE_NO_SERVER_SUPPORT,
  MSK_RES_ERR_LICENSE_SERVER,
  MSK_RES_ERR_LICENSE_SERVER_VERSION,
  MSK_RES_ERR_LICENSE_VERSION,
  MSK_RES_ERR_LINK_FILE_DLL,
  MSK_RES_ERR_LIVING_TASKS,
  MSK_RES_ERR_LOWER_BOUND_IS_A_NAN,
  MSK_RES_ERR_LP_DUP_SLACK_NAME,
  MSK_RES_ERR_LP_EMPTY,
  MSK_RES_ERR_LP_FILE_FORMAT,
  MSK_RES_ERR_LP_FORMAT,
  MSK_RES_ERR_LP_FREE_CONSTRAINT,
  MSK_RES_ERR_LP_INCOMPATIBLE,
  MSK_RES_ERR_LP_INVALID_CON_NAME,
  MSK_RES_ERR_LP_INVALID_VAR_NAME,
  MSK_RES_ERR_LP_WRITE_CONIC_PROBLEM,
  MSK_RES_ERR_LP_WRITE_GECO_PROBLEM,
  MSK_RES_ERR_LU_MAX_NUM_TRIES,
  MSK_RES_ERR_MAX_LEN_IS_TOO_SMALL,
  MSK_RES_ERR_MAXNUMBARVAR,
  MSK_RES_ERR_MAXNUMCON,
  MSK_RES_ERR_MAXNUMCONE,
  MSK_RES_ERR_MAXNUMQNZ,
  MSK_RES_ERR_MAXNUMVAR,
  MSK_RES_ERR_MIO_INTERNAL,
  MSK_RES_ERR_MIO_INVALID_NODE_OPTIMIZER,
  MSK_RES_ERR_MIO_INVALID_ROOT_OPTIMIZER,
  MSK_RES_ERR_MIO_NO_OPTIMIZER,
  MSK_RES_ERR_MIO_NOT_LOADED,
  MSK_RES_ERR_MISSING_LICENSE_FILE,
  MSK_RES_ERR_MIXED_CONIC_AND_NL,
  MSK_RES_ERR_MPS_CONE_OVERLAP,
  MSK_RES_ERR_MPS_CONE_REPEAT,
  MSK_RES_ERR_MPS_CONE_TYPE,
  MSK_RES_ERR_MPS_DUPLICATE_Q_ELEMENT,
  MSK_RES_ERR_MPS_FILE,
  MSK_RES_ERR_MPS_INV_BOUND_KEY,
  MSK_RES_ERR_MPS_INV_CON_KEY,
  MSK_RES_ERR_MPS_INV_FIELD,
  MSK_RES_ERR_MPS_INV_MARKER,
  MSK_RES_ERR_MPS_INV_SEC_NAME,
  MSK_RES_ERR_MPS_INV_SEC_ORDER,
  MSK_RES_ERR_MPS_INVALID_OBJ_NAME,
  MSK_RES_ERR_MPS_INVALID_OBJSENSE,
  MSK_RES_ERR_MPS_MUL_CON_NAME,
  MSK_RES_ERR_MPS_MUL_CSEC,
  MSK_RES_ERR_MPS_MUL_QOBJ,
  MSK_RES_ERR_MPS_MUL_QSEC,
  MSK_RES_ERR_MPS_NO_OBJECTIVE,
  MSK_RES_ERR_MPS_NON_SYMMETRIC_Q,
  MSK_RES_ERR_MPS_NULL_CON_NAME,
  MSK_RES_ERR_MPS_NULL_VAR_NAME,
  MSK_RES_ERR_MPS_SPLITTED_VAR,
  MSK_RES_ERR_MPS_TAB_IN_FIELD2,
  MSK_RES_ERR_MPS_TAB_IN_FIELD3,
  MSK_RES_ERR_MPS_TAB_IN_FIELD5,
  MSK_RES_ERR_MPS_UNDEF_CON_NAME,
  MSK_RES_ERR_MPS_UNDEF_VAR_NAME,
  MSK_RES_ERR_MUL_A_ELEMENT,
  MSK_RES_ERR_NAME_IS_NULL,
  MSK_RES_ERR_NAME_MAX_LEN,
  MSK_RES_ERR_NAN_IN_BLC,
  MSK_RES_ERR_NAN_IN_BLX,
  MSK_RES_ERR_NAN_IN_BUC,
  MSK_RES_ERR_NAN_IN_BUX,
  MSK_RES_ERR_NAN_IN_C,
  MSK_RES_ERR_NAN_IN_DOUBLE_DATA,
  MSK_RES_ERR_NEGATIVE_APPEND,
  MSK_RES_ERR_NEGATIVE_SURPLUS,
  MSK_RES_ERR_NEWER_DLL,
  MSK_RES_ERR_NO_BARS_FOR_SOLUTION,
  MSK_RES_ERR_NO_BARX_FOR_SOLUTION,
  MSK_RES_ERR_NO_BASIS_SOL,
  MSK_RES_ERR_NO_DUAL_FOR_ITG_SOL,
  MSK_RES_ERR_NO_DUAL_INFEAS_CER,
  MSK_RES_ERR_NO_INIT_ENV,
  MSK_RES_ERR_NO_OPTIMIZER_VAR_TYPE,
  MSK_RES_ERR_NO_PRIMAL_INFEAS_CER,
  MSK_RES_ERR_NO_SNX_FOR_BAS_SOL,
  MSK_RES_ERR_NO_SOLUTION_IN_CALLBACK,
  MSK_RES_ERR_NON_UNIQUE_ARRAY,
  MSK_RES_ERR_NONCONVEX,
  MSK_RES_ERR_NONLINEAR_EQUALITY,
  MSK_RES_ERR_NONLINEAR_FUNCTIONS_NOT_ALLOWED,
  MSK_RES_ERR_NONLINEAR_RANGED,
  MSK_RES_ERR_NR_ARGUMENTS,
  MSK_RES_ERR_NULL_ENV,
  MSK_RES_ERR_NULL_POINTER,
  MSK_RES_ERR_NULL_TASK,
  MSK_RES_ERR_NUMCONLIM,
  MSK_RES_ERR_NUMVARLIM,
  MSK_RES_ERR_OBJ_Q_NOT_NSD,
  MSK_RES_ERR_OBJ_Q_NOT_PSD,
  MSK_RES_ERR_OBJECTIVE_RANGE,
  MSK_RES_ERR_OLDER_DLL,
  MSK_RES_ERR_OPEN_DL,
  MSK_RES_ERR_OPF_FORMAT,
  MSK_RES_ERR_OPF_NEW_VARIABLE,
  MSK_RES_ERR_OPF_PREMATURE_EOF,
  MSK_RES_ERR_OPTIMIZER_LICENSE,
  MSK_RES_ERR_OVERFLOW,
  MSK_RES_ERR_PARAM_INDEX,
  MSK_RES_ERR_PARAM_IS_TOO_LARGE,
  MSK_RES_ERR_PARAM_IS_TOO_SMALL,
  MSK_RES_ERR_PARAM_NAME,
  MSK_RES_ERR_PARAM_NAME_DOU,
  MSK_RES_ERR_PARAM_NAME_INT,
  MSK_RES_ERR_PARAM_NAME_STR,
  MSK_RES_ERR_PARAM_TYPE,
  MSK_RES_ERR_PARAM_VALUE_STR,
  MSK_RES_ERR_PLATFORM_NOT_LICENSED,
  MSK_RES_ERR_POSTSOLVE,
  MSK_RES_ERR_PRO_ITEM,
  MSK_RES_ERR_PROB_LICENSE,
  MSK_RES_ERR_QCON_SUBI_TOO_LARGE,
  MSK_RES_ERR_QCON_SUBI_TOO_SMALL,
  MSK_RES_ERR_QCON_UPPER_TRIANGLE,
  MSK_RES_ERR_QOBJ_UPPER_TRIANGLE,
  MSK_RES_ERR_READ_FORMAT,
  MSK_RES_ERR_READ_LP_MISSING_END_TAG,
  MSK_RES_ERR_READ_LP_NONEXISTING_NAME,
  MSK_RES_ERR_REMOVE_CONE_VARIABLE,
  MSK_RES_ERR_REPAIR_INVALID_PROBLEM,
  MSK_RES_ERR_REPAIR_OPTIMIZATION_FAILED,
  MSK_RES_ERR_SEN_BOUND_INVALID_LO,
  MSK_RES_ERR_SEN_BOUND_INVALID_UP,
  MSK_RES_ERR_SEN_FORMAT,
  MSK_RES_ERR_SEN_INDEX_INVALID,
  MSK_RES_ERR_SEN_INDEX_RANGE,
  MSK_RES_ERR_SEN_INVALID_REGEXP,
  MSK_RES_ERR_SEN_NUMERICAL,
  MSK_RES_ERR_SEN_SOLUTION_STATUS,
  MSK_RES_ERR_SEN_UNDEF_NAME,
  MSK_RES_ERR_SEN_UNHANDLED_PROBLEM_TYPE,
  MSK_RES_ERR_SERVER_CONNECT,
  MSK_RES_ERR_SERVER_PROTOCOL,
  MSK_RES_ERR_SERVER_STATUS,
  MSK_RES_ERR_SERVER_TOKEN,
  MSK_RES_ERR_SIZE_LICENSE,
  MSK_RES_ERR_SIZE_LICENSE_CON,
  MSK_RES_ERR_SIZE_LICENSE_INTVAR,
  MSK_RES_ERR_SIZE_LICENSE_NUMCORES,
  MSK_RES_ERR_SIZE_LICENSE_VAR,
  MSK_RES_ERR_SOL_FILE_INVALID_NUMBER,
  MSK_RES_ERR_SOLITEM,
  MSK_RES_ERR_SOLVER_PROBTYPE,
  MSK_RES_ERR_SPACE,
  MSK_RES_ERR_SPACE_LEAKING,
  MSK_RES_ERR_SPACE_NO_INFO,
  MSK_RES_ERR_SYM_MAT_DUPLICATE,
  MSK_RES_ERR_SYM_MAT_INVALID_COL_INDEX,
  MSK_RES_ERR_SYM_MAT_INVALID_ROW_INDEX,
  MSK_RES_ERR_SYM_MAT_INVALID_VALUE,
  MSK_RES_ERR_SYM_MAT_NOT_LOWER_TRINGULAR,
  MSK_RES_ERR_TASK_INCOMPATIBLE,
  MSK_RES_ERR_TASK_INVALID,
  MSK_RES_ERR_THREAD_COND_INIT,
  MSK_RES_ERR_THREAD_CREATE,
  MSK_RES_ERR_THREAD_MUTEX_INIT,
  MSK_RES_ERR_THREAD_MUTEX_LOCK,
  MSK_RES_ERR_THREAD_MUTEX_UNLOCK,
  MSK_RES_ERR_TOCONIC_CONSTR_NOT_CONIC,
  MSK_RES_ERR_TOCONIC_CONSTR_Q_NOT_PSD,
  MSK_RES_ERR_TOCONIC_CONSTRAINT_FX,
  MSK_RES_ERR_TOCONIC_CONSTRAINT_RA,
  MSK_RES_ERR_TOCONIC_OBJECTIVE_NOT_PSD,
  MSK_RES_ERR_TOO_MANY_CONCURRENT_TASKS,
  MSK_RES_ERR_TOO_SMALL_MAX_NUM_NZ,
  MSK_RES_ERR_TOO_SMALL_MAXNUMANZ,
  MSK_RES_ERR_UNB_STEP_SIZE,
  MSK_RES_ERR_UNDEF_SOLUTION,
  MSK_RES_ERR_UNDEFINED_OBJECTIVE_SENSE,
  MSK_RES_ERR_UNHANDLED_SOLUTION_STATUS,
  MSK_RES_ERR_UNKNOWN,
  MSK_RES_ERR_UPPER_BOUND_IS_A_NAN,
  MSK_RES_ERR_UPPER_TRIANGLE,
  MSK_RES_ERR_USER_FUNC_RET,
  MSK_RES_ERR_USER_FUNC_RET_DATA,
  MSK_RES_ERR_USER_NLO_EVAL,
  MSK_RES_ERR_USER_NLO_EVAL_HESSUBI,
  MSK_RES_ERR_USER_NLO_EVAL_HESSUBJ,
  MSK_RES_ERR_USER_NLO_FUNC,
  MSK_RES_ERR_WHICHITEM_NOT_ALLOWED,
  MSK_RES_ERR_WHICHSOL,
  MSK_RES_ERR_WRITE_LP_FORMAT,
  MSK_RES_ERR_WRITE_LP_NON_UNIQUE_NAME,
  MSK_RES_ERR_WRITE_MPS_INVALID_NAME,
  MSK_RES_ERR_WRITE_OPF_INVALID_VAR_NAME,
  MSK_RES_ERR_WRITING_FILE,
  MSK_RES_ERR_XML_INVALID_PROBLEM_TYPE,
  MSK_RES_ERR_Y_IS_UNDEFINED,
  MSK_RES_OK,
  MSK_RES_TRM_INTERNAL,
  MSK_RES_TRM_INTERNAL_STOP,
  MSK_RES_TRM_MAX_ITERATIONS,
  MSK_RES_TRM_MAX_NUM_SETBACKS,
  MSK_RES_TRM_MAX_TIME,
  MSK_RES_TRM_MIO_NEAR_ABS_GAP,
  MSK_RES_TRM_MIO_NEAR_REL_GAP,
  MSK_RES_TRM_MIO_NUM_BRANCHES,
  MSK_RES_TRM_MIO_NUM_RELAXS,
  MSK_RES_TRM_NUM_MAX_NUM_INT_SOLUTIONS,
  MSK_RES_TRM_NUMERICAL_PROBLEM,
  MSK_RES_TRM_OBJECTIVE_RANGE,
  MSK_RES_TRM_STALL,
  MSK_RES_TRM_USER_CALLBACK,
  MSK_RES_WRN_ANA_ALMOST_INT_BOUNDS,
  MSK_RES_WRN_ANA_C_ZERO,
  MSK_RES_WRN_ANA_CLOSE_BOUNDS,
  MSK_RES_WRN_ANA_EMPTY_COLS,
  MSK_RES_WRN_ANA_LARGE_BOUNDS,
  MSK_RES_WRN_CONSTRUCT_INVALID_SOL_ITG,
  MSK_RES_WRN_CONSTRUCT_NO_SOL_ITG,
  MSK_RES_WRN_CONSTRUCT_SOLUTION_INFEAS,
  MSK_RES_WRN_DROPPED_NZ_QOBJ,
  MSK_RES_WRN_DUPLICATE_BARVARIABLE_NAMES,
  MSK_RES_WRN_DUPLICATE_CONE_NAMES,
  MSK_RES_WRN_DUPLICATE_CONSTRAINT_NAMES,
  MSK_RES_WRN_DUPLICATE_VARIABLE_NAMES,
  MSK_RES_WRN_ELIMINATOR_SPACE,
  MSK_RES_WRN_EMPTY_NAME,
  MSK_RES_WRN_IGNORE_INTEGER,
  MSK_RES_WRN_INCOMPLETE_LINEAR_DEPENDENCY_CHECK,
  MSK_RES_WRN_LARGE_AIJ,
  MSK_RES_WRN_LARGE_BOUND,
  MSK_RES_WRN_LARGE_CJ,
  MSK_RES_WRN_LARGE_CON_FX,
  MSK_RES_WRN_LARGE_LO_BOUND,
  MSK_RES_WRN_LARGE_UP_BOUND,
  MSK_RES_WRN_LICENSE_EXPIRE,
  MSK_RES_WRN_LICENSE_FEATURE_EXPIRE,
  MSK_RES_WRN_LICENSE_SERVER,
  MSK_RES_WRN_LP_DROP_VARIABLE,
  MSK_RES_WRN_LP_OLD_QUAD_FORMAT,
  MSK_RES_WRN_MIO_INFEASIBLE_FINAL,
  MSK_RES_WRN_MPS_SPLIT_BOU_VECTOR,
  MSK_RES_WRN_MPS_SPLIT_RAN_VECTOR,
  MSK_RES_WRN_MPS_SPLIT_RHS_VECTOR,
  MSK_RES_WRN_NAME_MAX_LEN,
  MSK_RES_WRN_NO_DUALIZER,
  MSK_RES_WRN_NO_GLOBAL_OPTIMIZER,
  MSK_RES_WRN_NO_NONLINEAR_FUNCTION_WRITE,
  MSK_RES_WRN_NZ_IN_UPR_TRI,
  MSK_RES_WRN_OPEN_PARAM_FILE,
  MSK_RES_WRN_PARAM_IGNORED_CMIO,
  MSK_RES_WRN_PARAM_NAME_DOU,
  MSK_RES_WRN_PARAM_NAME_INT,
  MSK_RES_WRN_PARAM_NAME_STR,
  MSK_RES_WRN_PARAM_STR_VALUE,
  MSK_RES_WRN_PRESOLVE_OUTOFSPACE,
  MSK_RES_WRN_QUAD_CONES_WITH_ROOT_FIXED_AT_ZERO,
  MSK_RES_WRN_RQUAD_CONES_WITH_ROOT_FIXED_AT_ZERO,
  MSK_RES_WRN_SOL_FILE_IGNORED_CON,
  MSK_RES_WRN_SOL_FILE_IGNORED_VAR,
  MSK_RES_WRN_SOL_FILTER,
  MSK_RES_WRN_SPAR_MAX_LEN,
  MSK_RES_WRN_TOO_FEW_BASIS_VARS,
  MSK_RES_WRN_TOO_MANY_BASIS_VARS,
  MSK_RES_WRN_TOO_MANY_THREADS_CONCURRENT,
  MSK_RES_WRN_UNDEF_SOL_FILE_NAME,
  MSK_RES_WRN_USING_GENERIC_NAMES,
  MSK_RES_WRN_WRITE_CHANGED_NAMES,
  MSK_RES_WRN_WRITE_DISCARDED_CFIX,
  MSK_RES_WRN_ZERO_AIJ,
  MSK_RES_WRN_ZEROS_IN_SPARSE_COL,
  MSK_RES_WRN_ZEROS_IN_SPARSE_ROW,
  MSK_MIO_NODE_SELECTION_BEST,
  MSK_MIO_NODE_SELECTION_FIRST,
  MSK_MIO_NODE_SELECTION_FREE,
  MSK_MIO_NODE_SELECTION_HYBRID,
  MSK_MIO_NODE_SELECTION_PSEUDO,
  MSK_MIO_NODE_SELECTION_WORST,
  MSK_MIO_NODE_SELECTION_BEGIN,
  MSK_MIO_NODE_SELECTION_END,
  MSK_TRANSPOSE_NO,
  MSK_TRANSPOSE_YES,
  MSK_TRANSPOSE_BEGIN,
  MSK_TRANSPOSE_END,
  MSK_OFF,
  MSK_ON,
  MSK_SIM_DEGEN_AGGRESSIVE,
  MSK_SIM_DEGEN_FREE,
  MSK_SIM_DEGEN_MINIMUM,
  MSK_SIM_DEGEN_MODERATE,
  MSK_SIM_DEGEN_NONE,
  MSK_SIM_DEGEN_BEGIN,
  MSK_SIM_DEGEN_END,
  MSK_DATA_FORMAT_CB,
  MSK_DATA_FORMAT_EXTENSION,
  MSK_DATA_FORMAT_FREE_MPS,
  MSK_DATA_FORMAT_JSON_TASK,
  MSK_DATA_FORMAT_LP,
  MSK_DATA_FORMAT_MPS,
  MSK_DATA_FORMAT_OP,
  MSK_DATA_FORMAT_TASK,
  MSK_DATA_FORMAT_XML,
  MSK_DATA_FORMAT_BEGIN,
  MSK_DATA_FORMAT_END,
  MSK_ORDER_METHOD_APPMINLOC,
  MSK_ORDER_METHOD_EXPERIMENTAL,
  MSK_ORDER_METHOD_FORCE_GRAPHPAR,
  MSK_ORDER_METHOD_FREE,
  MSK_ORDER_METHOD_NONE,
  MSK_ORDER_METHOD_TRY_GRAPHPAR,
  MSK_ORDER_METHOD_BEGIN,
  MSK_ORDER_METHOD_END,
  MSK_PROBTYPE_CONIC,
  MSK_PROBTYPE_GECO,
  MSK_PROBTYPE_LO,
  MSK_PROBTYPE_MIXED,
  MSK_PROBTYPE_QCQO,
  MSK_PROBTYPE_QO,
  MSK_PROBTYPE_BEGIN,
  MSK_PROBTYPE_END,
  MSK_INF_DOU_TYPE,
  MSK_INF_INT_TYPE,
  MSK_INF_LINT_TYPE,
  MSK_INF_BEGIN,
  MSK_INF_END,
  MSK_DPAR_ANA_SOL_INFEAS_TOL,
  MSK_DPAR_BASIS_REL_TOL_S,
  MSK_DPAR_BASIS_TOL_S,
  MSK_DPAR_BASIS_TOL_X,
  MSK_DPAR_CHECK_CONVEXITY_REL_TOL,
  MSK_DPAR_DATA_TOL_AIJ,
  MSK_DPAR_DATA_TOL_AIJ_HUGE,
  MSK_DPAR_DATA_TOL_AIJ_LARGE,
  MSK_DPAR_DATA_TOL_BOUND_INF,
  MSK_DPAR_DATA_TOL_BOUND_WRN,
  MSK_DPAR_DATA_TOL_C_HUGE,
  MSK_DPAR_DATA_TOL_CJ_LARGE,
  MSK_DPAR_DATA_TOL_QIJ,
  MSK_DPAR_DATA_TOL_X,
  MSK_DPAR_FEASREPAIR_TOL,
  MSK_DPAR_INTPNT_CO_TOL_DFEAS,
  MSK_DPAR_INTPNT_CO_TOL_INFEAS,
  MSK_DPAR_INTPNT_CO_TOL_MU_RED,
  MSK_DPAR_INTPNT_CO_TOL_NEAR_REL,
  MSK_DPAR_INTPNT_CO_TOL_PFEAS,
  MSK_DPAR_INTPNT_CO_TOL_REL_GAP,
  MSK_DPAR_INTPNT_NL_MERIT_BAL,
  MSK_DPAR_INTPNT_NL_TOL_DFEAS,
  MSK_DPAR_INTPNT_NL_TOL_MU_RED,
  MSK_DPAR_INTPNT_NL_TOL_NEAR_REL,
  MSK_DPAR_INTPNT_NL_TOL_PFEAS,
  MSK_DPAR_INTPNT_NL_TOL_REL_GAP,
  MSK_DPAR_INTPNT_NL_TOL_REL_STEP,
  MSK_DPAR_INTPNT_QO_TOL_DFEAS,
  MSK_DPAR_INTPNT_QO_TOL_INFEAS,
  MSK_DPAR_INTPNT_QO_TOL_MU_RED,
  MSK_DPAR_INTPNT_QO_TOL_NEAR_REL,
  MSK_DPAR_INTPNT_QO_TOL_PFEAS,
  MSK_DPAR_INTPNT_QO_TOL_REL_GAP,
  MSK_DPAR_INTPNT_TOL_DFEAS,
  MSK_DPAR_INTPNT_TOL_DSAFE,
  MSK_DPAR_INTPNT_TOL_INFEAS,
  MSK_DPAR_INTPNT_TOL_MU_RED,
  MSK_DPAR_INTPNT_TOL_PATH,
  MSK_DPAR_INTPNT_TOL_PFEAS,
  MSK_DPAR_INTPNT_TOL_PSAFE,
  MSK_DPAR_INTPNT_TOL_REL_GAP,
  MSK_DPAR_INTPNT_TOL_REL_STEP,
  MSK_DPAR_INTPNT_TOL_STEP_SIZE,
  MSK_DPAR_LOWER_OBJ_CUT,
  MSK_DPAR_LOWER_OBJ_CUT_FINITE_TRH,
  MSK_DPAR_MIO_DISABLE_TERM_TIME,
  MSK_DPAR_MIO_MAX_TIME,
  MSK_DPAR_MIO_NEAR_TOL_ABS_GAP,
  MSK_DPAR_MIO_NEAR_TOL_REL_GAP,
  MSK_DPAR_MIO_REL_GAP_CONST,
  MSK_DPAR_MIO_TOL_ABS_GAP,
  MSK_DPAR_MIO_TOL_ABS_RELAX_INT,
  MSK_DPAR_MIO_TOL_FEAS,
  MSK_DPAR_MIO_TOL_REL_DUAL_BOUND_IMPROVEMENT,
  MSK_DPAR_MIO_TOL_REL_GAP,
  MSK_DPAR_OPTIMIZER_MAX_TIME,
  MSK_DPAR_PRESOLVE_TOL_ABS_LINDEP,
  MSK_DPAR_PRESOLVE_TOL_AIJ,
  MSK_DPAR_PRESOLVE_TOL_REL_LINDEP,
  MSK_DPAR_PRESOLVE_TOL_S,
  MSK_DPAR_PRESOLVE_TOL_X,
  MSK_DPAR_QCQO_REFORMULATE_REL_DROP_TOL,
  MSK_DPAR_SEMIDEFINITE_TOL_APPROX,
  MSK_DPAR_SIM_LU_TOL_REL_PIV,
  MSK_DPAR_SIMPLEX_ABS_TOL_PIV,
  MSK_DPAR_UPPER_OBJ_CUT,
  MSK_DPAR_UPPER_OBJ_CUT_FINITE_TRH,
  MSK_DPAR_BEGIN,
  MSK_DPAR_END,
  MSK_SIM_EXPLOIT_DUPVEC_FREE,
  MSK_SIM_EXPLOIT_DUPVEC_OFF,
  MSK_SIM_EXPLOIT_DUPVEC_ON,
  MSK_SIM_EXPLOIT_DUPVEC_BEGIN,
  MSK_SIM_EXPLOIT_DUPVEC_END,
  MSK_COMPRESS_FREE,
  MSK_COMPRESS_GZIP,
  MSK_COMPRESS_NONE,
  MSK_COMPRESS_BEGIN,
  MSK_COMPRESS_END,
  MSK_NAME_TYPE_GEN,
  MSK_NAME_TYPE_LP,
  MSK_NAME_TYPE_MPS,
  MSK_NAME_TYPE_BEGIN,
  MSK_NAME_TYPE_END,
  MSK_MPS_FORMAT_CPLEX,
  MSK_MPS_FORMAT_FREE,
  MSK_MPS_FORMAT_RELAXED,
  MSK_MPS_FORMAT_STRICT,
  MSK_MPS_FORMAT_BEGIN,
  MSK_MPS_FORMAT_END,
  MSK_VAR_TYPE_CONT,
  MSK_VAR_TYPE_INT,
  MSK_VAR_BEGIN,
  MSK_VAR_END,
  MSK_CHECK_CONVEXITY_FULL,
  MSK_CHECK_CONVEXITY_NONE,
  MSK_CHECK_CONVEXITY_SIMPLE,
  MSK_CHECK_CONVEXITY_BEGIN,
  MSK_CHECK_CONVEXITY_END,
  MSK_LANG_DAN,
  MSK_LANG_ENG,
  MSK_LANG_BEGIN,
  MSK_LANG_END,
  MSK_STARTING_POINT_CONSTANT,
  MSK_STARTING_POINT_FREE,
  MSK_STARTING_POINT_GUESS,
  MSK_STARTING_POINT_SATISFY_BOUNDS,
  MSK_STARTING_POINT_BEGIN,
  MSK_STARTING_POINT_END,
  MSK_SOL_BAS,
  MSK_SOL_ITG,
  MSK_SOL_ITR,
  MSK_SOL_BEGIN,
  MSK_SOL_END,
  MSK_SCALING_METHOD_FREE,
  MSK_SCALING_METHOD_POW2,
  MSK_SCALING_METHOD_BEGIN,
  MSK_SCALING_METHOD_END,
  MSK_LICENSE_BUFFER_LENGTH,
  MSK_MAX_STR_LEN,
  MSK_SK_BAS,
  MSK_SK_FIX,
  MSK_SK_INF,
  MSK_SK_LOW,
  MSK_SK_SUPBAS,
  MSK_SK_UNK,
  MSK_SK_UPR,
  MSK_SK_BEGIN,
  MSK_SK_END,
  MSK_SIM_REFORMULATION_AGGRESSIVE,
  MSK_SIM_REFORMULATION_FREE,
  MSK_SIM_REFORMULATION_OFF,
  MSK_SIM_REFORMULATION_ON,
  MSK_SIM_REFORMULATION_BEGIN,
  MSK_SIM_REFORMULATION_END,
  MSK_IINF_ANA_PRO_NUM_CON,
  MSK_IINF_ANA_PRO_NUM_CON_EQ,
  MSK_IINF_ANA_PRO_NUM_CON_FR,
  MSK_IINF_ANA_PRO_NUM_CON_LO,
  MSK_IINF_ANA_PRO_NUM_CON_RA,
  MSK_IINF_ANA_PRO_NUM_CON_UP,
  MSK_IINF_ANA_PRO_NUM_VAR,
  MSK_IINF_ANA_PRO_NUM_VAR_BIN,
  MSK_IINF_ANA_PRO_NUM_VAR_CONT,
  MSK_IINF_ANA_PRO_NUM_VAR_EQ,
  MSK_IINF_ANA_PRO_NUM_VAR_FR,
  MSK_IINF_ANA_PRO_NUM_VAR_INT,
  MSK_IINF_ANA_PRO_NUM_VAR_LO,
  MSK_IINF_ANA_PRO_NUM_VAR_RA,
  MSK_IINF_ANA_PRO_NUM_VAR_UP,
  MSK_IINF_CONCURRENT_WINNING_OPTIMIZER,
  MSK_IINF_INTPNT_FACTOR_DIM_DENSE,
  MSK_IINF_INTPNT_ITER,
  MSK_IINF_INTPNT_NUM_THREADS,
  MSK_IINF_INTPNT_SOLVE_DUAL,
  MSK_IINF_MIO_ABSGAP_SATISFIED,
  MSK_IINF_MIO_CLIQUE_TABLE_SIZE,
  MSK_IINF_MIO_CONSTRUCT_NUM_ROUNDINGS,
  MSK_IINF_MIO_CONSTRUCT_SOLUTION,
  MSK_IINF_MIO_INITIAL_SOLUTION,
  MSK_IINF_MIO_NEAR_ABSGAP_SATISFIED,
  MSK_IINF_MIO_NEAR_RELGAP_SATISFIED,
  MSK_IINF_MIO_NODE_DEPTH,
  MSK_IINF_MIO_NUM_ACTIVE_NODES,
  MSK_IINF_MIO_NUM_BRANCH,
  MSK_IINF_MIO_NUM_CLIQUE_CUTS,
  MSK_IINF_MIO_NUM_CMIR_CUTS,
  MSK_IINF_MIO_NUM_GOMORY_CUTS,
  MSK_IINF_MIO_NUM_IMPLIED_BOUND_CUTS,
  MSK_IINF_MIO_NUM_INT_SOLUTIONS,
  MSK_IINF_MIO_NUM_KNAPSACK_COVER_CUTS,
  MSK_IINF_MIO_NUM_RELAX,
  MSK_IINF_MIO_NUM_REPEATED_PRESOLVE,
  MSK_IINF_MIO_NUMCON,
  MSK_IINF_MIO_NUMINT,
  MSK_IINF_MIO_NUMVAR,
  MSK_IINF_MIO_OBJ_BOUND_DEFINED,
  MSK_IINF_MIO_PRESOLVED_NUMBIN,
  MSK_IINF_MIO_PRESOLVED_NUMCON,
  MSK_IINF_MIO_PRESOLVED_NUMCONT,
  MSK_IINF_MIO_PRESOLVED_NUMINT,
  MSK_IINF_MIO_PRESOLVED_NUMVAR,
  MSK_IINF_MIO_RELGAP_SATISFIED,
  MSK_IINF_MIO_TOTAL_NUM_CUTS,
  MSK_IINF_MIO_USER_OBJ_CUT,
  MSK_IINF_OPT_NUMCON,
  MSK_IINF_OPT_NUMVAR,
  MSK_IINF_OPTIMIZE_RESPONSE,
  MSK_IINF_RD_NUMBARVAR,
  MSK_IINF_RD_NUMCON,
  MSK_IINF_RD_NUMCONE,
  MSK_IINF_RD_NUMINTVAR,
  MSK_IINF_RD_NUMQ,
  MSK_IINF_RD_NUMVAR,
  MSK_IINF_RD_PROTYPE,
  MSK_IINF_SIM_DUAL_DEG_ITER,
  MSK_IINF_SIM_DUAL_HOTSTART,
  MSK_IINF_SIM_DUAL_HOTSTART_LU,
  MSK_IINF_SIM_DUAL_INF_ITER,
  MSK_IINF_SIM_DUAL_ITER,
  MSK_IINF_SIM_NETWORK_DUAL_DEG_ITER,
  MSK_IINF_SIM_NETWORK_DUAL_HOTSTART,
  MSK_IINF_SIM_NETWORK_DUAL_HOTSTART_LU,
  MSK_IINF_SIM_NETWORK_DUAL_INF_ITER,
  MSK_IINF_SIM_NETWORK_DUAL_ITER,
  MSK_IINF_SIM_NETWORK_PRIMAL_DEG_ITER,
  MSK_IINF_SIM_NETWORK_PRIMAL_HOTSTART,
  MSK_IINF_SIM_NETWORK_PRIMAL_HOTSTART_LU,
  MSK_IINF_SIM_NETWORK_PRIMAL_INF_ITER,
  MSK_IINF_SIM_NETWORK_PRIMAL_ITER,
  MSK_IINF_SIM_NUMCON,
  MSK_IINF_SIM_NUMVAR,
  MSK_IINF_SIM_PRIMAL_DEG_ITER,
  MSK_IINF_SIM_PRIMAL_DUAL_DEG_ITER,
  MSK_IINF_SIM_PRIMAL_DUAL_HOTSTART,
  MSK_IINF_SIM_PRIMAL_DUAL_HOTSTART_LU,
  MSK_IINF_SIM_PRIMAL_DUAL_INF_ITER,
  MSK_IINF_SIM_PRIMAL_DUAL_ITER,
  MSK_IINF_SIM_PRIMAL_HOTSTART,
  MSK_IINF_SIM_PRIMAL_HOTSTART_LU,
  MSK_IINF_SIM_PRIMAL_INF_ITER,
  MSK_IINF_SIM_PRIMAL_ITER,
  MSK_IINF_SIM_SOLVE_DUAL,
  MSK_IINF_SOL_BAS_PROSTA,
  MSK_IINF_SOL_BAS_SOLSTA,
  MSK_IINF_SOL_ITG_PROSTA,
  MSK_IINF_SOL_ITG_SOLSTA,
  MSK_IINF_SOL_ITR_PROSTA,
  MSK_IINF_SOL_ITR_SOLSTA,
  MSK_IINF_STO_NUM_A_REALLOC,
  MSK_IINF_BEGIN,
  MSK_IINF_END,
  MSK_WRITE_XML_MODE_COL,
  MSK_WRITE_XML_MODE_ROW,
  MSK_WRITE_XML_MODE_BEGIN,
  MSK_WRITE_XML_MODE_END,
  MSK_OPTIMIZER_CONIC,
  MSK_OPTIMIZER_DUAL_SIMPLEX,
  MSK_OPTIMIZER_FREE,
  MSK_OPTIMIZER_FREE_SIMPLEX,
  MSK_OPTIMIZER_INTPNT,
  MSK_OPTIMIZER_MIXED_INT,
  MSK_OPTIMIZER_PRIMAL_SIMPLEX,
  MSK_OPTIMIZER_BEGIN,
  MSK_OPTIMIZER_END,
  MSK_PRESOLVE_MODE_FREE,
  MSK_PRESOLVE_MODE_OFF,
  MSK_PRESOLVE_MODE_ON,
  MSK_PRESOLVE_MODE_BEGIN,
  MSK_PRESOLVE_MODE_END,
  MSK_MIO_CONT_SOL_ITG,
  MSK_MIO_CONT_SOL_ITG_REL,
  MSK_MIO_CONT_SOL_NONE,
  MSK_MIO_CONT_SOL_ROOT,
  MSK_MIO_CONT_SOL_BEGIN,
  MSK_MIO_CONT_SOL_END

# enum solveform
MSK_SOLVE_DUAL = Int32(2)
MSK_SOLVE_FREE = Int32(0)
MSK_SOLVE_PRIMAL = Int32(1)

  MSK_SOLVE_BEGIN = Int32(0)
  MSK_SOLVE_END   = Int32(3)

# enum problemitem
MSK_PI_CON = Int32(1)
MSK_PI_CONE = Int32(2)
MSK_PI_VAR = Int32(0)

  MSK_PI_BEGIN = Int32(0)
  MSK_PI_END   = Int32(3)

# enum accmode
MSK_ACC_CON = Int32(1)
MSK_ACC_VAR = Int32(0)

  MSK_ACC_BEGIN = Int32(0)
  MSK_ACC_END   = Int32(2)

# enum sensitivitytype
MSK_SENSITIVITY_TYPE_BASIS = Int32(0)
MSK_SENSITIVITY_TYPE_OPTIMAL_PARTITION = Int32(1)

  MSK_SENSITIVITY_TYPE_BEGIN = Int32(0)
  MSK_SENSITIVITY_TYPE_END   = Int32(2)

# enum uplo
MSK_UPLO_LO = Int32(0)
MSK_UPLO_UP = Int32(1)

  MSK_UPLO_BEGIN = Int32(0)
  MSK_UPLO_END   = Int32(2)

# enum intpnthotstart
MSK_INTPNT_HOTSTART_DUAL = Int32(2)
MSK_INTPNT_HOTSTART_NONE = Int32(0)
MSK_INTPNT_HOTSTART_PRIMAL = Int32(1)
MSK_INTPNT_HOTSTART_PRIMAL_DUAL = Int32(3)

  MSK_INTPNT_HOTSTART_BEGIN = Int32(0)
  MSK_INTPNT_HOTSTART_END   = Int32(4)

# enum sparam
MSK_SPAR_BAS_SOL_FILE_NAME = Int32(0)
MSK_SPAR_DATA_FILE_NAME = Int32(1)
MSK_SPAR_DEBUG_FILE_NAME = Int32(2)
MSK_SPAR_INT_SOL_FILE_NAME = Int32(3)
MSK_SPAR_ITR_SOL_FILE_NAME = Int32(4)
MSK_SPAR_MIO_DEBUG_STRING = Int32(5)
MSK_SPAR_PARAM_COMMENT_SIGN = Int32(6)
MSK_SPAR_PARAM_READ_FILE_NAME = Int32(7)
MSK_SPAR_PARAM_WRITE_FILE_NAME = Int32(8)
MSK_SPAR_READ_MPS_BOU_NAME = Int32(9)
MSK_SPAR_READ_MPS_OBJ_NAME = Int32(10)
MSK_SPAR_READ_MPS_RAN_NAME = Int32(11)
MSK_SPAR_READ_MPS_RHS_NAME = Int32(12)
MSK_SPAR_REMOTE_ACCESS_TOKEN = Int32(13)
MSK_SPAR_SENSITIVITY_FILE_NAME = Int32(14)
MSK_SPAR_SENSITIVITY_RES_FILE_NAME = Int32(15)
MSK_SPAR_SOL_FILTER_XC_LOW = Int32(16)
MSK_SPAR_SOL_FILTER_XC_UPR = Int32(17)
MSK_SPAR_SOL_FILTER_XX_LOW = Int32(18)
MSK_SPAR_SOL_FILTER_XX_UPR = Int32(19)
MSK_SPAR_STAT_FILE_NAME = Int32(20)
MSK_SPAR_STAT_KEY = Int32(21)
MSK_SPAR_STAT_NAME = Int32(22)
MSK_SPAR_WRITE_LP_GEN_VAR_NAME = Int32(23)

  MSK_SPAR_BEGIN = Int32(0)
  MSK_SPAR_END   = Int32(24)

# enum iparam
MSK_IPAR_ANA_SOL_BASIS = Int32(0)
MSK_IPAR_ANA_SOL_PRINT_VIOLATED = Int32(1)
MSK_IPAR_AUTO_SORT_A_BEFORE_OPT = Int32(2)
MSK_IPAR_AUTO_UPDATE_SOL_INFO = Int32(3)
MSK_IPAR_BASIS_SOLVE_USE_PLUS_ONE = Int32(4)
MSK_IPAR_BI_CLEAN_OPTIMIZER = Int32(5)
MSK_IPAR_BI_IGNORE_MAX_ITER = Int32(6)
MSK_IPAR_BI_IGNORE_NUM_ERROR = Int32(7)
MSK_IPAR_BI_MAX_ITERATIONS = Int32(8)
MSK_IPAR_CACHE_LICENSE = Int32(9)
MSK_IPAR_CHECK_CONVEXITY = Int32(10)
MSK_IPAR_COMPRESS_STATFILE = Int32(11)
MSK_IPAR_CONCURRENT_NUM_OPTIMIZERS = Int32(12)
MSK_IPAR_CONCURRENT_PRIORITY_DUAL_SIMPLEX = Int32(13)
MSK_IPAR_CONCURRENT_PRIORITY_FREE_SIMPLEX = Int32(14)
MSK_IPAR_CONCURRENT_PRIORITY_INTPNT = Int32(15)
MSK_IPAR_CONCURRENT_PRIORITY_PRIMAL_SIMPLEX = Int32(16)
MSK_IPAR_FEASREPAIR_OPTIMIZE = Int32(17)
MSK_IPAR_INFEAS_GENERIC_NAMES = Int32(18)
MSK_IPAR_INFEAS_PREFER_PRIMAL = Int32(19)
MSK_IPAR_INFEAS_REPORT_AUTO = Int32(20)
MSK_IPAR_INFEAS_REPORT_LEVEL = Int32(21)
MSK_IPAR_INTPNT_BASIS = Int32(22)
MSK_IPAR_INTPNT_DIFF_STEP = Int32(23)
MSK_IPAR_INTPNT_HOTSTART = Int32(24)
MSK_IPAR_INTPNT_MAX_ITERATIONS = Int32(25)
MSK_IPAR_INTPNT_MAX_NUM_COR = Int32(26)
MSK_IPAR_INTPNT_MAX_NUM_REFINEMENT_STEPS = Int32(27)
MSK_IPAR_INTPNT_MULTI_THREAD = Int32(28)
MSK_IPAR_INTPNT_OFF_COL_TRH = Int32(29)
MSK_IPAR_INTPNT_ORDER_METHOD = Int32(30)
MSK_IPAR_INTPNT_REGULARIZATION_USE = Int32(31)
MSK_IPAR_INTPNT_SCALING = Int32(32)
MSK_IPAR_INTPNT_SOLVE_FORM = Int32(33)
MSK_IPAR_INTPNT_STARTING_POINT = Int32(34)
MSK_IPAR_LICENSE_DEBUG = Int32(35)
MSK_IPAR_LICENSE_PAUSE_TIME = Int32(36)
MSK_IPAR_LICENSE_SUPPRESS_EXPIRE_WRNS = Int32(37)
MSK_IPAR_LICENSE_TRH_EXPIRY_WRN = Int32(38)
MSK_IPAR_LICENSE_WAIT = Int32(39)
MSK_IPAR_LOG = Int32(40)
MSK_IPAR_LOG_ANA_PRO = Int32(41)
MSK_IPAR_LOG_BI = Int32(42)
MSK_IPAR_LOG_BI_FREQ = Int32(43)
MSK_IPAR_LOG_CHECK_CONVEXITY = Int32(44)
MSK_IPAR_LOG_CONCURRENT = Int32(45)
MSK_IPAR_LOG_CUT_SECOND_OPT = Int32(46)
MSK_IPAR_LOG_EXPAND = Int32(47)
MSK_IPAR_LOG_FACTOR = Int32(48)
MSK_IPAR_LOG_FEAS_REPAIR = Int32(49)
MSK_IPAR_LOG_FILE = Int32(50)
MSK_IPAR_LOG_HEAD = Int32(51)
MSK_IPAR_LOG_INFEAS_ANA = Int32(52)
MSK_IPAR_LOG_INTPNT = Int32(53)
MSK_IPAR_LOG_MIO = Int32(54)
MSK_IPAR_LOG_MIO_FREQ = Int32(55)
MSK_IPAR_LOG_OPTIMIZER = Int32(56)
MSK_IPAR_LOG_ORDER = Int32(57)
MSK_IPAR_LOG_PRESOLVE = Int32(58)
MSK_IPAR_LOG_RESPONSE = Int32(59)
MSK_IPAR_LOG_SENSITIVITY = Int32(60)
MSK_IPAR_LOG_SENSITIVITY_OPT = Int32(61)
MSK_IPAR_LOG_SIM = Int32(62)
MSK_IPAR_LOG_SIM_FREQ = Int32(63)
MSK_IPAR_LOG_SIM_MINOR = Int32(64)
MSK_IPAR_LOG_STORAGE = Int32(65)
MSK_IPAR_MAX_NUM_WARNINGS = Int32(66)
MSK_IPAR_MIO_BRANCH_DIR = Int32(67)
MSK_IPAR_MIO_CONSTRUCT_SOL = Int32(68)
MSK_IPAR_MIO_CUT_CLIQUE = Int32(69)
MSK_IPAR_MIO_CUT_CMIR = Int32(70)
MSK_IPAR_MIO_CUT_GMI = Int32(71)
MSK_IPAR_MIO_CUT_IMPLIED_BOUND = Int32(72)
MSK_IPAR_MIO_CUT_KNAPSACK_COVER = Int32(73)
MSK_IPAR_MIO_CUT_SELECTION_LEVEL = Int32(74)
MSK_IPAR_MIO_HEURISTIC_LEVEL = Int32(75)
MSK_IPAR_MIO_MAX_NUM_BRANCHES = Int32(76)
MSK_IPAR_MIO_MAX_NUM_RELAXS = Int32(77)
MSK_IPAR_MIO_MAX_NUM_SOLUTIONS = Int32(78)
MSK_IPAR_MIO_MODE = Int32(79)
MSK_IPAR_MIO_MT_USER_CB = Int32(80)
MSK_IPAR_MIO_NODE_OPTIMIZER = Int32(81)
MSK_IPAR_MIO_NODE_SELECTION = Int32(82)
MSK_IPAR_MIO_PERSPECTIVE_REFORMULATE = Int32(83)
MSK_IPAR_MIO_PROBING_LEVEL = Int32(84)
MSK_IPAR_MIO_RINS_MAX_NODES = Int32(85)
MSK_IPAR_MIO_ROOT_OPTIMIZER = Int32(86)
MSK_IPAR_MIO_ROOT_REPEAT_PRESOLVE_LEVEL = Int32(87)
MSK_IPAR_MIO_VB_DETECTION_LEVEL = Int32(88)
MSK_IPAR_MT_SPINCOUNT = Int32(89)
MSK_IPAR_NUM_THREADS = Int32(90)
MSK_IPAR_OPF_MAX_TERMS_PER_LINE = Int32(91)
MSK_IPAR_OPF_WRITE_HEADER = Int32(92)
MSK_IPAR_OPF_WRITE_HINTS = Int32(93)
MSK_IPAR_OPF_WRITE_PARAMETERS = Int32(94)
MSK_IPAR_OPF_WRITE_PROBLEM = Int32(95)
MSK_IPAR_OPF_WRITE_SOL_BAS = Int32(96)
MSK_IPAR_OPF_WRITE_SOL_ITG = Int32(97)
MSK_IPAR_OPF_WRITE_SOL_ITR = Int32(98)
MSK_IPAR_OPF_WRITE_SOLUTIONS = Int32(99)
MSK_IPAR_OPTIMIZER = Int32(100)
MSK_IPAR_PARAM_READ_CASE_NAME = Int32(101)
MSK_IPAR_PARAM_READ_IGN_ERROR = Int32(102)
MSK_IPAR_PRESOLVE_ELIMINATOR_MAX_FILL = Int32(103)
MSK_IPAR_PRESOLVE_ELIMINATOR_MAX_NUM_TRIES = Int32(104)
MSK_IPAR_PRESOLVE_LEVEL = Int32(105)
MSK_IPAR_PRESOLVE_LINDEP_ABS_WORK_TRH = Int32(106)
MSK_IPAR_PRESOLVE_LINDEP_REL_WORK_TRH = Int32(107)
MSK_IPAR_PRESOLVE_LINDEP_USE = Int32(108)
MSK_IPAR_PRESOLVE_MAX_NUM_REDUCTIONS = Int32(109)
MSK_IPAR_PRESOLVE_USE = Int32(110)
MSK_IPAR_PRIMAL_REPAIR_OPTIMIZER = Int32(111)
MSK_IPAR_READ_DATA_COMPRESSED = Int32(112)
MSK_IPAR_READ_DATA_FORMAT = Int32(113)
MSK_IPAR_READ_DEBUG = Int32(114)
MSK_IPAR_READ_KEEP_FREE_CON = Int32(115)
MSK_IPAR_READ_LP_DROP_NEW_VARS_IN_BOU = Int32(116)
MSK_IPAR_READ_LP_QUOTED_NAMES = Int32(117)
MSK_IPAR_READ_MPS_FORMAT = Int32(118)
MSK_IPAR_READ_MPS_WIDTH = Int32(119)
MSK_IPAR_READ_TASK_IGNORE_PARAM = Int32(120)
MSK_IPAR_SENSITIVITY_ALL = Int32(121)
MSK_IPAR_SENSITIVITY_OPTIMIZER = Int32(122)
MSK_IPAR_SENSITIVITY_TYPE = Int32(123)
MSK_IPAR_SIM_BASIS_FACTOR_USE = Int32(124)
MSK_IPAR_SIM_DEGEN = Int32(125)
MSK_IPAR_SIM_DUAL_CRASH = Int32(126)
MSK_IPAR_SIM_DUAL_PHASEONE_METHOD = Int32(127)
MSK_IPAR_SIM_DUAL_RESTRICT_SELECTION = Int32(128)
MSK_IPAR_SIM_DUAL_SELECTION = Int32(129)
MSK_IPAR_SIM_EXPLOIT_DUPVEC = Int32(130)
MSK_IPAR_SIM_HOTSTART = Int32(131)
MSK_IPAR_SIM_HOTSTART_LU = Int32(132)
MSK_IPAR_SIM_INTEGER = Int32(133)
MSK_IPAR_SIM_MAX_ITERATIONS = Int32(134)
MSK_IPAR_SIM_MAX_NUM_SETBACKS = Int32(135)
MSK_IPAR_SIM_NON_SINGULAR = Int32(136)
MSK_IPAR_SIM_PRIMAL_CRASH = Int32(137)
MSK_IPAR_SIM_PRIMAL_PHASEONE_METHOD = Int32(138)
MSK_IPAR_SIM_PRIMAL_RESTRICT_SELECTION = Int32(139)
MSK_IPAR_SIM_PRIMAL_SELECTION = Int32(140)
MSK_IPAR_SIM_REFACTOR_FREQ = Int32(141)
MSK_IPAR_SIM_REFORMULATION = Int32(142)
MSK_IPAR_SIM_SAVE_LU = Int32(143)
MSK_IPAR_SIM_SCALING = Int32(144)
MSK_IPAR_SIM_SCALING_METHOD = Int32(145)
MSK_IPAR_SIM_SOLVE_FORM = Int32(146)
MSK_IPAR_SIM_STABILITY_PRIORITY = Int32(147)
MSK_IPAR_SIM_SWITCH_OPTIMIZER = Int32(148)
MSK_IPAR_SOL_FILTER_KEEP_BASIC = Int32(149)
MSK_IPAR_SOL_FILTER_KEEP_RANGED = Int32(150)
MSK_IPAR_SOL_READ_NAME_WIDTH = Int32(151)
MSK_IPAR_SOL_READ_WIDTH = Int32(152)
MSK_IPAR_SOLUTION_CALLBACK = Int32(153)
MSK_IPAR_TIMING_LEVEL = Int32(154)
MSK_IPAR_WRITE_BAS_CONSTRAINTS = Int32(155)
MSK_IPAR_WRITE_BAS_HEAD = Int32(156)
MSK_IPAR_WRITE_BAS_VARIABLES = Int32(157)
MSK_IPAR_WRITE_DATA_COMPRESSED = Int32(158)
MSK_IPAR_WRITE_DATA_FORMAT = Int32(159)
MSK_IPAR_WRITE_DATA_PARAM = Int32(160)
MSK_IPAR_WRITE_FREE_CON = Int32(161)
MSK_IPAR_WRITE_GENERIC_NAMES = Int32(162)
MSK_IPAR_WRITE_GENERIC_NAMES_IO = Int32(163)
MSK_IPAR_WRITE_IGNORE_INCOMPATIBLE_CONIC_ITEMS = Int32(164)
MSK_IPAR_WRITE_IGNORE_INCOMPATIBLE_ITEMS = Int32(165)
MSK_IPAR_WRITE_IGNORE_INCOMPATIBLE_NL_ITEMS = Int32(166)
MSK_IPAR_WRITE_IGNORE_INCOMPATIBLE_PSD_ITEMS = Int32(167)
MSK_IPAR_WRITE_INT_CONSTRAINTS = Int32(168)
MSK_IPAR_WRITE_INT_HEAD = Int32(169)
MSK_IPAR_WRITE_INT_VARIABLES = Int32(170)
MSK_IPAR_WRITE_LP_FULL_OBJ = Int32(171)
MSK_IPAR_WRITE_LP_LINE_WIDTH = Int32(172)
MSK_IPAR_WRITE_LP_QUOTED_NAMES = Int32(173)
MSK_IPAR_WRITE_LP_STRICT_FORMAT = Int32(174)
MSK_IPAR_WRITE_LP_TERMS_PER_LINE = Int32(175)
MSK_IPAR_WRITE_MPS_FORMAT = Int32(176)
MSK_IPAR_WRITE_MPS_INT = Int32(177)
MSK_IPAR_WRITE_PRECISION = Int32(178)
MSK_IPAR_WRITE_SOL_BARVARIABLES = Int32(179)
MSK_IPAR_WRITE_SOL_CONSTRAINTS = Int32(180)
MSK_IPAR_WRITE_SOL_HEAD = Int32(181)
MSK_IPAR_WRITE_SOL_IGNORE_INVALID_NAMES = Int32(182)
MSK_IPAR_WRITE_SOL_VARIABLES = Int32(183)
MSK_IPAR_WRITE_TASK_INC_SOL = Int32(184)
MSK_IPAR_WRITE_XML_MODE = Int32(185)

  MSK_IPAR_BEGIN = Int32(0)
  MSK_IPAR_END   = Int32(186)

# enum solsta
MSK_SOL_STA_DUAL_FEAS = Int32(3)
MSK_SOL_STA_DUAL_ILLPOSED_CER = Int32(15)
MSK_SOL_STA_DUAL_INFEAS_CER = Int32(6)
MSK_SOL_STA_INTEGER_OPTIMAL = Int32(16)
MSK_SOL_STA_NEAR_DUAL_FEAS = Int32(10)
MSK_SOL_STA_NEAR_DUAL_INFEAS_CER = Int32(13)
MSK_SOL_STA_NEAR_INTEGER_OPTIMAL = Int32(17)
MSK_SOL_STA_NEAR_OPTIMAL = Int32(8)
MSK_SOL_STA_NEAR_PRIM_AND_DUAL_FEAS = Int32(11)
MSK_SOL_STA_NEAR_PRIM_FEAS = Int32(9)
MSK_SOL_STA_NEAR_PRIM_INFEAS_CER = Int32(12)
MSK_SOL_STA_OPTIMAL = Int32(1)
MSK_SOL_STA_PRIM_AND_DUAL_FEAS = Int32(4)
MSK_SOL_STA_PRIM_FEAS = Int32(2)
MSK_SOL_STA_PRIM_ILLPOSED_CER = Int32(14)
MSK_SOL_STA_PRIM_INFEAS_CER = Int32(5)
MSK_SOL_STA_UNKNOWN = Int32(0)

  MSK_SOL_STA_BEGIN = Int32(0)
  MSK_SOL_STA_END   = Int32(18)

# enum objsense
MSK_OBJECTIVE_SENSE_MAXIMIZE = Int32(1)
MSK_OBJECTIVE_SENSE_MINIMIZE = Int32(0)

  MSK_OBJECTIVE_SENSE_BEGIN = Int32(0)
  MSK_OBJECTIVE_SENSE_END   = Int32(2)

# enum solitem
MSK_SOL_ITEM_SLC = Int32(3)
MSK_SOL_ITEM_SLX = Int32(5)
MSK_SOL_ITEM_SNX = Int32(7)
MSK_SOL_ITEM_SUC = Int32(4)
MSK_SOL_ITEM_SUX = Int32(6)
MSK_SOL_ITEM_XC = Int32(0)
MSK_SOL_ITEM_XX = Int32(1)
MSK_SOL_ITEM_Y = Int32(2)

  MSK_SOL_ITEM_BEGIN = Int32(0)
  MSK_SOL_ITEM_END   = Int32(8)

# enum boundkey
MSK_BK_FR = Int32(3)
MSK_BK_FX = Int32(2)
MSK_BK_LO = Int32(0)
MSK_BK_RA = Int32(4)
MSK_BK_UP = Int32(1)

  MSK_BK_BEGIN = Int32(0)
  MSK_BK_END   = Int32(5)

# enum basindtype
MSK_BI_ALWAYS = Int32(1)
MSK_BI_IF_FEASIBLE = Int32(3)
MSK_BI_NEVER = Int32(0)
MSK_BI_NO_ERROR = Int32(2)
MSK_BI_RESERVERED = Int32(4)

  MSK_BI_BEGIN = Int32(0)
  MSK_BI_END   = Int32(5)

# enum branchdir
MSK_BRANCH_DIR_DOWN = Int32(2)
MSK_BRANCH_DIR_FAR = Int32(4)
MSK_BRANCH_DIR_FREE = Int32(0)
MSK_BRANCH_DIR_GUIDED = Int32(6)
MSK_BRANCH_DIR_NEAR = Int32(3)
MSK_BRANCH_DIR_PSEUDOCOST = Int32(7)
MSK_BRANCH_DIR_ROOT_LP = Int32(5)
MSK_BRANCH_DIR_UP = Int32(1)

  MSK_BRANCH_DIR_BEGIN = Int32(0)
  MSK_BRANCH_DIR_END   = Int32(8)

# enum liinfitem
MSK_LIINF_BI_CLEAN_DUAL_DEG_ITER = Int32(0)
MSK_LIINF_BI_CLEAN_DUAL_ITER = Int32(1)
MSK_LIINF_BI_CLEAN_PRIMAL_DEG_ITER = Int32(2)
MSK_LIINF_BI_CLEAN_PRIMAL_DUAL_DEG_ITER = Int32(3)
MSK_LIINF_BI_CLEAN_PRIMAL_DUAL_ITER = Int32(4)
MSK_LIINF_BI_CLEAN_PRIMAL_DUAL_SUB_ITER = Int32(5)
MSK_LIINF_BI_CLEAN_PRIMAL_ITER = Int32(6)
MSK_LIINF_BI_DUAL_ITER = Int32(7)
MSK_LIINF_BI_PRIMAL_ITER = Int32(8)
MSK_LIINF_INTPNT_FACTOR_NUM_NZ = Int32(9)
MSK_LIINF_MIO_INTPNT_ITER = Int32(10)
MSK_LIINF_MIO_PRESOLVED_ANZ = Int32(11)
MSK_LIINF_MIO_SIM_MAXITER_SETBACKS = Int32(12)
MSK_LIINF_MIO_SIMPLEX_ITER = Int32(13)
MSK_LIINF_RD_NUMANZ = Int32(14)
MSK_LIINF_RD_NUMQNZ = Int32(15)

  MSK_LIINF_BEGIN = Int32(0)
  MSK_LIINF_END   = Int32(16)

# enum streamtype
MSK_STREAM_ERR = Int32(2)
MSK_STREAM_LOG = Int32(0)
MSK_STREAM_MSG = Int32(1)
MSK_STREAM_WRN = Int32(3)

  MSK_STREAM_BEGIN = Int32(0)
  MSK_STREAM_END   = Int32(4)

# enum simhotstart
MSK_SIM_HOTSTART_FREE = Int32(1)
MSK_SIM_HOTSTART_NONE = Int32(0)
MSK_SIM_HOTSTART_STATUS_KEYS = Int32(2)

  MSK_SIM_HOTSTART_BEGIN = Int32(0)
  MSK_SIM_HOTSTART_END   = Int32(3)

# enum callbackcode
MSK_CALLBACK_BEGIN_BI = Int32(0)
MSK_CALLBACK_BEGIN_CONCURRENT = Int32(1)
MSK_CALLBACK_BEGIN_CONIC = Int32(2)
MSK_CALLBACK_BEGIN_DUAL_BI = Int32(3)
MSK_CALLBACK_BEGIN_DUAL_SENSITIVITY = Int32(4)
MSK_CALLBACK_BEGIN_DUAL_SETUP_BI = Int32(5)
MSK_CALLBACK_BEGIN_DUAL_SIMPLEX = Int32(6)
MSK_CALLBACK_BEGIN_DUAL_SIMPLEX_BI = Int32(7)
MSK_CALLBACK_BEGIN_FULL_CONVEXITY_CHECK = Int32(8)
MSK_CALLBACK_BEGIN_INFEAS_ANA = Int32(9)
MSK_CALLBACK_BEGIN_INTPNT = Int32(10)
MSK_CALLBACK_BEGIN_LICENSE_WAIT = Int32(11)
MSK_CALLBACK_BEGIN_MIO = Int32(12)
MSK_CALLBACK_BEGIN_NETWORK_DUAL_SIMPLEX = Int32(13)
MSK_CALLBACK_BEGIN_NETWORK_PRIMAL_SIMPLEX = Int32(14)
MSK_CALLBACK_BEGIN_NETWORK_SIMPLEX = Int32(15)
MSK_CALLBACK_BEGIN_OPTIMIZER = Int32(16)
MSK_CALLBACK_BEGIN_PRESOLVE = Int32(17)
MSK_CALLBACK_BEGIN_PRIMAL_BI = Int32(18)
MSK_CALLBACK_BEGIN_PRIMAL_DUAL_SIMPLEX = Int32(19)
MSK_CALLBACK_BEGIN_PRIMAL_DUAL_SIMPLEX_BI = Int32(20)
MSK_CALLBACK_BEGIN_PRIMAL_REPAIR = Int32(21)
MSK_CALLBACK_BEGIN_PRIMAL_SENSITIVITY = Int32(22)
MSK_CALLBACK_BEGIN_PRIMAL_SETUP_BI = Int32(23)
MSK_CALLBACK_BEGIN_PRIMAL_SIMPLEX = Int32(24)
MSK_CALLBACK_BEGIN_PRIMAL_SIMPLEX_BI = Int32(25)
MSK_CALLBACK_BEGIN_QCQO_REFORMULATE = Int32(26)
MSK_CALLBACK_BEGIN_READ = Int32(27)
MSK_CALLBACK_BEGIN_ROOT_CUTGEN = Int32(28)
MSK_CALLBACK_BEGIN_SIMPLEX = Int32(29)
MSK_CALLBACK_BEGIN_SIMPLEX_BI = Int32(30)
MSK_CALLBACK_BEGIN_SIMPLEX_NETWORK_DETECT = Int32(31)
MSK_CALLBACK_BEGIN_TO_CONIC = Int32(32)
MSK_CALLBACK_BEGIN_WRITE = Int32(33)
MSK_CALLBACK_CONIC = Int32(34)
MSK_CALLBACK_DUAL_SIMPLEX = Int32(35)
MSK_CALLBACK_END_BI = Int32(36)
MSK_CALLBACK_END_CONCURRENT = Int32(37)
MSK_CALLBACK_END_CONIC = Int32(38)
MSK_CALLBACK_END_DUAL_BI = Int32(39)
MSK_CALLBACK_END_DUAL_SENSITIVITY = Int32(40)
MSK_CALLBACK_END_DUAL_SETUP_BI = Int32(41)
MSK_CALLBACK_END_DUAL_SIMPLEX = Int32(42)
MSK_CALLBACK_END_DUAL_SIMPLEX_BI = Int32(43)
MSK_CALLBACK_END_FULL_CONVEXITY_CHECK = Int32(44)
MSK_CALLBACK_END_INFEAS_ANA = Int32(45)
MSK_CALLBACK_END_INTPNT = Int32(46)
MSK_CALLBACK_END_LICENSE_WAIT = Int32(47)
MSK_CALLBACK_END_MIO = Int32(48)
MSK_CALLBACK_END_NETWORK_DUAL_SIMPLEX = Int32(49)
MSK_CALLBACK_END_NETWORK_PRIMAL_SIMPLEX = Int32(50)
MSK_CALLBACK_END_NETWORK_SIMPLEX = Int32(51)
MSK_CALLBACK_END_OPTIMIZER = Int32(52)
MSK_CALLBACK_END_PRESOLVE = Int32(53)
MSK_CALLBACK_END_PRIMAL_BI = Int32(54)
MSK_CALLBACK_END_PRIMAL_DUAL_SIMPLEX = Int32(55)
MSK_CALLBACK_END_PRIMAL_DUAL_SIMPLEX_BI = Int32(56)
MSK_CALLBACK_END_PRIMAL_REPAIR = Int32(57)
MSK_CALLBACK_END_PRIMAL_SENSITIVITY = Int32(58)
MSK_CALLBACK_END_PRIMAL_SETUP_BI = Int32(59)
MSK_CALLBACK_END_PRIMAL_SIMPLEX = Int32(60)
MSK_CALLBACK_END_PRIMAL_SIMPLEX_BI = Int32(61)
MSK_CALLBACK_END_QCQO_REFORMULATE = Int32(62)
MSK_CALLBACK_END_READ = Int32(63)
MSK_CALLBACK_END_ROOT_CUTGEN = Int32(64)
MSK_CALLBACK_END_SIMPLEX = Int32(65)
MSK_CALLBACK_END_SIMPLEX_BI = Int32(66)
MSK_CALLBACK_END_SIMPLEX_NETWORK_DETECT = Int32(67)
MSK_CALLBACK_END_TO_CONIC = Int32(68)
MSK_CALLBACK_END_WRITE = Int32(69)
MSK_CALLBACK_IM_BI = Int32(70)
MSK_CALLBACK_IM_CONIC = Int32(71)
MSK_CALLBACK_IM_DUAL_BI = Int32(72)
MSK_CALLBACK_IM_DUAL_SENSIVITY = Int32(73)
MSK_CALLBACK_IM_DUAL_SIMPLEX = Int32(74)
MSK_CALLBACK_IM_FULL_CONVEXITY_CHECK = Int32(75)
MSK_CALLBACK_IM_INTPNT = Int32(76)
MSK_CALLBACK_IM_LICENSE_WAIT = Int32(77)
MSK_CALLBACK_IM_LU = Int32(78)
MSK_CALLBACK_IM_MIO = Int32(79)
MSK_CALLBACK_IM_MIO_DUAL_SIMPLEX = Int32(80)
MSK_CALLBACK_IM_MIO_INTPNT = Int32(81)
MSK_CALLBACK_IM_MIO_PRIMAL_SIMPLEX = Int32(82)
MSK_CALLBACK_IM_NETWORK_DUAL_SIMPLEX = Int32(83)
MSK_CALLBACK_IM_NETWORK_PRIMAL_SIMPLEX = Int32(84)
MSK_CALLBACK_IM_ORDER = Int32(85)
MSK_CALLBACK_IM_PRESOLVE = Int32(86)
MSK_CALLBACK_IM_PRIMAL_BI = Int32(87)
MSK_CALLBACK_IM_PRIMAL_DUAL_SIMPLEX = Int32(88)
MSK_CALLBACK_IM_PRIMAL_SENSIVITY = Int32(89)
MSK_CALLBACK_IM_PRIMAL_SIMPLEX = Int32(90)
MSK_CALLBACK_IM_QO_REFORMULATE = Int32(91)
MSK_CALLBACK_IM_READ = Int32(92)
MSK_CALLBACK_IM_ROOT_CUTGEN = Int32(93)
MSK_CALLBACK_IM_SIMPLEX = Int32(94)
MSK_CALLBACK_IM_SIMPLEX_BI = Int32(95)
MSK_CALLBACK_INTPNT = Int32(96)
MSK_CALLBACK_NEW_INT_MIO = Int32(97)
MSK_CALLBACK_PRIMAL_SIMPLEX = Int32(98)
MSK_CALLBACK_READ_OPF = Int32(99)
MSK_CALLBACK_READ_OPF_SECTION = Int32(100)
MSK_CALLBACK_SOLVING_REMOTE = Int32(101)
MSK_CALLBACK_UPDATE_DUAL_BI = Int32(102)
MSK_CALLBACK_UPDATE_DUAL_SIMPLEX = Int32(103)
MSK_CALLBACK_UPDATE_DUAL_SIMPLEX_BI = Int32(104)
MSK_CALLBACK_UPDATE_NETWORK_DUAL_SIMPLEX = Int32(105)
MSK_CALLBACK_UPDATE_NETWORK_PRIMAL_SIMPLEX = Int32(106)
MSK_CALLBACK_UPDATE_PRESOLVE = Int32(107)
MSK_CALLBACK_UPDATE_PRIMAL_BI = Int32(108)
MSK_CALLBACK_UPDATE_PRIMAL_DUAL_SIMPLEX = Int32(109)
MSK_CALLBACK_UPDATE_PRIMAL_DUAL_SIMPLEX_BI = Int32(110)
MSK_CALLBACK_UPDATE_PRIMAL_SIMPLEX = Int32(111)
MSK_CALLBACK_UPDATE_PRIMAL_SIMPLEX_BI = Int32(112)
MSK_CALLBACK_WRITE_OPF = Int32(113)

  MSK_CALLBACK_BEGIN = Int32(0)
  MSK_CALLBACK_END   = Int32(114)

# enum symmattype
MSK_SYMMAT_TYPE_SPARSE = Int32(0)

  MSK_SYMMAT_TYPE_BEGIN = Int32(0)
  MSK_SYMMAT_TYPE_END   = Int32(1)

# enum feature
MSK_FEATURE_PTON = Int32(1)
MSK_FEATURE_PTS = Int32(0)

  MSK_FEATURE_BEGIN = Int32(0)
  MSK_FEATURE_END   = Int32(2)

# enum mark
MSK_MARK_LO = Int32(0)
MSK_MARK_UP = Int32(1)

  MSK_MARK_BEGIN = Int32(0)
  MSK_MARK_END   = Int32(2)

# enum conetype
MSK_CT_QUAD = Int32(0)
MSK_CT_RQUAD = Int32(1)

  MSK_CT_BEGIN = Int32(0)
  MSK_CT_END   = Int32(2)

# enum feasrepairtype
MSK_FEASREPAIR_OPTIMIZE_COMBINED = Int32(2)
MSK_FEASREPAIR_OPTIMIZE_NONE = Int32(0)
MSK_FEASREPAIR_OPTIMIZE_PENALTY = Int32(1)

  MSK_FEASREPAIR_BEGIN = Int32(0)
  MSK_FEASREPAIR_END   = Int32(3)

# enum iomode
MSK_IOMODE_READ = Int32(0)
MSK_IOMODE_READWRITE = Int32(2)
MSK_IOMODE_WRITE = Int32(1)

  MSK_IOMODE_BEGIN = Int32(0)
  MSK_IOMODE_END   = Int32(3)

# enum simseltype
MSK_SIM_SELECTION_ASE = Int32(2)
MSK_SIM_SELECTION_DEVEX = Int32(3)
MSK_SIM_SELECTION_FREE = Int32(0)
MSK_SIM_SELECTION_FULL = Int32(1)
MSK_SIM_SELECTION_PARTIAL = Int32(5)
MSK_SIM_SELECTION_SE = Int32(4)

  MSK_SIM_SELECTION_BEGIN = Int32(0)
  MSK_SIM_SELECTION_END   = Int32(6)

# enum msgkey
MSK_MSG_MPS_SELECTED = Int32(1100)
MSK_MSG_READING_FILE = Int32(1000)
MSK_MSG_WRITING_FILE = Int32(1001)

# enum miomode
MSK_MIO_MODE_IGNORED = Int32(0)
MSK_MIO_MODE_SATISFIED = Int32(1)

  MSK_MIO_MODE_BEGIN = Int32(0)
  MSK_MIO_MODE_END   = Int32(2)

# enum dinfitem
MSK_DINF_BI_CLEAN_DUAL_TIME = Int32(0)
MSK_DINF_BI_CLEAN_PRIMAL_DUAL_TIME = Int32(1)
MSK_DINF_BI_CLEAN_PRIMAL_TIME = Int32(2)
MSK_DINF_BI_CLEAN_TIME = Int32(3)
MSK_DINF_BI_DUAL_TIME = Int32(4)
MSK_DINF_BI_PRIMAL_TIME = Int32(5)
MSK_DINF_BI_TIME = Int32(6)
MSK_DINF_CONCURRENT_TIME = Int32(7)
MSK_DINF_INTPNT_DUAL_FEAS = Int32(8)
MSK_DINF_INTPNT_DUAL_OBJ = Int32(9)
MSK_DINF_INTPNT_FACTOR_NUM_FLOPS = Int32(10)
MSK_DINF_INTPNT_OPT_STATUS = Int32(11)
MSK_DINF_INTPNT_ORDER_TIME = Int32(12)
MSK_DINF_INTPNT_PRIMAL_FEAS = Int32(13)
MSK_DINF_INTPNT_PRIMAL_OBJ = Int32(14)
MSK_DINF_INTPNT_TIME = Int32(15)
MSK_DINF_MIO_CLIQUE_SEPARATION_TIME = Int32(16)
MSK_DINF_MIO_CMIR_SEPARATION_TIME = Int32(17)
MSK_DINF_MIO_CONSTRUCT_SOLUTION_OBJ = Int32(18)
MSK_DINF_MIO_DUAL_BOUND_AFTER_PRESOLVE = Int32(19)
MSK_DINF_MIO_GMI_SEPARATION_TIME = Int32(20)
MSK_DINF_MIO_HEURISTIC_TIME = Int32(21)
MSK_DINF_MIO_IMPLIED_BOUND_TIME = Int32(22)
MSK_DINF_MIO_KNAPSACK_COVER_SEPARATION_TIME = Int32(23)
MSK_DINF_MIO_OBJ_ABS_GAP = Int32(24)
MSK_DINF_MIO_OBJ_BOUND = Int32(25)
MSK_DINF_MIO_OBJ_INT = Int32(26)
MSK_DINF_MIO_OBJ_REL_GAP = Int32(27)
MSK_DINF_MIO_OPTIMIZER_TIME = Int32(28)
MSK_DINF_MIO_PROBING_TIME = Int32(29)
MSK_DINF_MIO_ROOT_CUTGEN_TIME = Int32(30)
MSK_DINF_MIO_ROOT_OPTIMIZER_TIME = Int32(31)
MSK_DINF_MIO_ROOT_PRESOLVE_TIME = Int32(32)
MSK_DINF_MIO_TIME = Int32(33)
MSK_DINF_MIO_USER_OBJ_CUT = Int32(34)
MSK_DINF_OPTIMIZER_TIME = Int32(35)
MSK_DINF_PRESOLVE_ELI_TIME = Int32(36)
MSK_DINF_PRESOLVE_LINDEP_TIME = Int32(37)
MSK_DINF_PRESOLVE_TIME = Int32(38)
MSK_DINF_PRIMAL_REPAIR_PENALTY_OBJ = Int32(39)
MSK_DINF_QCQO_REFORMULATE_MAX_PERTURBATION = Int32(40)
MSK_DINF_QCQO_REFORMULATE_TIME = Int32(41)
MSK_DINF_QCQO_REFORMULATE_WORST_CHOLESKY_COLUMN_SCALING = Int32(42)
MSK_DINF_QCQO_REFORMULATE_WORST_CHOLESKY_DIAG_SCALING = Int32(43)
MSK_DINF_RD_TIME = Int32(44)
MSK_DINF_SIM_DUAL_TIME = Int32(45)
MSK_DINF_SIM_FEAS = Int32(46)
MSK_DINF_SIM_NETWORK_DUAL_TIME = Int32(47)
MSK_DINF_SIM_NETWORK_PRIMAL_TIME = Int32(48)
MSK_DINF_SIM_NETWORK_TIME = Int32(49)
MSK_DINF_SIM_OBJ = Int32(50)
MSK_DINF_SIM_PRIMAL_DUAL_TIME = Int32(51)
MSK_DINF_SIM_PRIMAL_TIME = Int32(52)
MSK_DINF_SIM_TIME = Int32(53)
MSK_DINF_SOL_BAS_DUAL_OBJ = Int32(54)
MSK_DINF_SOL_BAS_DVIOLCON = Int32(55)
MSK_DINF_SOL_BAS_DVIOLVAR = Int32(56)
MSK_DINF_SOL_BAS_NRM_BARX = Int32(57)
MSK_DINF_SOL_BAS_NRM_SLC = Int32(58)
MSK_DINF_SOL_BAS_NRM_SLX = Int32(59)
MSK_DINF_SOL_BAS_NRM_SUC = Int32(60)
MSK_DINF_SOL_BAS_NRM_SUX = Int32(61)
MSK_DINF_SOL_BAS_NRM_XC = Int32(62)
MSK_DINF_SOL_BAS_NRM_XX = Int32(63)
MSK_DINF_SOL_BAS_NRM_Y = Int32(64)
MSK_DINF_SOL_BAS_PRIMAL_OBJ = Int32(65)
MSK_DINF_SOL_BAS_PVIOLCON = Int32(66)
MSK_DINF_SOL_BAS_PVIOLVAR = Int32(67)
MSK_DINF_SOL_ITG_NRM_BARX = Int32(68)
MSK_DINF_SOL_ITG_NRM_XC = Int32(69)
MSK_DINF_SOL_ITG_NRM_XX = Int32(70)
MSK_DINF_SOL_ITG_PRIMAL_OBJ = Int32(71)
MSK_DINF_SOL_ITG_PVIOLBARVAR = Int32(72)
MSK_DINF_SOL_ITG_PVIOLCON = Int32(73)
MSK_DINF_SOL_ITG_PVIOLCONES = Int32(74)
MSK_DINF_SOL_ITG_PVIOLITG = Int32(75)
MSK_DINF_SOL_ITG_PVIOLVAR = Int32(76)
MSK_DINF_SOL_ITR_DUAL_OBJ = Int32(77)
MSK_DINF_SOL_ITR_DVIOLBARVAR = Int32(78)
MSK_DINF_SOL_ITR_DVIOLCON = Int32(79)
MSK_DINF_SOL_ITR_DVIOLCONES = Int32(80)
MSK_DINF_SOL_ITR_DVIOLVAR = Int32(81)
MSK_DINF_SOL_ITR_NRM_BARS = Int32(82)
MSK_DINF_SOL_ITR_NRM_BARX = Int32(83)
MSK_DINF_SOL_ITR_NRM_SLC = Int32(84)
MSK_DINF_SOL_ITR_NRM_SLX = Int32(85)
MSK_DINF_SOL_ITR_NRM_SNX = Int32(86)
MSK_DINF_SOL_ITR_NRM_SUC = Int32(87)
MSK_DINF_SOL_ITR_NRM_SUX = Int32(88)
MSK_DINF_SOL_ITR_NRM_XC = Int32(89)
MSK_DINF_SOL_ITR_NRM_XX = Int32(90)
MSK_DINF_SOL_ITR_NRM_Y = Int32(91)
MSK_DINF_SOL_ITR_PRIMAL_OBJ = Int32(92)
MSK_DINF_SOL_ITR_PVIOLBARVAR = Int32(93)
MSK_DINF_SOL_ITR_PVIOLCON = Int32(94)
MSK_DINF_SOL_ITR_PVIOLCONES = Int32(95)
MSK_DINF_SOL_ITR_PVIOLVAR = Int32(96)
MSK_DINF_TO_CONIC_TIME = Int32(97)

  MSK_DINF_BEGIN = Int32(0)
  MSK_DINF_END   = Int32(98)

# enum parametertype
MSK_PAR_DOU_TYPE = Int32(1)
MSK_PAR_INT_TYPE = Int32(2)
MSK_PAR_INVALID_TYPE = Int32(0)
MSK_PAR_STR_TYPE = Int32(3)

  MSK_PAR_BEGIN = Int32(0)
  MSK_PAR_END   = Int32(4)

# enum rescodetype
MSK_RESPONSE_ERR = Int32(3)
MSK_RESPONSE_OK = Int32(0)
MSK_RESPONSE_TRM = Int32(2)
MSK_RESPONSE_UNK = Int32(4)
MSK_RESPONSE_WRN = Int32(1)

  MSK_RESPONSE_BEGIN = Int32(0)
  MSK_RESPONSE_END   = Int32(5)

# enum prosta
MSK_PRO_STA_DUAL_FEAS = Int32(3)
MSK_PRO_STA_DUAL_INFEAS = Int32(5)
MSK_PRO_STA_ILL_POSED = Int32(7)
MSK_PRO_STA_NEAR_DUAL_FEAS = Int32(10)
MSK_PRO_STA_NEAR_PRIM_AND_DUAL_FEAS = Int32(8)
MSK_PRO_STA_NEAR_PRIM_FEAS = Int32(9)
MSK_PRO_STA_PRIM_AND_DUAL_FEAS = Int32(1)
MSK_PRO_STA_PRIM_AND_DUAL_INFEAS = Int32(6)
MSK_PRO_STA_PRIM_FEAS = Int32(2)
MSK_PRO_STA_PRIM_INFEAS = Int32(4)
MSK_PRO_STA_PRIM_INFEAS_OR_UNBOUNDED = Int32(11)
MSK_PRO_STA_UNKNOWN = Int32(0)

  MSK_PRO_STA_BEGIN = Int32(0)
  MSK_PRO_STA_END   = Int32(12)

# enum scalingtype
MSK_SCALING_AGGRESSIVE = Int32(3)
MSK_SCALING_FREE = Int32(0)
MSK_SCALING_MODERATE = Int32(2)
MSK_SCALING_NONE = Int32(1)

  MSK_SCALING_BEGIN = Int32(0)
  MSK_SCALING_END   = Int32(4)

# enum rescode
MSK_RES_ERR_AD_INVALID_CODELIST = Int32(3102)
MSK_RES_ERR_API_ARRAY_TOO_SMALL = Int32(3001)
MSK_RES_ERR_API_CB_CONNECT = Int32(3002)
MSK_RES_ERR_API_FATAL_ERROR = Int32(3005)
MSK_RES_ERR_API_INTERNAL = Int32(3999)
MSK_RES_ERR_ARG_IS_TOO_LARGE = Int32(1227)
MSK_RES_ERR_ARG_IS_TOO_SMALL = Int32(1226)
MSK_RES_ERR_ARGUMENT_DIMENSION = Int32(1201)
MSK_RES_ERR_ARGUMENT_IS_TOO_LARGE = Int32(5005)
MSK_RES_ERR_ARGUMENT_LENNEQ = Int32(1197)
MSK_RES_ERR_ARGUMENT_PERM_ARRAY = Int32(1299)
MSK_RES_ERR_ARGUMENT_TYPE = Int32(1198)
MSK_RES_ERR_BAR_VAR_DIM = Int32(3920)
MSK_RES_ERR_BASIS = Int32(1266)
MSK_RES_ERR_BASIS_FACTOR = Int32(1610)
MSK_RES_ERR_BASIS_SINGULAR = Int32(1615)
MSK_RES_ERR_BLANK_NAME = Int32(1070)
MSK_RES_ERR_CANNOT_CLONE_NL = Int32(2505)
MSK_RES_ERR_CANNOT_HANDLE_NL = Int32(2506)
MSK_RES_ERR_CBF_DUPLICATE_ACOORD = Int32(7116)
MSK_RES_ERR_CBF_DUPLICATE_BCOORD = Int32(7115)
MSK_RES_ERR_CBF_DUPLICATE_CON = Int32(7108)
MSK_RES_ERR_CBF_DUPLICATE_INT = Int32(7110)
MSK_RES_ERR_CBF_DUPLICATE_OBJ = Int32(7107)
MSK_RES_ERR_CBF_DUPLICATE_OBJACOORD = Int32(7114)
MSK_RES_ERR_CBF_DUPLICATE_VAR = Int32(7109)
MSK_RES_ERR_CBF_INVALID_CON_TYPE = Int32(7112)
MSK_RES_ERR_CBF_INVALID_DOMAIN_DIMENSION = Int32(7113)
MSK_RES_ERR_CBF_INVALID_INT_INDEX = Int32(7121)
MSK_RES_ERR_CBF_INVALID_VAR_TYPE = Int32(7111)
MSK_RES_ERR_CBF_NO_VARIABLES = Int32(7102)
MSK_RES_ERR_CBF_NO_VERSION_SPECIFIED = Int32(7105)
MSK_RES_ERR_CBF_OBJ_SENSE = Int32(7101)
MSK_RES_ERR_CBF_PARSE = Int32(7100)
MSK_RES_ERR_CBF_SYNTAX = Int32(7106)
MSK_RES_ERR_CBF_TOO_FEW_CONSTRAINTS = Int32(7118)
MSK_RES_ERR_CBF_TOO_FEW_INTS = Int32(7119)
MSK_RES_ERR_CBF_TOO_FEW_VARIABLES = Int32(7117)
MSK_RES_ERR_CBF_TOO_MANY_CONSTRAINTS = Int32(7103)
MSK_RES_ERR_CBF_TOO_MANY_INTS = Int32(7120)
MSK_RES_ERR_CBF_TOO_MANY_VARIABLES = Int32(7104)
MSK_RES_ERR_CBF_UNSUPPORTED = Int32(7122)
MSK_RES_ERR_CON_Q_NOT_NSD = Int32(1294)
MSK_RES_ERR_CON_Q_NOT_PSD = Int32(1293)
MSK_RES_ERR_CONCURRENT_OPTIMIZER = Int32(3059)
MSK_RES_ERR_CONE_INDEX = Int32(1300)
MSK_RES_ERR_CONE_OVERLAP = Int32(1302)
MSK_RES_ERR_CONE_OVERLAP_APPEND = Int32(1307)
MSK_RES_ERR_CONE_REP_VAR = Int32(1303)
MSK_RES_ERR_CONE_SIZE = Int32(1301)
MSK_RES_ERR_CONE_TYPE = Int32(1305)
MSK_RES_ERR_CONE_TYPE_STR = Int32(1306)
MSK_RES_ERR_DATA_FILE_EXT = Int32(1055)
MSK_RES_ERR_DUP_NAME = Int32(1071)
MSK_RES_ERR_DUPLICATE_AIJ = Int32(1385)
MSK_RES_ERR_DUPLICATE_BARVARIABLE_NAMES = Int32(4502)
MSK_RES_ERR_DUPLICATE_CONE_NAMES = Int32(4503)
MSK_RES_ERR_DUPLICATE_CONSTRAINT_NAMES = Int32(4500)
MSK_RES_ERR_DUPLICATE_VARIABLE_NAMES = Int32(4501)
MSK_RES_ERR_END_OF_FILE = Int32(1059)
MSK_RES_ERR_FACTOR = Int32(1650)
MSK_RES_ERR_FEASREPAIR_CANNOT_RELAX = Int32(1700)
MSK_RES_ERR_FEASREPAIR_INCONSISTENT_BOUND = Int32(1702)
MSK_RES_ERR_FEASREPAIR_SOLVING_RELAXED = Int32(1701)
MSK_RES_ERR_FILE_LICENSE = Int32(1007)
MSK_RES_ERR_FILE_OPEN = Int32(1052)
MSK_RES_ERR_FILE_READ = Int32(1053)
MSK_RES_ERR_FILE_WRITE = Int32(1054)
MSK_RES_ERR_FIRST = Int32(1261)
MSK_RES_ERR_FIRSTI = Int32(1285)
MSK_RES_ERR_FIRSTJ = Int32(1287)
MSK_RES_ERR_FIXED_BOUND_VALUES = Int32(1425)
MSK_RES_ERR_FLEXLM = Int32(1014)
MSK_RES_ERR_GLOBAL_INV_CONIC_PROBLEM = Int32(1503)
MSK_RES_ERR_HUGE_AIJ = Int32(1380)
MSK_RES_ERR_HUGE_C = Int32(1375)
MSK_RES_ERR_IDENTICAL_TASKS = Int32(3101)
MSK_RES_ERR_IN_ARGUMENT = Int32(1200)
MSK_RES_ERR_INDEX = Int32(1235)
MSK_RES_ERR_INDEX_ARR_IS_TOO_LARGE = Int32(1222)
MSK_RES_ERR_INDEX_ARR_IS_TOO_SMALL = Int32(1221)
MSK_RES_ERR_INDEX_IS_TOO_LARGE = Int32(1204)
MSK_RES_ERR_INDEX_IS_TOO_SMALL = Int32(1203)
MSK_RES_ERR_INF_DOU_INDEX = Int32(1219)
MSK_RES_ERR_INF_DOU_NAME = Int32(1230)
MSK_RES_ERR_INF_INT_INDEX = Int32(1220)
MSK_RES_ERR_INF_INT_NAME = Int32(1231)
MSK_RES_ERR_INF_LINT_INDEX = Int32(1225)
MSK_RES_ERR_INF_LINT_NAME = Int32(1234)
MSK_RES_ERR_INF_TYPE = Int32(1232)
MSK_RES_ERR_INFEAS_UNDEFINED = Int32(3910)
MSK_RES_ERR_INFINITE_BOUND = Int32(1400)
MSK_RES_ERR_INT64_TO_INT32_CAST = Int32(3800)
MSK_RES_ERR_INTERNAL = Int32(3000)
MSK_RES_ERR_INTERNAL_TEST_FAILED = Int32(3500)
MSK_RES_ERR_INV_APTRE = Int32(1253)
MSK_RES_ERR_INV_BK = Int32(1255)
MSK_RES_ERR_INV_BKC = Int32(1256)
MSK_RES_ERR_INV_BKX = Int32(1257)
MSK_RES_ERR_INV_CONE_TYPE = Int32(1272)
MSK_RES_ERR_INV_CONE_TYPE_STR = Int32(1271)
MSK_RES_ERR_INV_MARKI = Int32(2501)
MSK_RES_ERR_INV_MARKJ = Int32(2502)
MSK_RES_ERR_INV_NAME_ITEM = Int32(1280)
MSK_RES_ERR_INV_NUMI = Int32(2503)
MSK_RES_ERR_INV_NUMJ = Int32(2504)
MSK_RES_ERR_INV_OPTIMIZER = Int32(1550)
MSK_RES_ERR_INV_PROBLEM = Int32(1500)
MSK_RES_ERR_INV_QCON_SUBI = Int32(1405)
MSK_RES_ERR_INV_QCON_SUBJ = Int32(1406)
MSK_RES_ERR_INV_QCON_SUBK = Int32(1404)
MSK_RES_ERR_INV_QCON_VAL = Int32(1407)
MSK_RES_ERR_INV_QOBJ_SUBI = Int32(1401)
MSK_RES_ERR_INV_QOBJ_SUBJ = Int32(1402)
MSK_RES_ERR_INV_QOBJ_VAL = Int32(1403)
MSK_RES_ERR_INV_SK = Int32(1270)
MSK_RES_ERR_INV_SK_STR = Int32(1269)
MSK_RES_ERR_INV_SKC = Int32(1267)
MSK_RES_ERR_INV_SKN = Int32(1274)
MSK_RES_ERR_INV_SKX = Int32(1268)
MSK_RES_ERR_INV_VAR_TYPE = Int32(1258)
MSK_RES_ERR_INVALID_ACCMODE = Int32(2520)
MSK_RES_ERR_INVALID_AIJ = Int32(1473)
MSK_RES_ERR_INVALID_AMPL_STUB = Int32(3700)
MSK_RES_ERR_INVALID_BARVAR_NAME = Int32(1079)
MSK_RES_ERR_INVALID_COMPRESSION = Int32(1800)
MSK_RES_ERR_INVALID_CON_NAME = Int32(1076)
MSK_RES_ERR_INVALID_CONE_NAME = Int32(1078)
MSK_RES_ERR_INVALID_FILE_FORMAT_FOR_CONES = Int32(4005)
MSK_RES_ERR_INVALID_FILE_FORMAT_FOR_GENERAL_NL = Int32(4010)
MSK_RES_ERR_INVALID_FILE_FORMAT_FOR_SYM_MAT = Int32(4000)
MSK_RES_ERR_INVALID_FILE_NAME = Int32(1056)
MSK_RES_ERR_INVALID_FORMAT_TYPE = Int32(1283)
MSK_RES_ERR_INVALID_IDX = Int32(1246)
MSK_RES_ERR_INVALID_IOMODE = Int32(1801)
MSK_RES_ERR_INVALID_MAX_NUM = Int32(1247)
MSK_RES_ERR_INVALID_NAME_IN_SOL_FILE = Int32(1170)
MSK_RES_ERR_INVALID_NETWORK_PROBLEM = Int32(1504)
MSK_RES_ERR_INVALID_OBJ_NAME = Int32(1075)
MSK_RES_ERR_INVALID_OBJECTIVE_SENSE = Int32(1445)
MSK_RES_ERR_INVALID_PROBLEM_TYPE = Int32(6000)
MSK_RES_ERR_INVALID_SOL_FILE_NAME = Int32(1057)
MSK_RES_ERR_INVALID_STREAM = Int32(1062)
MSK_RES_ERR_INVALID_SURPLUS = Int32(1275)
MSK_RES_ERR_INVALID_SYM_MAT_DIM = Int32(3950)
MSK_RES_ERR_INVALID_TASK = Int32(1064)
MSK_RES_ERR_INVALID_UTF8 = Int32(2900)
MSK_RES_ERR_INVALID_VAR_NAME = Int32(1077)
MSK_RES_ERR_INVALID_WCHAR = Int32(2901)
MSK_RES_ERR_INVALID_WHICHSOL = Int32(1228)
MSK_RES_ERR_JSON_DATA = Int32(1179)
MSK_RES_ERR_JSON_FORMAT = Int32(1178)
MSK_RES_ERR_JSON_MISSING_DATA = Int32(1180)
MSK_RES_ERR_JSON_NUMBER_OVERFLOW = Int32(1177)
MSK_RES_ERR_JSON_STRING = Int32(1176)
MSK_RES_ERR_JSON_SYNTAX = Int32(1175)
MSK_RES_ERR_LAST = Int32(1262)
MSK_RES_ERR_LASTI = Int32(1286)
MSK_RES_ERR_LASTJ = Int32(1288)
MSK_RES_ERR_LAU_ARG_K = Int32(7012)
MSK_RES_ERR_LAU_ARG_M = Int32(7010)
MSK_RES_ERR_LAU_ARG_N = Int32(7011)
MSK_RES_ERR_LAU_ARG_TRANS = Int32(7018)
MSK_RES_ERR_LAU_ARG_TRANSA = Int32(7015)
MSK_RES_ERR_LAU_ARG_TRANSB = Int32(7016)
MSK_RES_ERR_LAU_ARG_UPLO = Int32(7017)
MSK_RES_ERR_LAU_INVALID_LOWER_TRIANGULAR_MATRIX = Int32(7002)
MSK_RES_ERR_LAU_INVALID_SPARSE_SYMMETRIC_MATRIX = Int32(7019)
MSK_RES_ERR_LAU_NOT_POSITIVE_DEFINITE = Int32(7001)
MSK_RES_ERR_LAU_SINGULAR_MATRIX = Int32(7000)
MSK_RES_ERR_LAU_UNKNOWN = Int32(7005)
MSK_RES_ERR_LICENSE = Int32(1000)
MSK_RES_ERR_LICENSE_CANNOT_ALLOCATE = Int32(1020)
MSK_RES_ERR_LICENSE_CANNOT_CONNECT = Int32(1021)
MSK_RES_ERR_LICENSE_EXPIRED = Int32(1001)
MSK_RES_ERR_LICENSE_FEATURE = Int32(1018)
MSK_RES_ERR_LICENSE_INVALID_HOSTID = Int32(1025)
MSK_RES_ERR_LICENSE_MAX = Int32(1016)
MSK_RES_ERR_LICENSE_MOSEKLM_DAEMON = Int32(1017)
MSK_RES_ERR_LICENSE_NO_SERVER_LINE = Int32(1028)
MSK_RES_ERR_LICENSE_NO_SERVER_SUPPORT = Int32(1027)
MSK_RES_ERR_LICENSE_SERVER = Int32(1015)
MSK_RES_ERR_LICENSE_SERVER_VERSION = Int32(1026)
MSK_RES_ERR_LICENSE_VERSION = Int32(1002)
MSK_RES_ERR_LINK_FILE_DLL = Int32(1040)
MSK_RES_ERR_LIVING_TASKS = Int32(1066)
MSK_RES_ERR_LOWER_BOUND_IS_A_NAN = Int32(1390)
MSK_RES_ERR_LP_DUP_SLACK_NAME = Int32(1152)
MSK_RES_ERR_LP_EMPTY = Int32(1151)
MSK_RES_ERR_LP_FILE_FORMAT = Int32(1157)
MSK_RES_ERR_LP_FORMAT = Int32(1160)
MSK_RES_ERR_LP_FREE_CONSTRAINT = Int32(1155)
MSK_RES_ERR_LP_INCOMPATIBLE = Int32(1150)
MSK_RES_ERR_LP_INVALID_CON_NAME = Int32(1171)
MSK_RES_ERR_LP_INVALID_VAR_NAME = Int32(1154)
MSK_RES_ERR_LP_WRITE_CONIC_PROBLEM = Int32(1163)
MSK_RES_ERR_LP_WRITE_GECO_PROBLEM = Int32(1164)
MSK_RES_ERR_LU_MAX_NUM_TRIES = Int32(2800)
MSK_RES_ERR_MAX_LEN_IS_TOO_SMALL = Int32(1289)
MSK_RES_ERR_MAXNUMBARVAR = Int32(1242)
MSK_RES_ERR_MAXNUMCON = Int32(1240)
MSK_RES_ERR_MAXNUMCONE = Int32(1304)
MSK_RES_ERR_MAXNUMQNZ = Int32(1243)
MSK_RES_ERR_MAXNUMVAR = Int32(1241)
MSK_RES_ERR_MIO_INTERNAL = Int32(5010)
MSK_RES_ERR_MIO_INVALID_NODE_OPTIMIZER = Int32(7131)
MSK_RES_ERR_MIO_INVALID_ROOT_OPTIMIZER = Int32(7130)
MSK_RES_ERR_MIO_NO_OPTIMIZER = Int32(1551)
MSK_RES_ERR_MIO_NOT_LOADED = Int32(1553)
MSK_RES_ERR_MISSING_LICENSE_FILE = Int32(1008)
MSK_RES_ERR_MIXED_CONIC_AND_NL = Int32(1501)
MSK_RES_ERR_MPS_CONE_OVERLAP = Int32(1118)
MSK_RES_ERR_MPS_CONE_REPEAT = Int32(1119)
MSK_RES_ERR_MPS_CONE_TYPE = Int32(1117)
MSK_RES_ERR_MPS_DUPLICATE_Q_ELEMENT = Int32(1121)
MSK_RES_ERR_MPS_FILE = Int32(1100)
MSK_RES_ERR_MPS_INV_BOUND_KEY = Int32(1108)
MSK_RES_ERR_MPS_INV_CON_KEY = Int32(1107)
MSK_RES_ERR_MPS_INV_FIELD = Int32(1101)
MSK_RES_ERR_MPS_INV_MARKER = Int32(1102)
MSK_RES_ERR_MPS_INV_SEC_NAME = Int32(1109)
MSK_RES_ERR_MPS_INV_SEC_ORDER = Int32(1115)
MSK_RES_ERR_MPS_INVALID_OBJ_NAME = Int32(1128)
MSK_RES_ERR_MPS_INVALID_OBJSENSE = Int32(1122)
MSK_RES_ERR_MPS_MUL_CON_NAME = Int32(1112)
MSK_RES_ERR_MPS_MUL_CSEC = Int32(1116)
MSK_RES_ERR_MPS_MUL_QOBJ = Int32(1114)
MSK_RES_ERR_MPS_MUL_QSEC = Int32(1113)
MSK_RES_ERR_MPS_NO_OBJECTIVE = Int32(1110)
MSK_RES_ERR_MPS_NON_SYMMETRIC_Q = Int32(1120)
MSK_RES_ERR_MPS_NULL_CON_NAME = Int32(1103)
MSK_RES_ERR_MPS_NULL_VAR_NAME = Int32(1104)
MSK_RES_ERR_MPS_SPLITTED_VAR = Int32(1111)
MSK_RES_ERR_MPS_TAB_IN_FIELD2 = Int32(1125)
MSK_RES_ERR_MPS_TAB_IN_FIELD3 = Int32(1126)
MSK_RES_ERR_MPS_TAB_IN_FIELD5 = Int32(1127)
MSK_RES_ERR_MPS_UNDEF_CON_NAME = Int32(1105)
MSK_RES_ERR_MPS_UNDEF_VAR_NAME = Int32(1106)
MSK_RES_ERR_MUL_A_ELEMENT = Int32(1254)
MSK_RES_ERR_NAME_IS_NULL = Int32(1760)
MSK_RES_ERR_NAME_MAX_LEN = Int32(1750)
MSK_RES_ERR_NAN_IN_BLC = Int32(1461)
MSK_RES_ERR_NAN_IN_BLX = Int32(1471)
MSK_RES_ERR_NAN_IN_BUC = Int32(1462)
MSK_RES_ERR_NAN_IN_BUX = Int32(1472)
MSK_RES_ERR_NAN_IN_C = Int32(1470)
MSK_RES_ERR_NAN_IN_DOUBLE_DATA = Int32(1450)
MSK_RES_ERR_NEGATIVE_APPEND = Int32(1264)
MSK_RES_ERR_NEGATIVE_SURPLUS = Int32(1263)
MSK_RES_ERR_NEWER_DLL = Int32(1036)
MSK_RES_ERR_NO_BARS_FOR_SOLUTION = Int32(3916)
MSK_RES_ERR_NO_BARX_FOR_SOLUTION = Int32(3915)
MSK_RES_ERR_NO_BASIS_SOL = Int32(1600)
MSK_RES_ERR_NO_DUAL_FOR_ITG_SOL = Int32(2950)
MSK_RES_ERR_NO_DUAL_INFEAS_CER = Int32(2001)
MSK_RES_ERR_NO_INIT_ENV = Int32(1063)
MSK_RES_ERR_NO_OPTIMIZER_VAR_TYPE = Int32(1552)
MSK_RES_ERR_NO_PRIMAL_INFEAS_CER = Int32(2000)
MSK_RES_ERR_NO_SNX_FOR_BAS_SOL = Int32(2953)
MSK_RES_ERR_NO_SOLUTION_IN_CALLBACK = Int32(2500)
MSK_RES_ERR_NON_UNIQUE_ARRAY = Int32(5000)
MSK_RES_ERR_NONCONVEX = Int32(1291)
MSK_RES_ERR_NONLINEAR_EQUALITY = Int32(1290)
MSK_RES_ERR_NONLINEAR_FUNCTIONS_NOT_ALLOWED = Int32(1428)
MSK_RES_ERR_NONLINEAR_RANGED = Int32(1292)
MSK_RES_ERR_NR_ARGUMENTS = Int32(1199)
MSK_RES_ERR_NULL_ENV = Int32(1060)
MSK_RES_ERR_NULL_POINTER = Int32(1065)
MSK_RES_ERR_NULL_TASK = Int32(1061)
MSK_RES_ERR_NUMCONLIM = Int32(1250)
MSK_RES_ERR_NUMVARLIM = Int32(1251)
MSK_RES_ERR_OBJ_Q_NOT_NSD = Int32(1296)
MSK_RES_ERR_OBJ_Q_NOT_PSD = Int32(1295)
MSK_RES_ERR_OBJECTIVE_RANGE = Int32(1260)
MSK_RES_ERR_OLDER_DLL = Int32(1035)
MSK_RES_ERR_OPEN_DL = Int32(1030)
MSK_RES_ERR_OPF_FORMAT = Int32(1168)
MSK_RES_ERR_OPF_NEW_VARIABLE = Int32(1169)
MSK_RES_ERR_OPF_PREMATURE_EOF = Int32(1172)
MSK_RES_ERR_OPTIMIZER_LICENSE = Int32(1013)
MSK_RES_ERR_OVERFLOW = Int32(1590)
MSK_RES_ERR_PARAM_INDEX = Int32(1210)
MSK_RES_ERR_PARAM_IS_TOO_LARGE = Int32(1215)
MSK_RES_ERR_PARAM_IS_TOO_SMALL = Int32(1216)
MSK_RES_ERR_PARAM_NAME = Int32(1205)
MSK_RES_ERR_PARAM_NAME_DOU = Int32(1206)
MSK_RES_ERR_PARAM_NAME_INT = Int32(1207)
MSK_RES_ERR_PARAM_NAME_STR = Int32(1208)
MSK_RES_ERR_PARAM_TYPE = Int32(1218)
MSK_RES_ERR_PARAM_VALUE_STR = Int32(1217)
MSK_RES_ERR_PLATFORM_NOT_LICENSED = Int32(1019)
MSK_RES_ERR_POSTSOLVE = Int32(1580)
MSK_RES_ERR_PRO_ITEM = Int32(1281)
MSK_RES_ERR_PROB_LICENSE = Int32(1006)
MSK_RES_ERR_QCON_SUBI_TOO_LARGE = Int32(1409)
MSK_RES_ERR_QCON_SUBI_TOO_SMALL = Int32(1408)
MSK_RES_ERR_QCON_UPPER_TRIANGLE = Int32(1417)
MSK_RES_ERR_QOBJ_UPPER_TRIANGLE = Int32(1415)
MSK_RES_ERR_READ_FORMAT = Int32(1090)
MSK_RES_ERR_READ_LP_MISSING_END_TAG = Int32(1159)
MSK_RES_ERR_READ_LP_NONEXISTING_NAME = Int32(1162)
MSK_RES_ERR_REMOVE_CONE_VARIABLE = Int32(1310)
MSK_RES_ERR_REPAIR_INVALID_PROBLEM = Int32(1710)
MSK_RES_ERR_REPAIR_OPTIMIZATION_FAILED = Int32(1711)
MSK_RES_ERR_SEN_BOUND_INVALID_LO = Int32(3054)
MSK_RES_ERR_SEN_BOUND_INVALID_UP = Int32(3053)
MSK_RES_ERR_SEN_FORMAT = Int32(3050)
MSK_RES_ERR_SEN_INDEX_INVALID = Int32(3055)
MSK_RES_ERR_SEN_INDEX_RANGE = Int32(3052)
MSK_RES_ERR_SEN_INVALID_REGEXP = Int32(3056)
MSK_RES_ERR_SEN_NUMERICAL = Int32(3058)
MSK_RES_ERR_SEN_SOLUTION_STATUS = Int32(3057)
MSK_RES_ERR_SEN_UNDEF_NAME = Int32(3051)
MSK_RES_ERR_SEN_UNHANDLED_PROBLEM_TYPE = Int32(3080)
MSK_RES_ERR_SERVER_CONNECT = Int32(8000)
MSK_RES_ERR_SERVER_PROTOCOL = Int32(8001)
MSK_RES_ERR_SERVER_STATUS = Int32(8002)
MSK_RES_ERR_SERVER_TOKEN = Int32(8003)
MSK_RES_ERR_SIZE_LICENSE = Int32(1005)
MSK_RES_ERR_SIZE_LICENSE_CON = Int32(1010)
MSK_RES_ERR_SIZE_LICENSE_INTVAR = Int32(1012)
MSK_RES_ERR_SIZE_LICENSE_NUMCORES = Int32(3900)
MSK_RES_ERR_SIZE_LICENSE_VAR = Int32(1011)
MSK_RES_ERR_SOL_FILE_INVALID_NUMBER = Int32(1350)
MSK_RES_ERR_SOLITEM = Int32(1237)
MSK_RES_ERR_SOLVER_PROBTYPE = Int32(1259)
MSK_RES_ERR_SPACE = Int32(1051)
MSK_RES_ERR_SPACE_LEAKING = Int32(1080)
MSK_RES_ERR_SPACE_NO_INFO = Int32(1081)
MSK_RES_ERR_SYM_MAT_DUPLICATE = Int32(3944)
MSK_RES_ERR_SYM_MAT_INVALID_COL_INDEX = Int32(3941)
MSK_RES_ERR_SYM_MAT_INVALID_ROW_INDEX = Int32(3940)
MSK_RES_ERR_SYM_MAT_INVALID_VALUE = Int32(3943)
MSK_RES_ERR_SYM_MAT_NOT_LOWER_TRINGULAR = Int32(3942)
MSK_RES_ERR_TASK_INCOMPATIBLE = Int32(2560)
MSK_RES_ERR_TASK_INVALID = Int32(2561)
MSK_RES_ERR_THREAD_COND_INIT = Int32(1049)
MSK_RES_ERR_THREAD_CREATE = Int32(1048)
MSK_RES_ERR_THREAD_MUTEX_INIT = Int32(1045)
MSK_RES_ERR_THREAD_MUTEX_LOCK = Int32(1046)
MSK_RES_ERR_THREAD_MUTEX_UNLOCK = Int32(1047)
MSK_RES_ERR_TOCONIC_CONSTR_NOT_CONIC = Int32(7153)
MSK_RES_ERR_TOCONIC_CONSTR_Q_NOT_PSD = Int32(7150)
MSK_RES_ERR_TOCONIC_CONSTRAINT_FX = Int32(7151)
MSK_RES_ERR_TOCONIC_CONSTRAINT_RA = Int32(7152)
MSK_RES_ERR_TOCONIC_OBJECTIVE_NOT_PSD = Int32(7155)
MSK_RES_ERR_TOO_MANY_CONCURRENT_TASKS = Int32(3090)
MSK_RES_ERR_TOO_SMALL_MAX_NUM_NZ = Int32(1245)
MSK_RES_ERR_TOO_SMALL_MAXNUMANZ = Int32(1252)
MSK_RES_ERR_UNB_STEP_SIZE = Int32(3100)
MSK_RES_ERR_UNDEF_SOLUTION = Int32(1265)
MSK_RES_ERR_UNDEFINED_OBJECTIVE_SENSE = Int32(1446)
MSK_RES_ERR_UNHANDLED_SOLUTION_STATUS = Int32(6010)
MSK_RES_ERR_UNKNOWN = Int32(1050)
MSK_RES_ERR_UPPER_BOUND_IS_A_NAN = Int32(1391)
MSK_RES_ERR_UPPER_TRIANGLE = Int32(6020)
MSK_RES_ERR_USER_FUNC_RET = Int32(1430)
MSK_RES_ERR_USER_FUNC_RET_DATA = Int32(1431)
MSK_RES_ERR_USER_NLO_EVAL = Int32(1433)
MSK_RES_ERR_USER_NLO_EVAL_HESSUBI = Int32(1440)
MSK_RES_ERR_USER_NLO_EVAL_HESSUBJ = Int32(1441)
MSK_RES_ERR_USER_NLO_FUNC = Int32(1432)
MSK_RES_ERR_WHICHITEM_NOT_ALLOWED = Int32(1238)
MSK_RES_ERR_WHICHSOL = Int32(1236)
MSK_RES_ERR_WRITE_LP_FORMAT = Int32(1158)
MSK_RES_ERR_WRITE_LP_NON_UNIQUE_NAME = Int32(1161)
MSK_RES_ERR_WRITE_MPS_INVALID_NAME = Int32(1153)
MSK_RES_ERR_WRITE_OPF_INVALID_VAR_NAME = Int32(1156)
MSK_RES_ERR_WRITING_FILE = Int32(1166)
MSK_RES_ERR_XML_INVALID_PROBLEM_TYPE = Int32(3600)
MSK_RES_ERR_Y_IS_UNDEFINED = Int32(1449)
MSK_RES_OK = Int32(0)
MSK_RES_TRM_INTERNAL = Int32(10030)
MSK_RES_TRM_INTERNAL_STOP = Int32(10031)
MSK_RES_TRM_MAX_ITERATIONS = Int32(10000)
MSK_RES_TRM_MAX_NUM_SETBACKS = Int32(10020)
MSK_RES_TRM_MAX_TIME = Int32(10001)
MSK_RES_TRM_MIO_NEAR_ABS_GAP = Int32(10004)
MSK_RES_TRM_MIO_NEAR_REL_GAP = Int32(10003)
MSK_RES_TRM_MIO_NUM_BRANCHES = Int32(10009)
MSK_RES_TRM_MIO_NUM_RELAXS = Int32(10008)
MSK_RES_TRM_NUM_MAX_NUM_INT_SOLUTIONS = Int32(10015)
MSK_RES_TRM_NUMERICAL_PROBLEM = Int32(10025)
MSK_RES_TRM_OBJECTIVE_RANGE = Int32(10002)
MSK_RES_TRM_STALL = Int32(10006)
MSK_RES_TRM_USER_CALLBACK = Int32(10007)
MSK_RES_WRN_ANA_ALMOST_INT_BOUNDS = Int32(904)
MSK_RES_WRN_ANA_C_ZERO = Int32(901)
MSK_RES_WRN_ANA_CLOSE_BOUNDS = Int32(903)
MSK_RES_WRN_ANA_EMPTY_COLS = Int32(902)
MSK_RES_WRN_ANA_LARGE_BOUNDS = Int32(900)
MSK_RES_WRN_CONSTRUCT_INVALID_SOL_ITG = Int32(807)
MSK_RES_WRN_CONSTRUCT_NO_SOL_ITG = Int32(810)
MSK_RES_WRN_CONSTRUCT_SOLUTION_INFEAS = Int32(805)
MSK_RES_WRN_DROPPED_NZ_QOBJ = Int32(201)
MSK_RES_WRN_DUPLICATE_BARVARIABLE_NAMES = Int32(852)
MSK_RES_WRN_DUPLICATE_CONE_NAMES = Int32(853)
MSK_RES_WRN_DUPLICATE_CONSTRAINT_NAMES = Int32(850)
MSK_RES_WRN_DUPLICATE_VARIABLE_NAMES = Int32(851)
MSK_RES_WRN_ELIMINATOR_SPACE = Int32(801)
MSK_RES_WRN_EMPTY_NAME = Int32(502)
MSK_RES_WRN_IGNORE_INTEGER = Int32(250)
MSK_RES_WRN_INCOMPLETE_LINEAR_DEPENDENCY_CHECK = Int32(800)
MSK_RES_WRN_LARGE_AIJ = Int32(62)
MSK_RES_WRN_LARGE_BOUND = Int32(51)
MSK_RES_WRN_LARGE_CJ = Int32(57)
MSK_RES_WRN_LARGE_CON_FX = Int32(54)
MSK_RES_WRN_LARGE_LO_BOUND = Int32(52)
MSK_RES_WRN_LARGE_UP_BOUND = Int32(53)
MSK_RES_WRN_LICENSE_EXPIRE = Int32(500)
MSK_RES_WRN_LICENSE_FEATURE_EXPIRE = Int32(505)
MSK_RES_WRN_LICENSE_SERVER = Int32(501)
MSK_RES_WRN_LP_DROP_VARIABLE = Int32(85)
MSK_RES_WRN_LP_OLD_QUAD_FORMAT = Int32(80)
MSK_RES_WRN_MIO_INFEASIBLE_FINAL = Int32(270)
MSK_RES_WRN_MPS_SPLIT_BOU_VECTOR = Int32(72)
MSK_RES_WRN_MPS_SPLIT_RAN_VECTOR = Int32(71)
MSK_RES_WRN_MPS_SPLIT_RHS_VECTOR = Int32(70)
MSK_RES_WRN_NAME_MAX_LEN = Int32(65)
MSK_RES_WRN_NO_DUALIZER = Int32(950)
MSK_RES_WRN_NO_GLOBAL_OPTIMIZER = Int32(251)
MSK_RES_WRN_NO_NONLINEAR_FUNCTION_WRITE = Int32(450)
MSK_RES_WRN_NZ_IN_UPR_TRI = Int32(200)
MSK_RES_WRN_OPEN_PARAM_FILE = Int32(50)
MSK_RES_WRN_PARAM_IGNORED_CMIO = Int32(516)
MSK_RES_WRN_PARAM_NAME_DOU = Int32(510)
MSK_RES_WRN_PARAM_NAME_INT = Int32(511)
MSK_RES_WRN_PARAM_NAME_STR = Int32(512)
MSK_RES_WRN_PARAM_STR_VALUE = Int32(515)
MSK_RES_WRN_PRESOLVE_OUTOFSPACE = Int32(802)
MSK_RES_WRN_QUAD_CONES_WITH_ROOT_FIXED_AT_ZERO = Int32(930)
MSK_RES_WRN_RQUAD_CONES_WITH_ROOT_FIXED_AT_ZERO = Int32(931)
MSK_RES_WRN_SOL_FILE_IGNORED_CON = Int32(351)
MSK_RES_WRN_SOL_FILE_IGNORED_VAR = Int32(352)
MSK_RES_WRN_SOL_FILTER = Int32(300)
MSK_RES_WRN_SPAR_MAX_LEN = Int32(66)
MSK_RES_WRN_TOO_FEW_BASIS_VARS = Int32(400)
MSK_RES_WRN_TOO_MANY_BASIS_VARS = Int32(405)
MSK_RES_WRN_TOO_MANY_THREADS_CONCURRENT = Int32(750)
MSK_RES_WRN_UNDEF_SOL_FILE_NAME = Int32(350)
MSK_RES_WRN_USING_GENERIC_NAMES = Int32(503)
MSK_RES_WRN_WRITE_CHANGED_NAMES = Int32(803)
MSK_RES_WRN_WRITE_DISCARDED_CFIX = Int32(804)
MSK_RES_WRN_ZERO_AIJ = Int32(63)
MSK_RES_WRN_ZEROS_IN_SPARSE_COL = Int32(710)
MSK_RES_WRN_ZEROS_IN_SPARSE_ROW = Int32(705)

# enum mionodeseltype
MSK_MIO_NODE_SELECTION_BEST = Int32(2)
MSK_MIO_NODE_SELECTION_FIRST = Int32(1)
MSK_MIO_NODE_SELECTION_FREE = Int32(0)
MSK_MIO_NODE_SELECTION_HYBRID = Int32(4)
MSK_MIO_NODE_SELECTION_PSEUDO = Int32(5)
MSK_MIO_NODE_SELECTION_WORST = Int32(3)

  MSK_MIO_NODE_SELECTION_BEGIN = Int32(0)
  MSK_MIO_NODE_SELECTION_END   = Int32(6)

# enum transpose
MSK_TRANSPOSE_NO = Int32(0)
MSK_TRANSPOSE_YES = Int32(1)

  MSK_TRANSPOSE_BEGIN = Int32(0)
  MSK_TRANSPOSE_END   = Int32(2)

# enum onoffkey
MSK_OFF = Int32(0)
MSK_ON = Int32(1)

# enum simdegen
MSK_SIM_DEGEN_AGGRESSIVE = Int32(2)
MSK_SIM_DEGEN_FREE = Int32(1)
MSK_SIM_DEGEN_MINIMUM = Int32(4)
MSK_SIM_DEGEN_MODERATE = Int32(3)
MSK_SIM_DEGEN_NONE = Int32(0)

  MSK_SIM_DEGEN_BEGIN = Int32(0)
  MSK_SIM_DEGEN_END   = Int32(5)

# enum dataformat
MSK_DATA_FORMAT_CB = Int32(7)
MSK_DATA_FORMAT_EXTENSION = Int32(0)
MSK_DATA_FORMAT_FREE_MPS = Int32(5)
MSK_DATA_FORMAT_JSON_TASK = Int32(8)
MSK_DATA_FORMAT_LP = Int32(2)
MSK_DATA_FORMAT_MPS = Int32(1)
MSK_DATA_FORMAT_OP = Int32(3)
MSK_DATA_FORMAT_TASK = Int32(6)
MSK_DATA_FORMAT_XML = Int32(4)

  MSK_DATA_FORMAT_BEGIN = Int32(0)
  MSK_DATA_FORMAT_END   = Int32(9)

# enum orderingtype
MSK_ORDER_METHOD_APPMINLOC = Int32(1)
MSK_ORDER_METHOD_EXPERIMENTAL = Int32(2)
MSK_ORDER_METHOD_FORCE_GRAPHPAR = Int32(4)
MSK_ORDER_METHOD_FREE = Int32(0)
MSK_ORDER_METHOD_NONE = Int32(5)
MSK_ORDER_METHOD_TRY_GRAPHPAR = Int32(3)

  MSK_ORDER_METHOD_BEGIN = Int32(0)
  MSK_ORDER_METHOD_END   = Int32(6)

# enum problemtype
MSK_PROBTYPE_CONIC = Int32(4)
MSK_PROBTYPE_GECO = Int32(3)
MSK_PROBTYPE_LO = Int32(0)
MSK_PROBTYPE_MIXED = Int32(5)
MSK_PROBTYPE_QCQO = Int32(2)
MSK_PROBTYPE_QO = Int32(1)

  MSK_PROBTYPE_BEGIN = Int32(0)
  MSK_PROBTYPE_END   = Int32(6)

# enum inftype
MSK_INF_DOU_TYPE = Int32(0)
MSK_INF_INT_TYPE = Int32(1)
MSK_INF_LINT_TYPE = Int32(2)

  MSK_INF_BEGIN = Int32(0)
  MSK_INF_END   = Int32(3)

# enum dparam
MSK_DPAR_ANA_SOL_INFEAS_TOL = Int32(0)
MSK_DPAR_BASIS_REL_TOL_S = Int32(1)
MSK_DPAR_BASIS_TOL_S = Int32(2)
MSK_DPAR_BASIS_TOL_X = Int32(3)
MSK_DPAR_CHECK_CONVEXITY_REL_TOL = Int32(4)
MSK_DPAR_DATA_TOL_AIJ = Int32(5)
MSK_DPAR_DATA_TOL_AIJ_HUGE = Int32(6)
MSK_DPAR_DATA_TOL_AIJ_LARGE = Int32(7)
MSK_DPAR_DATA_TOL_BOUND_INF = Int32(8)
MSK_DPAR_DATA_TOL_BOUND_WRN = Int32(9)
MSK_DPAR_DATA_TOL_C_HUGE = Int32(10)
MSK_DPAR_DATA_TOL_CJ_LARGE = Int32(11)
MSK_DPAR_DATA_TOL_QIJ = Int32(12)
MSK_DPAR_DATA_TOL_X = Int32(13)
MSK_DPAR_FEASREPAIR_TOL = Int32(14)
MSK_DPAR_INTPNT_CO_TOL_DFEAS = Int32(15)
MSK_DPAR_INTPNT_CO_TOL_INFEAS = Int32(16)
MSK_DPAR_INTPNT_CO_TOL_MU_RED = Int32(17)
MSK_DPAR_INTPNT_CO_TOL_NEAR_REL = Int32(18)
MSK_DPAR_INTPNT_CO_TOL_PFEAS = Int32(19)
MSK_DPAR_INTPNT_CO_TOL_REL_GAP = Int32(20)
MSK_DPAR_INTPNT_NL_MERIT_BAL = Int32(21)
MSK_DPAR_INTPNT_NL_TOL_DFEAS = Int32(22)
MSK_DPAR_INTPNT_NL_TOL_MU_RED = Int32(23)
MSK_DPAR_INTPNT_NL_TOL_NEAR_REL = Int32(24)
MSK_DPAR_INTPNT_NL_TOL_PFEAS = Int32(25)
MSK_DPAR_INTPNT_NL_TOL_REL_GAP = Int32(26)
MSK_DPAR_INTPNT_NL_TOL_REL_STEP = Int32(27)
MSK_DPAR_INTPNT_QO_TOL_DFEAS = Int32(28)
MSK_DPAR_INTPNT_QO_TOL_INFEAS = Int32(29)
MSK_DPAR_INTPNT_QO_TOL_MU_RED = Int32(30)
MSK_DPAR_INTPNT_QO_TOL_NEAR_REL = Int32(31)
MSK_DPAR_INTPNT_QO_TOL_PFEAS = Int32(32)
MSK_DPAR_INTPNT_QO_TOL_REL_GAP = Int32(33)
MSK_DPAR_INTPNT_TOL_DFEAS = Int32(34)
MSK_DPAR_INTPNT_TOL_DSAFE = Int32(35)
MSK_DPAR_INTPNT_TOL_INFEAS = Int32(36)
MSK_DPAR_INTPNT_TOL_MU_RED = Int32(37)
MSK_DPAR_INTPNT_TOL_PATH = Int32(38)
MSK_DPAR_INTPNT_TOL_PFEAS = Int32(39)
MSK_DPAR_INTPNT_TOL_PSAFE = Int32(40)
MSK_DPAR_INTPNT_TOL_REL_GAP = Int32(41)
MSK_DPAR_INTPNT_TOL_REL_STEP = Int32(42)
MSK_DPAR_INTPNT_TOL_STEP_SIZE = Int32(43)
MSK_DPAR_LOWER_OBJ_CUT = Int32(44)
MSK_DPAR_LOWER_OBJ_CUT_FINITE_TRH = Int32(45)
MSK_DPAR_MIO_DISABLE_TERM_TIME = Int32(46)
MSK_DPAR_MIO_MAX_TIME = Int32(47)
MSK_DPAR_MIO_NEAR_TOL_ABS_GAP = Int32(48)
MSK_DPAR_MIO_NEAR_TOL_REL_GAP = Int32(49)
MSK_DPAR_MIO_REL_GAP_CONST = Int32(50)
MSK_DPAR_MIO_TOL_ABS_GAP = Int32(51)
MSK_DPAR_MIO_TOL_ABS_RELAX_INT = Int32(52)
MSK_DPAR_MIO_TOL_FEAS = Int32(53)
MSK_DPAR_MIO_TOL_REL_DUAL_BOUND_IMPROVEMENT = Int32(54)
MSK_DPAR_MIO_TOL_REL_GAP = Int32(55)
MSK_DPAR_OPTIMIZER_MAX_TIME = Int32(56)
MSK_DPAR_PRESOLVE_TOL_ABS_LINDEP = Int32(57)
MSK_DPAR_PRESOLVE_TOL_AIJ = Int32(58)
MSK_DPAR_PRESOLVE_TOL_REL_LINDEP = Int32(59)
MSK_DPAR_PRESOLVE_TOL_S = Int32(60)
MSK_DPAR_PRESOLVE_TOL_X = Int32(61)
MSK_DPAR_QCQO_REFORMULATE_REL_DROP_TOL = Int32(62)
MSK_DPAR_SEMIDEFINITE_TOL_APPROX = Int32(63)
MSK_DPAR_SIM_LU_TOL_REL_PIV = Int32(64)
MSK_DPAR_SIMPLEX_ABS_TOL_PIV = Int32(65)
MSK_DPAR_UPPER_OBJ_CUT = Int32(66)
MSK_DPAR_UPPER_OBJ_CUT_FINITE_TRH = Int32(67)

  MSK_DPAR_BEGIN = Int32(0)
  MSK_DPAR_END   = Int32(68)

# enum simdupvec
MSK_SIM_EXPLOIT_DUPVEC_FREE = Int32(2)
MSK_SIM_EXPLOIT_DUPVEC_OFF = Int32(0)
MSK_SIM_EXPLOIT_DUPVEC_ON = Int32(1)

  MSK_SIM_EXPLOIT_DUPVEC_BEGIN = Int32(0)
  MSK_SIM_EXPLOIT_DUPVEC_END   = Int32(3)

# enum compresstype
MSK_COMPRESS_FREE = Int32(1)
MSK_COMPRESS_GZIP = Int32(2)
MSK_COMPRESS_NONE = Int32(0)

  MSK_COMPRESS_BEGIN = Int32(0)
  MSK_COMPRESS_END   = Int32(3)

# enum nametype
MSK_NAME_TYPE_GEN = Int32(0)
MSK_NAME_TYPE_LP = Int32(2)
MSK_NAME_TYPE_MPS = Int32(1)

  MSK_NAME_TYPE_BEGIN = Int32(0)
  MSK_NAME_TYPE_END   = Int32(3)

# enum mpsformat
MSK_MPS_FORMAT_CPLEX = Int32(3)
MSK_MPS_FORMAT_FREE = Int32(2)
MSK_MPS_FORMAT_RELAXED = Int32(1)
MSK_MPS_FORMAT_STRICT = Int32(0)

  MSK_MPS_FORMAT_BEGIN = Int32(0)
  MSK_MPS_FORMAT_END   = Int32(4)

# enum variabletype
MSK_VAR_TYPE_CONT = Int32(0)
MSK_VAR_TYPE_INT = Int32(1)

  MSK_VAR_BEGIN = Int32(0)
  MSK_VAR_END   = Int32(2)

# enum checkconvexitytype
MSK_CHECK_CONVEXITY_FULL = Int32(2)
MSK_CHECK_CONVEXITY_NONE = Int32(0)
MSK_CHECK_CONVEXITY_SIMPLE = Int32(1)

  MSK_CHECK_CONVEXITY_BEGIN = Int32(0)
  MSK_CHECK_CONVEXITY_END   = Int32(3)

# enum language
MSK_LANG_DAN = Int32(1)
MSK_LANG_ENG = Int32(0)

  MSK_LANG_BEGIN = Int32(0)
  MSK_LANG_END   = Int32(2)

# enum startpointtype
MSK_STARTING_POINT_CONSTANT = Int32(2)
MSK_STARTING_POINT_FREE = Int32(0)
MSK_STARTING_POINT_GUESS = Int32(1)
MSK_STARTING_POINT_SATISFY_BOUNDS = Int32(3)

  MSK_STARTING_POINT_BEGIN = Int32(0)
  MSK_STARTING_POINT_END   = Int32(4)

# enum soltype
MSK_SOL_BAS = Int32(1)
MSK_SOL_ITG = Int32(2)
MSK_SOL_ITR = Int32(0)

  MSK_SOL_BEGIN = Int32(0)
  MSK_SOL_END   = Int32(3)

# enum scalingmethod
MSK_SCALING_METHOD_FREE = Int32(1)
MSK_SCALING_METHOD_POW2 = Int32(0)

  MSK_SCALING_METHOD_BEGIN = Int32(0)
  MSK_SCALING_METHOD_END   = Int32(2)

# enum value
MSK_LICENSE_BUFFER_LENGTH = Int32(20)
MSK_MAX_STR_LEN = Int32(1024)

# enum stakey
MSK_SK_BAS = Int32(1)
MSK_SK_FIX = Int32(5)
MSK_SK_INF = Int32(6)
MSK_SK_LOW = Int32(3)
MSK_SK_SUPBAS = Int32(2)
MSK_SK_UNK = Int32(0)
MSK_SK_UPR = Int32(4)

  MSK_SK_BEGIN = Int32(0)
  MSK_SK_END   = Int32(7)

# enum simreform
MSK_SIM_REFORMULATION_AGGRESSIVE = Int32(3)
MSK_SIM_REFORMULATION_FREE = Int32(2)
MSK_SIM_REFORMULATION_OFF = Int32(0)
MSK_SIM_REFORMULATION_ON = Int32(1)

  MSK_SIM_REFORMULATION_BEGIN = Int32(0)
  MSK_SIM_REFORMULATION_END   = Int32(4)

# enum iinfitem
MSK_IINF_ANA_PRO_NUM_CON = Int32(0)
MSK_IINF_ANA_PRO_NUM_CON_EQ = Int32(1)
MSK_IINF_ANA_PRO_NUM_CON_FR = Int32(2)
MSK_IINF_ANA_PRO_NUM_CON_LO = Int32(3)
MSK_IINF_ANA_PRO_NUM_CON_RA = Int32(4)
MSK_IINF_ANA_PRO_NUM_CON_UP = Int32(5)
MSK_IINF_ANA_PRO_NUM_VAR = Int32(6)
MSK_IINF_ANA_PRO_NUM_VAR_BIN = Int32(7)
MSK_IINF_ANA_PRO_NUM_VAR_CONT = Int32(8)
MSK_IINF_ANA_PRO_NUM_VAR_EQ = Int32(9)
MSK_IINF_ANA_PRO_NUM_VAR_FR = Int32(10)
MSK_IINF_ANA_PRO_NUM_VAR_INT = Int32(11)
MSK_IINF_ANA_PRO_NUM_VAR_LO = Int32(12)
MSK_IINF_ANA_PRO_NUM_VAR_RA = Int32(13)
MSK_IINF_ANA_PRO_NUM_VAR_UP = Int32(14)
MSK_IINF_CONCURRENT_WINNING_OPTIMIZER = Int32(15)
MSK_IINF_INTPNT_FACTOR_DIM_DENSE = Int32(16)
MSK_IINF_INTPNT_ITER = Int32(17)
MSK_IINF_INTPNT_NUM_THREADS = Int32(18)
MSK_IINF_INTPNT_SOLVE_DUAL = Int32(19)
MSK_IINF_MIO_ABSGAP_SATISFIED = Int32(20)
MSK_IINF_MIO_CLIQUE_TABLE_SIZE = Int32(21)
MSK_IINF_MIO_CONSTRUCT_NUM_ROUNDINGS = Int32(22)
MSK_IINF_MIO_CONSTRUCT_SOLUTION = Int32(23)
MSK_IINF_MIO_INITIAL_SOLUTION = Int32(24)
MSK_IINF_MIO_NEAR_ABSGAP_SATISFIED = Int32(25)
MSK_IINF_MIO_NEAR_RELGAP_SATISFIED = Int32(26)
MSK_IINF_MIO_NODE_DEPTH = Int32(27)
MSK_IINF_MIO_NUM_ACTIVE_NODES = Int32(28)
MSK_IINF_MIO_NUM_BRANCH = Int32(29)
MSK_IINF_MIO_NUM_CLIQUE_CUTS = Int32(30)
MSK_IINF_MIO_NUM_CMIR_CUTS = Int32(31)
MSK_IINF_MIO_NUM_GOMORY_CUTS = Int32(32)
MSK_IINF_MIO_NUM_IMPLIED_BOUND_CUTS = Int32(33)
MSK_IINF_MIO_NUM_INT_SOLUTIONS = Int32(34)
MSK_IINF_MIO_NUM_KNAPSACK_COVER_CUTS = Int32(35)
MSK_IINF_MIO_NUM_RELAX = Int32(36)
MSK_IINF_MIO_NUM_REPEATED_PRESOLVE = Int32(37)
MSK_IINF_MIO_NUMCON = Int32(38)
MSK_IINF_MIO_NUMINT = Int32(39)
MSK_IINF_MIO_NUMVAR = Int32(40)
MSK_IINF_MIO_OBJ_BOUND_DEFINED = Int32(41)
MSK_IINF_MIO_PRESOLVED_NUMBIN = Int32(42)
MSK_IINF_MIO_PRESOLVED_NUMCON = Int32(43)
MSK_IINF_MIO_PRESOLVED_NUMCONT = Int32(44)
MSK_IINF_MIO_PRESOLVED_NUMINT = Int32(45)
MSK_IINF_MIO_PRESOLVED_NUMVAR = Int32(46)
MSK_IINF_MIO_RELGAP_SATISFIED = Int32(47)
MSK_IINF_MIO_TOTAL_NUM_CUTS = Int32(48)
MSK_IINF_MIO_USER_OBJ_CUT = Int32(49)
MSK_IINF_OPT_NUMCON = Int32(50)
MSK_IINF_OPT_NUMVAR = Int32(51)
MSK_IINF_OPTIMIZE_RESPONSE = Int32(52)
MSK_IINF_RD_NUMBARVAR = Int32(53)
MSK_IINF_RD_NUMCON = Int32(54)
MSK_IINF_RD_NUMCONE = Int32(55)
MSK_IINF_RD_NUMINTVAR = Int32(56)
MSK_IINF_RD_NUMQ = Int32(57)
MSK_IINF_RD_NUMVAR = Int32(58)
MSK_IINF_RD_PROTYPE = Int32(59)
MSK_IINF_SIM_DUAL_DEG_ITER = Int32(60)
MSK_IINF_SIM_DUAL_HOTSTART = Int32(61)
MSK_IINF_SIM_DUAL_HOTSTART_LU = Int32(62)
MSK_IINF_SIM_DUAL_INF_ITER = Int32(63)
MSK_IINF_SIM_DUAL_ITER = Int32(64)
MSK_IINF_SIM_NETWORK_DUAL_DEG_ITER = Int32(65)
MSK_IINF_SIM_NETWORK_DUAL_HOTSTART = Int32(66)
MSK_IINF_SIM_NETWORK_DUAL_HOTSTART_LU = Int32(67)
MSK_IINF_SIM_NETWORK_DUAL_INF_ITER = Int32(68)
MSK_IINF_SIM_NETWORK_DUAL_ITER = Int32(69)
MSK_IINF_SIM_NETWORK_PRIMAL_DEG_ITER = Int32(70)
MSK_IINF_SIM_NETWORK_PRIMAL_HOTSTART = Int32(71)
MSK_IINF_SIM_NETWORK_PRIMAL_HOTSTART_LU = Int32(72)
MSK_IINF_SIM_NETWORK_PRIMAL_INF_ITER = Int32(73)
MSK_IINF_SIM_NETWORK_PRIMAL_ITER = Int32(74)
MSK_IINF_SIM_NUMCON = Int32(75)
MSK_IINF_SIM_NUMVAR = Int32(76)
MSK_IINF_SIM_PRIMAL_DEG_ITER = Int32(77)
MSK_IINF_SIM_PRIMAL_DUAL_DEG_ITER = Int32(78)
MSK_IINF_SIM_PRIMAL_DUAL_HOTSTART = Int32(79)
MSK_IINF_SIM_PRIMAL_DUAL_HOTSTART_LU = Int32(80)
MSK_IINF_SIM_PRIMAL_DUAL_INF_ITER = Int32(81)
MSK_IINF_SIM_PRIMAL_DUAL_ITER = Int32(82)
MSK_IINF_SIM_PRIMAL_HOTSTART = Int32(83)
MSK_IINF_SIM_PRIMAL_HOTSTART_LU = Int32(84)
MSK_IINF_SIM_PRIMAL_INF_ITER = Int32(85)
MSK_IINF_SIM_PRIMAL_ITER = Int32(86)
MSK_IINF_SIM_SOLVE_DUAL = Int32(87)
MSK_IINF_SOL_BAS_PROSTA = Int32(88)
MSK_IINF_SOL_BAS_SOLSTA = Int32(89)
MSK_IINF_SOL_ITG_PROSTA = Int32(90)
MSK_IINF_SOL_ITG_SOLSTA = Int32(91)
MSK_IINF_SOL_ITR_PROSTA = Int32(92)
MSK_IINF_SOL_ITR_SOLSTA = Int32(93)
MSK_IINF_STO_NUM_A_REALLOC = Int32(94)

  MSK_IINF_BEGIN = Int32(0)
  MSK_IINF_END   = Int32(95)

# enum xmlwriteroutputtype
MSK_WRITE_XML_MODE_COL = Int32(1)
MSK_WRITE_XML_MODE_ROW = Int32(0)

  MSK_WRITE_XML_MODE_BEGIN = Int32(0)
  MSK_WRITE_XML_MODE_END   = Int32(2)

# enum optimizertype
MSK_OPTIMIZER_CONIC = Int32(0)
MSK_OPTIMIZER_DUAL_SIMPLEX = Int32(1)
MSK_OPTIMIZER_FREE = Int32(2)
MSK_OPTIMIZER_FREE_SIMPLEX = Int32(3)
MSK_OPTIMIZER_INTPNT = Int32(4)
MSK_OPTIMIZER_MIXED_INT = Int32(5)
MSK_OPTIMIZER_PRIMAL_SIMPLEX = Int32(6)

  MSK_OPTIMIZER_BEGIN = Int32(0)
  MSK_OPTIMIZER_END   = Int32(7)

# enum presolvemode
MSK_PRESOLVE_MODE_FREE = Int32(2)
MSK_PRESOLVE_MODE_OFF = Int32(0)
MSK_PRESOLVE_MODE_ON = Int32(1)

  MSK_PRESOLVE_MODE_BEGIN = Int32(0)
  MSK_PRESOLVE_MODE_END   = Int32(3)

# enum miocontsoltype
MSK_MIO_CONT_SOL_ITG = Int32(2)
MSK_MIO_CONT_SOL_ITG_REL = Int32(3)
MSK_MIO_CONT_SOL_NONE = Int32(0)
MSK_MIO_CONT_SOL_ROOT = Int32(1)

  MSK_MIO_CONT_SOL_BEGIN = Int32(0)
  MSK_MIO_CONT_SOL_END   = Int32(4)

