# Contents of this file is generated. Do not edit by hand!
# MOSEK 7.1.0.27

export
  MSK_SOLVE_DUAL,
  MSK_SOLVE_FREE,
  MSK_SOLVE_PRIMAL,
  MSK_SOLVE_BEGIN,
  MSK_SOLVE_END,
  MSK_PI_CON,
  MSK_PI_CONE,
  MSK_PI_VAR,
  MSK_PI_BEGIN,
  MSK_PI_END,
  MSK_ACC_CON,
  MSK_ACC_VAR,
  MSK_ACC_BEGIN,
  MSK_ACC_END,
  MSK_SENSITIVITY_TYPE_BASIS,
  MSK_SENSITIVITY_TYPE_OPTIMAL_PARTITION,
  MSK_SENSITIVITY_TYPE_BEGIN,
  MSK_SENSITIVITY_TYPE_END,
  MSK_UPLO_LO,
  MSK_UPLO_UP,
  MSK_UPLO_BEGIN,
  MSK_UPLO_END,
  MSK_INTPNT_HOTSTART_DUAL,
  MSK_INTPNT_HOTSTART_NONE,
  MSK_INTPNT_HOTSTART_PRIMAL,
  MSK_INTPNT_HOTSTART_PRIMAL_DUAL,
  MSK_INTPNT_HOTSTART_BEGIN,
  MSK_INTPNT_HOTSTART_END,
  MSK_SPAR_BAS_SOL_FILE_NAME,
  MSK_SPAR_DATA_FILE_NAME,
  MSK_SPAR_DEBUG_FILE_NAME,
  MSK_SPAR_FEASREPAIR_NAME_PREFIX,
  MSK_SPAR_FEASREPAIR_NAME_SEPARATOR,
  MSK_SPAR_FEASREPAIR_NAME_WSUMVIOL,
  MSK_SPAR_INT_SOL_FILE_NAME,
  MSK_SPAR_ITR_SOL_FILE_NAME,
  MSK_SPAR_MIO_DEBUG_STRING,
  MSK_SPAR_PARAM_COMMENT_SIGN,
  MSK_SPAR_PARAM_READ_FILE_NAME,
  MSK_SPAR_PARAM_WRITE_FILE_NAME,
  MSK_SPAR_READ_MPS_BOU_NAME,
  MSK_SPAR_READ_MPS_OBJ_NAME,
  MSK_SPAR_READ_MPS_RAN_NAME,
  MSK_SPAR_READ_MPS_RHS_NAME,
  MSK_SPAR_SENSITIVITY_FILE_NAME,
  MSK_SPAR_SENSITIVITY_RES_FILE_NAME,
  MSK_SPAR_SOL_FILTER_XC_LOW,
  MSK_SPAR_SOL_FILTER_XC_UPR,
  MSK_SPAR_SOL_FILTER_XX_LOW,
  MSK_SPAR_SOL_FILTER_XX_UPR,
  MSK_SPAR_STAT_FILE_NAME,
  MSK_SPAR_STAT_KEY,
  MSK_SPAR_STAT_NAME,
  MSK_SPAR_WRITE_LP_GEN_VAR_NAME,
  MSK_SPAR_BEGIN,
  MSK_SPAR_END,
  MSK_IPAR_ALLOC_ADD_QNZ,
  MSK_IPAR_ANA_SOL_BASIS,
  MSK_IPAR_ANA_SOL_PRINT_VIOLATED,
  MSK_IPAR_AUTO_SORT_A_BEFORE_OPT,
  MSK_IPAR_AUTO_UPDATE_SOL_INFO,
  MSK_IPAR_BASIS_SOLVE_USE_PLUS_ONE,
  MSK_IPAR_BI_CLEAN_OPTIMIZER,
  MSK_IPAR_BI_IGNORE_MAX_ITER,
  MSK_IPAR_BI_IGNORE_NUM_ERROR,
  MSK_IPAR_BI_MAX_ITERATIONS,
  MSK_IPAR_CACHE_LICENSE,
  MSK_IPAR_CHECK_CONVEXITY,
  MSK_IPAR_COMPRESS_STATFILE,
  MSK_IPAR_CONCURRENT_NUM_OPTIMIZERS,
  MSK_IPAR_CONCURRENT_PRIORITY_DUAL_SIMPLEX,
  MSK_IPAR_CONCURRENT_PRIORITY_FREE_SIMPLEX,
  MSK_IPAR_CONCURRENT_PRIORITY_INTPNT,
  MSK_IPAR_CONCURRENT_PRIORITY_PRIMAL_SIMPLEX,
  MSK_IPAR_FEASREPAIR_OPTIMIZE,
  MSK_IPAR_INFEAS_GENERIC_NAMES,
  MSK_IPAR_INFEAS_PREFER_PRIMAL,
  MSK_IPAR_INFEAS_REPORT_AUTO,
  MSK_IPAR_INFEAS_REPORT_LEVEL,
  MSK_IPAR_INTPNT_BASIS,
  MSK_IPAR_INTPNT_DIFF_STEP,
  MSK_IPAR_INTPNT_FACTOR_DEBUG_LVL,
  MSK_IPAR_INTPNT_FACTOR_METHOD,
  MSK_IPAR_INTPNT_HOTSTART,
  MSK_IPAR_INTPNT_MAX_ITERATIONS,
  MSK_IPAR_INTPNT_MAX_NUM_COR,
  MSK_IPAR_INTPNT_MAX_NUM_REFINEMENT_STEPS,
  MSK_IPAR_INTPNT_OFF_COL_TRH,
  MSK_IPAR_INTPNT_ORDER_METHOD,
  MSK_IPAR_INTPNT_REGULARIZATION_USE,
  MSK_IPAR_INTPNT_SCALING,
  MSK_IPAR_INTPNT_SOLVE_FORM,
  MSK_IPAR_INTPNT_STARTING_POINT,
  MSK_IPAR_LIC_TRH_EXPIRY_WRN,
  MSK_IPAR_LICENSE_DEBUG,
  MSK_IPAR_LICENSE_PAUSE_TIME,
  MSK_IPAR_LICENSE_SUPPRESS_EXPIRE_WRNS,
  MSK_IPAR_LICENSE_WAIT,
  MSK_IPAR_LOG,
  MSK_IPAR_LOG_BI,
  MSK_IPAR_LOG_BI_FREQ,
  MSK_IPAR_LOG_CHECK_CONVEXITY,
  MSK_IPAR_LOG_CONCURRENT,
  MSK_IPAR_LOG_CUT_SECOND_OPT,
  MSK_IPAR_LOG_EXPAND,
  MSK_IPAR_LOG_FACTOR,
  MSK_IPAR_LOG_FEAS_REPAIR,
  MSK_IPAR_LOG_FILE,
  MSK_IPAR_LOG_HEAD,
  MSK_IPAR_LOG_INFEAS_ANA,
  MSK_IPAR_LOG_INTPNT,
  MSK_IPAR_LOG_MIO,
  MSK_IPAR_LOG_MIO_FREQ,
  MSK_IPAR_LOG_NONCONVEX,
  MSK_IPAR_LOG_OPTIMIZER,
  MSK_IPAR_LOG_ORDER,
  MSK_IPAR_LOG_PARAM,
  MSK_IPAR_LOG_PRESOLVE,
  MSK_IPAR_LOG_RESPONSE,
  MSK_IPAR_LOG_SENSITIVITY,
  MSK_IPAR_LOG_SENSITIVITY_OPT,
  MSK_IPAR_LOG_SIM,
  MSK_IPAR_LOG_SIM_FREQ,
  MSK_IPAR_LOG_SIM_MINOR,
  MSK_IPAR_LOG_SIM_NETWORK_FREQ,
  MSK_IPAR_LOG_STORAGE,
  MSK_IPAR_MAX_NUM_WARNINGS,
  MSK_IPAR_MIO_BRANCH_DIR,
  MSK_IPAR_MIO_BRANCH_PRIORITIES_USE,
  MSK_IPAR_MIO_CONSTRUCT_SOL,
  MSK_IPAR_MIO_CONT_SOL,
  MSK_IPAR_MIO_CUT_CG,
  MSK_IPAR_MIO_CUT_CMIR,
  MSK_IPAR_MIO_CUT_LEVEL_ROOT,
  MSK_IPAR_MIO_CUT_LEVEL_TREE,
  MSK_IPAR_MIO_FEASPUMP_LEVEL,
  MSK_IPAR_MIO_HEURISTIC_LEVEL,
  MSK_IPAR_MIO_HOTSTART,
  MSK_IPAR_MIO_KEEP_BASIS,
  MSK_IPAR_MIO_LOCAL_BRANCH_NUMBER,
  MSK_IPAR_MIO_MAX_NUM_BRANCHES,
  MSK_IPAR_MIO_MAX_NUM_RELAXS,
  MSK_IPAR_MIO_MAX_NUM_SOLUTIONS,
  MSK_IPAR_MIO_MODE,
  MSK_IPAR_MIO_MT_USER_CB,
  MSK_IPAR_MIO_NODE_OPTIMIZER,
  MSK_IPAR_MIO_NODE_SELECTION,
  MSK_IPAR_MIO_OPTIMIZER_MODE,
  MSK_IPAR_MIO_PRESOLVE_AGGREGATE,
  MSK_IPAR_MIO_PRESOLVE_PROBING,
  MSK_IPAR_MIO_PRESOLVE_USE,
  MSK_IPAR_MIO_PROBING_LEVEL,
  MSK_IPAR_MIO_RINS_MAX_NODES,
  MSK_IPAR_MIO_ROOT_OPTIMIZER,
  MSK_IPAR_MIO_STRONG_BRANCH,
  MSK_IPAR_MIO_USE_MULTITHREADED_OPTIMIZER,
  MSK_IPAR_MT_SPINCOUNT,
  MSK_IPAR_NONCONVEX_MAX_ITERATIONS,
  MSK_IPAR_NUM_THREADS,
  MSK_IPAR_OPF_MAX_TERMS_PER_LINE,
  MSK_IPAR_OPF_WRITE_HEADER,
  MSK_IPAR_OPF_WRITE_HINTS,
  MSK_IPAR_OPF_WRITE_PARAMETERS,
  MSK_IPAR_OPF_WRITE_PROBLEM,
  MSK_IPAR_OPF_WRITE_SOL_BAS,
  MSK_IPAR_OPF_WRITE_SOL_ITG,
  MSK_IPAR_OPF_WRITE_SOL_ITR,
  MSK_IPAR_OPF_WRITE_SOLUTIONS,
  MSK_IPAR_OPTIMIZER,
  MSK_IPAR_PARAM_READ_CASE_NAME,
  MSK_IPAR_PARAM_READ_IGN_ERROR,
  MSK_IPAR_PRESOLVE_ELIM_FILL,
  MSK_IPAR_PRESOLVE_ELIMINATOR_MAX_NUM_TRIES,
  MSK_IPAR_PRESOLVE_ELIMINATOR_USE,
  MSK_IPAR_PRESOLVE_LEVEL,
  MSK_IPAR_PRESOLVE_LINDEP_ABS_WORK_TRH,
  MSK_IPAR_PRESOLVE_LINDEP_REL_WORK_TRH,
  MSK_IPAR_PRESOLVE_LINDEP_USE,
  MSK_IPAR_PRESOLVE_MAX_NUM_REDUCTIONS,
  MSK_IPAR_PRESOLVE_USE,
  MSK_IPAR_PRIMAL_REPAIR_OPTIMIZER,
  MSK_IPAR_QO_SEPARABLE_REFORMULATION,
  MSK_IPAR_READ_ANZ,
  MSK_IPAR_READ_CON,
  MSK_IPAR_READ_CONE,
  MSK_IPAR_READ_DATA_COMPRESSED,
  MSK_IPAR_READ_DATA_FORMAT,
  MSK_IPAR_READ_DEBUG,
  MSK_IPAR_READ_KEEP_FREE_CON,
  MSK_IPAR_READ_LP_DROP_NEW_VARS_IN_BOU,
  MSK_IPAR_READ_LP_QUOTED_NAMES,
  MSK_IPAR_READ_MPS_FORMAT,
  MSK_IPAR_READ_MPS_KEEP_INT,
  MSK_IPAR_READ_MPS_OBJ_SENSE,
  MSK_IPAR_READ_MPS_RELAX,
  MSK_IPAR_READ_MPS_WIDTH,
  MSK_IPAR_READ_QNZ,
  MSK_IPAR_READ_TASK_IGNORE_PARAM,
  MSK_IPAR_READ_VAR,
  MSK_IPAR_SENSITIVITY_ALL,
  MSK_IPAR_SENSITIVITY_OPTIMIZER,
  MSK_IPAR_SENSITIVITY_TYPE,
  MSK_IPAR_SIM_BASIS_FACTOR_USE,
  MSK_IPAR_SIM_DEGEN,
  MSK_IPAR_SIM_DUAL_CRASH,
  MSK_IPAR_SIM_DUAL_PHASEONE_METHOD,
  MSK_IPAR_SIM_DUAL_RESTRICT_SELECTION,
  MSK_IPAR_SIM_DUAL_SELECTION,
  MSK_IPAR_SIM_EXPLOIT_DUPVEC,
  MSK_IPAR_SIM_HOTSTART,
  MSK_IPAR_SIM_HOTSTART_LU,
  MSK_IPAR_SIM_INTEGER,
  MSK_IPAR_SIM_MAX_ITERATIONS,
  MSK_IPAR_SIM_MAX_NUM_SETBACKS,
  MSK_IPAR_SIM_NON_SINGULAR,
  MSK_IPAR_SIM_PRIMAL_CRASH,
  MSK_IPAR_SIM_PRIMAL_PHASEONE_METHOD,
  MSK_IPAR_SIM_PRIMAL_RESTRICT_SELECTION,
  MSK_IPAR_SIM_PRIMAL_SELECTION,
  MSK_IPAR_SIM_REFACTOR_FREQ,
  MSK_IPAR_SIM_REFORMULATION,
  MSK_IPAR_SIM_SAVE_LU,
  MSK_IPAR_SIM_SCALING,
  MSK_IPAR_SIM_SCALING_METHOD,
  MSK_IPAR_SIM_SOLVE_FORM,
  MSK_IPAR_SIM_STABILITY_PRIORITY,
  MSK_IPAR_SIM_SWITCH_OPTIMIZER,
  MSK_IPAR_SOL_FILTER_KEEP_BASIC,
  MSK_IPAR_SOL_FILTER_KEEP_RANGED,
  MSK_IPAR_SOL_READ_NAME_WIDTH,
  MSK_IPAR_SOL_READ_WIDTH,
  MSK_IPAR_SOLUTION_CALLBACK,
  MSK_IPAR_TIMING_LEVEL,
  MSK_IPAR_WARNING_LEVEL,
  MSK_IPAR_WRITE_BAS_CONSTRAINTS,
  MSK_IPAR_WRITE_BAS_HEAD,
  MSK_IPAR_WRITE_BAS_VARIABLES,
  MSK_IPAR_WRITE_DATA_COMPRESSED,
  MSK_IPAR_WRITE_DATA_FORMAT,
  MSK_IPAR_WRITE_DATA_PARAM,
  MSK_IPAR_WRITE_FREE_CON,
  MSK_IPAR_WRITE_GENERIC_NAMES,
  MSK_IPAR_WRITE_GENERIC_NAMES_IO,
  MSK_IPAR_WRITE_IGNORE_INCOMPATIBLE_CONIC_ITEMS,
  MSK_IPAR_WRITE_IGNORE_INCOMPATIBLE_ITEMS,
  MSK_IPAR_WRITE_IGNORE_INCOMPATIBLE_NL_ITEMS,
  MSK_IPAR_WRITE_IGNORE_INCOMPATIBLE_PSD_ITEMS,
  MSK_IPAR_WRITE_INT_CONSTRAINTS,
  MSK_IPAR_WRITE_INT_HEAD,
  MSK_IPAR_WRITE_INT_VARIABLES,
  MSK_IPAR_WRITE_LP_LINE_WIDTH,
  MSK_IPAR_WRITE_LP_QUOTED_NAMES,
  MSK_IPAR_WRITE_LP_STRICT_FORMAT,
  MSK_IPAR_WRITE_LP_TERMS_PER_LINE,
  MSK_IPAR_WRITE_MPS_INT,
  MSK_IPAR_WRITE_PRECISION,
  MSK_IPAR_WRITE_SOL_BARVARIABLES,
  MSK_IPAR_WRITE_SOL_CONSTRAINTS,
  MSK_IPAR_WRITE_SOL_HEAD,
  MSK_IPAR_WRITE_SOL_IGNORE_INVALID_NAMES,
  MSK_IPAR_WRITE_SOL_VARIABLES,
  MSK_IPAR_WRITE_TASK_INC_SOL,
  MSK_IPAR_WRITE_XML_MODE,
  MSK_IPAR_BEGIN,
  MSK_IPAR_END,
  MSK_SOL_STA_DUAL_FEAS,
  MSK_SOL_STA_DUAL_INFEAS_CER,
  MSK_SOL_STA_INTEGER_OPTIMAL,
  MSK_SOL_STA_NEAR_DUAL_FEAS,
  MSK_SOL_STA_NEAR_DUAL_INFEAS_CER,
  MSK_SOL_STA_NEAR_INTEGER_OPTIMAL,
  MSK_SOL_STA_NEAR_OPTIMAL,
  MSK_SOL_STA_NEAR_PRIM_AND_DUAL_FEAS,
  MSK_SOL_STA_NEAR_PRIM_FEAS,
  MSK_SOL_STA_NEAR_PRIM_INFEAS_CER,
  MSK_SOL_STA_OPTIMAL,
  MSK_SOL_STA_PRIM_AND_DUAL_FEAS,
  MSK_SOL_STA_PRIM_FEAS,
  MSK_SOL_STA_PRIM_INFEAS_CER,
  MSK_SOL_STA_UNKNOWN,
  MSK_SOL_STA_BEGIN,
  MSK_SOL_STA_END,
  MSK_OBJECTIVE_SENSE_MAXIMIZE,
  MSK_OBJECTIVE_SENSE_MINIMIZE,
  MSK_OBJECTIVE_SENSE_BEGIN,
  MSK_OBJECTIVE_SENSE_END,
  MSK_SOL_ITEM_SLC,
  MSK_SOL_ITEM_SLX,
  MSK_SOL_ITEM_SNX,
  MSK_SOL_ITEM_SUC,
  MSK_SOL_ITEM_SUX,
  MSK_SOL_ITEM_XC,
  MSK_SOL_ITEM_XX,
  MSK_SOL_ITEM_Y,
  MSK_SOL_ITEM_BEGIN,
  MSK_SOL_ITEM_END,
  MSK_BK_FR,
  MSK_BK_FX,
  MSK_BK_LO,
  MSK_BK_RA,
  MSK_BK_UP,
  MSK_BK_BEGIN,
  MSK_BK_END,
  MSK_BI_ALWAYS,
  MSK_BI_IF_FEASIBLE,
  MSK_BI_NEVER,
  MSK_BI_NO_ERROR,
  MSK_BI_RESERVERED,
  MSK_BI_BEGIN,
  MSK_BI_END,
  MSK_BRANCH_DIR_DOWN,
  MSK_BRANCH_DIR_FREE,
  MSK_BRANCH_DIR_UP,
  MSK_BRANCH_DIR_BEGIN,
  MSK_BRANCH_DIR_END,
  MSK_LIINF_BI_CLEAN_DUAL_DEG_ITER,
  MSK_LIINF_BI_CLEAN_DUAL_ITER,
  MSK_LIINF_BI_CLEAN_PRIMAL_DEG_ITER,
  MSK_LIINF_BI_CLEAN_PRIMAL_DUAL_DEG_ITER,
  MSK_LIINF_BI_CLEAN_PRIMAL_DUAL_ITER,
  MSK_LIINF_BI_CLEAN_PRIMAL_DUAL_SUB_ITER,
  MSK_LIINF_BI_CLEAN_PRIMAL_ITER,
  MSK_LIINF_BI_DUAL_ITER,
  MSK_LIINF_BI_PRIMAL_ITER,
  MSK_LIINF_INTPNT_FACTOR_NUM_NZ,
  MSK_LIINF_MIO_INTPNT_ITER,
  MSK_LIINF_MIO_SIMPLEX_ITER,
  MSK_LIINF_RD_NUMANZ,
  MSK_LIINF_RD_NUMQNZ,
  MSK_LIINF_BEGIN,
  MSK_LIINF_END,
  MSK_STREAM_ERR,
  MSK_STREAM_LOG,
  MSK_STREAM_MSG,
  MSK_STREAM_WRN,
  MSK_STREAM_BEGIN,
  MSK_STREAM_END,
  MSK_SIM_HOTSTART_FREE,
  MSK_SIM_HOTSTART_NONE,
  MSK_SIM_HOTSTART_STATUS_KEYS,
  MSK_SIM_HOTSTART_BEGIN,
  MSK_SIM_HOTSTART_END,
  MSK_CALLBACK_BEGIN_BI,
  MSK_CALLBACK_BEGIN_CONCURRENT,
  MSK_CALLBACK_BEGIN_CONIC,
  MSK_CALLBACK_BEGIN_DUAL_BI,
  MSK_CALLBACK_BEGIN_DUAL_SENSITIVITY,
  MSK_CALLBACK_BEGIN_DUAL_SETUP_BI,
  MSK_CALLBACK_BEGIN_DUAL_SIMPLEX,
  MSK_CALLBACK_BEGIN_DUAL_SIMPLEX_BI,
  MSK_CALLBACK_BEGIN_FULL_CONVEXITY_CHECK,
  MSK_CALLBACK_BEGIN_INFEAS_ANA,
  MSK_CALLBACK_BEGIN_INTPNT,
  MSK_CALLBACK_BEGIN_LICENSE_WAIT,
  MSK_CALLBACK_BEGIN_MIO,
  MSK_CALLBACK_BEGIN_NETWORK_DUAL_SIMPLEX,
  MSK_CALLBACK_BEGIN_NETWORK_PRIMAL_SIMPLEX,
  MSK_CALLBACK_BEGIN_NETWORK_SIMPLEX,
  MSK_CALLBACK_BEGIN_NONCONVEX,
  MSK_CALLBACK_BEGIN_OPTIMIZER,
  MSK_CALLBACK_BEGIN_PRESOLVE,
  MSK_CALLBACK_BEGIN_PRIMAL_BI,
  MSK_CALLBACK_BEGIN_PRIMAL_DUAL_SIMPLEX,
  MSK_CALLBACK_BEGIN_PRIMAL_DUAL_SIMPLEX_BI,
  MSK_CALLBACK_BEGIN_PRIMAL_REPAIR,
  MSK_CALLBACK_BEGIN_PRIMAL_SENSITIVITY,
  MSK_CALLBACK_BEGIN_PRIMAL_SETUP_BI,
  MSK_CALLBACK_BEGIN_PRIMAL_SIMPLEX,
  MSK_CALLBACK_BEGIN_PRIMAL_SIMPLEX_BI,
  MSK_CALLBACK_BEGIN_QCQO_REFORMULATE,
  MSK_CALLBACK_BEGIN_READ,
  MSK_CALLBACK_BEGIN_SIMPLEX,
  MSK_CALLBACK_BEGIN_SIMPLEX_BI,
  MSK_CALLBACK_BEGIN_SIMPLEX_NETWORK_DETECT,
  MSK_CALLBACK_BEGIN_WRITE,
  MSK_CALLBACK_CONIC,
  MSK_CALLBACK_DUAL_SIMPLEX,
  MSK_CALLBACK_END_BI,
  MSK_CALLBACK_END_CONCURRENT,
  MSK_CALLBACK_END_CONIC,
  MSK_CALLBACK_END_DUAL_BI,
  MSK_CALLBACK_END_DUAL_SENSITIVITY,
  MSK_CALLBACK_END_DUAL_SETUP_BI,
  MSK_CALLBACK_END_DUAL_SIMPLEX,
  MSK_CALLBACK_END_DUAL_SIMPLEX_BI,
  MSK_CALLBACK_END_FULL_CONVEXITY_CHECK,
  MSK_CALLBACK_END_INFEAS_ANA,
  MSK_CALLBACK_END_INTPNT,
  MSK_CALLBACK_END_LICENSE_WAIT,
  MSK_CALLBACK_END_MIO,
  MSK_CALLBACK_END_NETWORK_DUAL_SIMPLEX,
  MSK_CALLBACK_END_NETWORK_PRIMAL_SIMPLEX,
  MSK_CALLBACK_END_NETWORK_SIMPLEX,
  MSK_CALLBACK_END_NONCONVEX,
  MSK_CALLBACK_END_OPTIMIZER,
  MSK_CALLBACK_END_PRESOLVE,
  MSK_CALLBACK_END_PRIMAL_BI,
  MSK_CALLBACK_END_PRIMAL_DUAL_SIMPLEX,
  MSK_CALLBACK_END_PRIMAL_DUAL_SIMPLEX_BI,
  MSK_CALLBACK_END_PRIMAL_REPAIR,
  MSK_CALLBACK_END_PRIMAL_SENSITIVITY,
  MSK_CALLBACK_END_PRIMAL_SETUP_BI,
  MSK_CALLBACK_END_PRIMAL_SIMPLEX,
  MSK_CALLBACK_END_PRIMAL_SIMPLEX_BI,
  MSK_CALLBACK_END_QCQO_REFORMULATE,
  MSK_CALLBACK_END_READ,
  MSK_CALLBACK_END_SIMPLEX,
  MSK_CALLBACK_END_SIMPLEX_BI,
  MSK_CALLBACK_END_SIMPLEX_NETWORK_DETECT,
  MSK_CALLBACK_END_WRITE,
  MSK_CALLBACK_IM_BI,
  MSK_CALLBACK_IM_CONIC,
  MSK_CALLBACK_IM_DUAL_BI,
  MSK_CALLBACK_IM_DUAL_SENSIVITY,
  MSK_CALLBACK_IM_DUAL_SIMPLEX,
  MSK_CALLBACK_IM_FULL_CONVEXITY_CHECK,
  MSK_CALLBACK_IM_INTPNT,
  MSK_CALLBACK_IM_LICENSE_WAIT,
  MSK_CALLBACK_IM_LU,
  MSK_CALLBACK_IM_MIO,
  MSK_CALLBACK_IM_MIO_DUAL_SIMPLEX,
  MSK_CALLBACK_IM_MIO_INTPNT,
  MSK_CALLBACK_IM_MIO_PRESOLVE,
  MSK_CALLBACK_IM_MIO_PRIMAL_SIMPLEX,
  MSK_CALLBACK_IM_NETWORK_DUAL_SIMPLEX,
  MSK_CALLBACK_IM_NETWORK_PRIMAL_SIMPLEX,
  MSK_CALLBACK_IM_NONCONVEX,
  MSK_CALLBACK_IM_ORDER,
  MSK_CALLBACK_IM_PRESOLVE,
  MSK_CALLBACK_IM_PRIMAL_BI,
  MSK_CALLBACK_IM_PRIMAL_DUAL_SIMPLEX,
  MSK_CALLBACK_IM_PRIMAL_SENSIVITY,
  MSK_CALLBACK_IM_PRIMAL_SIMPLEX,
  MSK_CALLBACK_IM_QO_REFORMULATE,
  MSK_CALLBACK_IM_READ,
  MSK_CALLBACK_IM_SIMPLEX,
  MSK_CALLBACK_IM_SIMPLEX_BI,
  MSK_CALLBACK_INTPNT,
  MSK_CALLBACK_NEW_INT_MIO,
  MSK_CALLBACK_NONCOVEX,
  MSK_CALLBACK_PRIMAL_SIMPLEX,
  MSK_CALLBACK_READ_OPF,
  MSK_CALLBACK_READ_OPF_SECTION,
  MSK_CALLBACK_UPDATE_DUAL_BI,
  MSK_CALLBACK_UPDATE_DUAL_SIMPLEX,
  MSK_CALLBACK_UPDATE_DUAL_SIMPLEX_BI,
  MSK_CALLBACK_UPDATE_NETWORK_DUAL_SIMPLEX,
  MSK_CALLBACK_UPDATE_NETWORK_PRIMAL_SIMPLEX,
  MSK_CALLBACK_UPDATE_NONCONVEX,
  MSK_CALLBACK_UPDATE_PRESOLVE,
  MSK_CALLBACK_UPDATE_PRIMAL_BI,
  MSK_CALLBACK_UPDATE_PRIMAL_DUAL_SIMPLEX,
  MSK_CALLBACK_UPDATE_PRIMAL_DUAL_SIMPLEX_BI,
  MSK_CALLBACK_UPDATE_PRIMAL_SIMPLEX,
  MSK_CALLBACK_UPDATE_PRIMAL_SIMPLEX_BI,
  MSK_CALLBACK_WRITE_OPF,
  MSK_CALLBACK_BEGIN,
  MSK_CALLBACK_END,
  MSK_SYMMAT_TYPE_SPARSE,
  MSK_SYMMAT_TYPE_BEGIN,
  MSK_SYMMAT_TYPE_END,
  MSK_FEATURE_PTOM,
  MSK_FEATURE_PTON,
  MSK_FEATURE_PTOX,
  MSK_FEATURE_PTS,
  MSK_FEATURE_BEGIN,
  MSK_FEATURE_END,
  MSK_MARK_LO,
  MSK_MARK_UP,
  MSK_MARK_BEGIN,
  MSK_MARK_END,
  MSK_CT_QUAD,
  MSK_CT_RQUAD,
  MSK_CT_BEGIN,
  MSK_CT_END,
  MSK_FEASREPAIR_OPTIMIZE_COMBINED,
  MSK_FEASREPAIR_OPTIMIZE_NONE,
  MSK_FEASREPAIR_OPTIMIZE_PENALTY,
  MSK_FEASREPAIR_BEGIN,
  MSK_FEASREPAIR_END,
  MSK_IOMODE_READ,
  MSK_IOMODE_READWRITE,
  MSK_IOMODE_WRITE,
  MSK_IOMODE_BEGIN,
  MSK_IOMODE_END,
  MSK_SIM_SELECTION_ASE,
  MSK_SIM_SELECTION_DEVEX,
  MSK_SIM_SELECTION_FREE,
  MSK_SIM_SELECTION_FULL,
  MSK_SIM_SELECTION_PARTIAL,
  MSK_SIM_SELECTION_SE,
  MSK_SIM_SELECTION_BEGIN,
  MSK_SIM_SELECTION_END,
  MSK_MSG_MPS_SELECTED,
  MSK_MSG_READING_FILE,
  MSK_MSG_WRITING_FILE,
  MSK_MIO_MODE_IGNORED,
  MSK_MIO_MODE_LAZY,
  MSK_MIO_MODE_SATISFIED,
  MSK_MIO_MODE_BEGIN,
  MSK_MIO_MODE_END,
  MSK_DINF_BI_CLEAN_DUAL_TIME,
  MSK_DINF_BI_CLEAN_PRIMAL_DUAL_TIME,
  MSK_DINF_BI_CLEAN_PRIMAL_TIME,
  MSK_DINF_BI_CLEAN_TIME,
  MSK_DINF_BI_DUAL_TIME,
  MSK_DINF_BI_PRIMAL_TIME,
  MSK_DINF_BI_TIME,
  MSK_DINF_CONCURRENT_TIME,
  MSK_DINF_INTPNT_DUAL_FEAS,
  MSK_DINF_INTPNT_DUAL_OBJ,
  MSK_DINF_INTPNT_FACTOR_NUM_FLOPS,
  MSK_DINF_INTPNT_OPT_STATUS,
  MSK_DINF_INTPNT_ORDER_TIME,
  MSK_DINF_INTPNT_PRIMAL_FEAS,
  MSK_DINF_INTPNT_PRIMAL_OBJ,
  MSK_DINF_INTPNT_TIME,
  MSK_DINF_MIO_CG_SEPERATION_TIME,
  MSK_DINF_MIO_CMIR_SEPERATION_TIME,
  MSK_DINF_MIO_CONSTRUCT_SOLUTION_OBJ,
  MSK_DINF_MIO_DUAL_BOUND_AFTER_PRESOLVE,
  MSK_DINF_MIO_HEURISTIC_TIME,
  MSK_DINF_MIO_OBJ_ABS_GAP,
  MSK_DINF_MIO_OBJ_BOUND,
  MSK_DINF_MIO_OBJ_INT,
  MSK_DINF_MIO_OBJ_REL_GAP,
  MSK_DINF_MIO_OPTIMIZER_TIME,
  MSK_DINF_MIO_PROBING_TIME,
  MSK_DINF_MIO_ROOT_CUTGEN_TIME,
  MSK_DINF_MIO_ROOT_OPTIMIZER_TIME,
  MSK_DINF_MIO_ROOT_PRESOLVE_TIME,
  MSK_DINF_MIO_TIME,
  MSK_DINF_MIO_USER_OBJ_CUT,
  MSK_DINF_OPTIMIZER_TIME,
  MSK_DINF_PRESOLVE_ELI_TIME,
  MSK_DINF_PRESOLVE_LINDEP_TIME,
  MSK_DINF_PRESOLVE_TIME,
  MSK_DINF_PRIMAL_REPAIR_PENALTY_OBJ,
  MSK_DINF_QCQO_REFORMULATE_TIME,
  MSK_DINF_RD_TIME,
  MSK_DINF_SIM_DUAL_TIME,
  MSK_DINF_SIM_FEAS,
  MSK_DINF_SIM_NETWORK_DUAL_TIME,
  MSK_DINF_SIM_NETWORK_PRIMAL_TIME,
  MSK_DINF_SIM_NETWORK_TIME,
  MSK_DINF_SIM_OBJ,
  MSK_DINF_SIM_PRIMAL_DUAL_TIME,
  MSK_DINF_SIM_PRIMAL_TIME,
  MSK_DINF_SIM_TIME,
  MSK_DINF_SOL_BAS_DUAL_OBJ,
  MSK_DINF_SOL_BAS_DVIOLCON,
  MSK_DINF_SOL_BAS_DVIOLVAR,
  MSK_DINF_SOL_BAS_PRIMAL_OBJ,
  MSK_DINF_SOL_BAS_PVIOLCON,
  MSK_DINF_SOL_BAS_PVIOLVAR,
  MSK_DINF_SOL_ITG_PRIMAL_OBJ,
  MSK_DINF_SOL_ITG_PVIOLBARVAR,
  MSK_DINF_SOL_ITG_PVIOLCON,
  MSK_DINF_SOL_ITG_PVIOLCONES,
  MSK_DINF_SOL_ITG_PVIOLITG,
  MSK_DINF_SOL_ITG_PVIOLVAR,
  MSK_DINF_SOL_ITR_DUAL_OBJ,
  MSK_DINF_SOL_ITR_DVIOLBARVAR,
  MSK_DINF_SOL_ITR_DVIOLCON,
  MSK_DINF_SOL_ITR_DVIOLCONES,
  MSK_DINF_SOL_ITR_DVIOLVAR,
  MSK_DINF_SOL_ITR_PRIMAL_OBJ,
  MSK_DINF_SOL_ITR_PVIOLBARVAR,
  MSK_DINF_SOL_ITR_PVIOLCON,
  MSK_DINF_SOL_ITR_PVIOLCONES,
  MSK_DINF_SOL_ITR_PVIOLVAR,
  MSK_DINF_BEGIN,
  MSK_DINF_END,
  MSK_PAR_DOU_TYPE,
  MSK_PAR_INT_TYPE,
  MSK_PAR_INVALID_TYPE,
  MSK_PAR_STR_TYPE,
  MSK_PAR_BEGIN,
  MSK_PAR_END,
  MSK_RESPONSE_ERR,
  MSK_RESPONSE_OK,
  MSK_RESPONSE_TRM,
  MSK_RESPONSE_UNK,
  MSK_RESPONSE_WRN,
  MSK_RESPONSE_BEGIN,
  MSK_RESPONSE_END,
  MSK_PRO_STA_DUAL_FEAS,
  MSK_PRO_STA_DUAL_INFEAS,
  MSK_PRO_STA_ILL_POSED,
  MSK_PRO_STA_NEAR_DUAL_FEAS,
  MSK_PRO_STA_NEAR_PRIM_AND_DUAL_FEAS,
  MSK_PRO_STA_NEAR_PRIM_FEAS,
  MSK_PRO_STA_PRIM_AND_DUAL_FEAS,
  MSK_PRO_STA_PRIM_AND_DUAL_INFEAS,
  MSK_PRO_STA_PRIM_FEAS,
  MSK_PRO_STA_PRIM_INFEAS,
  MSK_PRO_STA_PRIM_INFEAS_OR_UNBOUNDED,
  MSK_PRO_STA_UNKNOWN,
  MSK_PRO_STA_BEGIN,
  MSK_PRO_STA_END,
  MSK_SCALING_AGGRESSIVE,
  MSK_SCALING_FREE,
  MSK_SCALING_MODERATE,
  MSK_SCALING_NONE,
  MSK_SCALING_BEGIN,
  MSK_SCALING_END,
  MSK_RES_ERR_AD_INVALID_CODELIST,
  MSK_RES_ERR_AD_INVALID_OPERAND,
  MSK_RES_ERR_AD_INVALID_OPERATOR,
  MSK_RES_ERR_AD_MISSING_OPERAND,
  MSK_RES_ERR_AD_MISSING_RETURN,
  MSK_RES_ERR_API_ARRAY_TOO_SMALL,
  MSK_RES_ERR_API_CB_CONNECT,
  MSK_RES_ERR_API_FATAL_ERROR,
  MSK_RES_ERR_API_INTERNAL,
  MSK_RES_ERR_ARG_IS_TOO_LARGE,
  MSK_RES_ERR_ARG_IS_TOO_SMALL,
  MSK_RES_ERR_ARGUMENT_DIMENSION,
  MSK_RES_ERR_ARGUMENT_IS_TOO_LARGE,
  MSK_RES_ERR_ARGUMENT_LENNEQ,
  MSK_RES_ERR_ARGUMENT_PERM_ARRAY,
  MSK_RES_ERR_ARGUMENT_TYPE,
  MSK_RES_ERR_BAR_VAR_DIM,
  MSK_RES_ERR_BASIS,
  MSK_RES_ERR_BASIS_FACTOR,
  MSK_RES_ERR_BASIS_SINGULAR,
  MSK_RES_ERR_BLANK_NAME,
  MSK_RES_ERR_CANNOT_CLONE_NL,
  MSK_RES_ERR_CANNOT_HANDLE_NL,
  MSK_RES_ERR_CBF_DUPLICATE_ACOORD,
  MSK_RES_ERR_CBF_DUPLICATE_BCOORD,
  MSK_RES_ERR_CBF_DUPLICATE_CON,
  MSK_RES_ERR_CBF_DUPLICATE_INT,
  MSK_RES_ERR_CBF_DUPLICATE_OBJ,
  MSK_RES_ERR_CBF_DUPLICATE_OBJACOORD,
  MSK_RES_ERR_CBF_DUPLICATE_VAR,
  MSK_RES_ERR_CBF_INVALID_CON_TYPE,
  MSK_RES_ERR_CBF_INVALID_DOMAIN_DIMENSION,
  MSK_RES_ERR_CBF_INVALID_INT_INDEX,
  MSK_RES_ERR_CBF_INVALID_VAR_TYPE,
  MSK_RES_ERR_CBF_NO_VARIABLES,
  MSK_RES_ERR_CBF_NO_VERSION_SPECIFIED,
  MSK_RES_ERR_CBF_OBJ_SENSE,
  MSK_RES_ERR_CBF_PARSE,
  MSK_RES_ERR_CBF_SYNTAX,
  MSK_RES_ERR_CBF_TOO_FEW_CONSTRAINTS,
  MSK_RES_ERR_CBF_TOO_FEW_INTS,
  MSK_RES_ERR_CBF_TOO_FEW_VARIABLES,
  MSK_RES_ERR_CBF_TOO_MANY_CONSTRAINTS,
  MSK_RES_ERR_CBF_TOO_MANY_INTS,
  MSK_RES_ERR_CBF_TOO_MANY_VARIABLES,
  MSK_RES_ERR_CBF_UNSUPPORTED,
  MSK_RES_ERR_CON_Q_NOT_NSD,
  MSK_RES_ERR_CON_Q_NOT_PSD,
  MSK_RES_ERR_CONCURRENT_OPTIMIZER,
  MSK_RES_ERR_CONE_INDEX,
  MSK_RES_ERR_CONE_OVERLAP,
  MSK_RES_ERR_CONE_OVERLAP_APPEND,
  MSK_RES_ERR_CONE_REP_VAR,
  MSK_RES_ERR_CONE_SIZE,
  MSK_RES_ERR_CONE_TYPE,
  MSK_RES_ERR_CONE_TYPE_STR,
  MSK_RES_ERR_DATA_FILE_EXT,
  MSK_RES_ERR_DUP_NAME,
  MSK_RES_ERR_DUPLICATE_BARVARIABLE_NAMES,
  MSK_RES_ERR_DUPLICATE_CONE_NAMES,
  MSK_RES_ERR_DUPLICATE_CONSTRAINT_NAMES,
  MSK_RES_ERR_DUPLICATE_VARIABLE_NAMES,
  MSK_RES_ERR_END_OF_FILE,
  MSK_RES_ERR_FACTOR,
  MSK_RES_ERR_FEASREPAIR_CANNOT_RELAX,
  MSK_RES_ERR_FEASREPAIR_INCONSISTENT_BOUND,
  MSK_RES_ERR_FEASREPAIR_SOLVING_RELAXED,
  MSK_RES_ERR_FILE_LICENSE,
  MSK_RES_ERR_FILE_OPEN,
  MSK_RES_ERR_FILE_READ,
  MSK_RES_ERR_FILE_WRITE,
  MSK_RES_ERR_FIRST,
  MSK_RES_ERR_FIRSTI,
  MSK_RES_ERR_FIRSTJ,
  MSK_RES_ERR_FIXED_BOUND_VALUES,
  MSK_RES_ERR_FLEXLM,
  MSK_RES_ERR_GLOBAL_INV_CONIC_PROBLEM,
  MSK_RES_ERR_HUGE_AIJ,
  MSK_RES_ERR_HUGE_C,
  MSK_RES_ERR_IDENTICAL_TASKS,
  MSK_RES_ERR_IN_ARGUMENT,
  MSK_RES_ERR_INDEX,
  MSK_RES_ERR_INDEX_ARR_IS_TOO_LARGE,
  MSK_RES_ERR_INDEX_ARR_IS_TOO_SMALL,
  MSK_RES_ERR_INDEX_IS_TOO_LARGE,
  MSK_RES_ERR_INDEX_IS_TOO_SMALL,
  MSK_RES_ERR_INF_DOU_INDEX,
  MSK_RES_ERR_INF_DOU_NAME,
  MSK_RES_ERR_INF_INT_INDEX,
  MSK_RES_ERR_INF_INT_NAME,
  MSK_RES_ERR_INF_LINT_INDEX,
  MSK_RES_ERR_INF_LINT_NAME,
  MSK_RES_ERR_INF_TYPE,
  MSK_RES_ERR_INFEAS_UNDEFINED,
  MSK_RES_ERR_INFINITE_BOUND,
  MSK_RES_ERR_INT64_TO_INT32_CAST,
  MSK_RES_ERR_INTERNAL,
  MSK_RES_ERR_INTERNAL_TEST_FAILED,
  MSK_RES_ERR_INV_APTRE,
  MSK_RES_ERR_INV_BK,
  MSK_RES_ERR_INV_BKC,
  MSK_RES_ERR_INV_BKX,
  MSK_RES_ERR_INV_CONE_TYPE,
  MSK_RES_ERR_INV_CONE_TYPE_STR,
  MSK_RES_ERR_INV_CONIC_PROBLEM,
  MSK_RES_ERR_INV_MARKI,
  MSK_RES_ERR_INV_MARKJ,
  MSK_RES_ERR_INV_NAME_ITEM,
  MSK_RES_ERR_INV_NUMI,
  MSK_RES_ERR_INV_NUMJ,
  MSK_RES_ERR_INV_OPTIMIZER,
  MSK_RES_ERR_INV_PROBLEM,
  MSK_RES_ERR_INV_QCON_SUBI,
  MSK_RES_ERR_INV_QCON_SUBJ,
  MSK_RES_ERR_INV_QCON_SUBK,
  MSK_RES_ERR_INV_QCON_VAL,
  MSK_RES_ERR_INV_QOBJ_SUBI,
  MSK_RES_ERR_INV_QOBJ_SUBJ,
  MSK_RES_ERR_INV_QOBJ_VAL,
  MSK_RES_ERR_INV_SK,
  MSK_RES_ERR_INV_SK_STR,
  MSK_RES_ERR_INV_SKC,
  MSK_RES_ERR_INV_SKN,
  MSK_RES_ERR_INV_SKX,
  MSK_RES_ERR_INV_VAR_TYPE,
  MSK_RES_ERR_INVALID_ACCMODE,
  MSK_RES_ERR_INVALID_AIJ,
  MSK_RES_ERR_INVALID_AMPL_STUB,
  MSK_RES_ERR_INVALID_BARVAR_NAME,
  MSK_RES_ERR_INVALID_BRANCH_DIRECTION,
  MSK_RES_ERR_INVALID_BRANCH_PRIORITY,
  MSK_RES_ERR_INVALID_COMPRESSION,
  MSK_RES_ERR_INVALID_CON_NAME,
  MSK_RES_ERR_INVALID_CONE_NAME,
  MSK_RES_ERR_INVALID_FILE_FORMAT_FOR_CONES,
  MSK_RES_ERR_INVALID_FILE_FORMAT_FOR_GENERAL_NL,
  MSK_RES_ERR_INVALID_FILE_FORMAT_FOR_SYM_MAT,
  MSK_RES_ERR_INVALID_FILE_NAME,
  MSK_RES_ERR_INVALID_FORMAT_TYPE,
  MSK_RES_ERR_INVALID_IDX,
  MSK_RES_ERR_INVALID_IOMODE,
  MSK_RES_ERR_INVALID_MAX_NUM,
  MSK_RES_ERR_INVALID_NAME_IN_SOL_FILE,
  MSK_RES_ERR_INVALID_NETWORK_PROBLEM,
  MSK_RES_ERR_INVALID_OBJ_NAME,
  MSK_RES_ERR_INVALID_OBJECTIVE_SENSE,
  MSK_RES_ERR_INVALID_PROBLEM_TYPE,
  MSK_RES_ERR_INVALID_SOL_FILE_NAME,
  MSK_RES_ERR_INVALID_STREAM,
  MSK_RES_ERR_INVALID_SURPLUS,
  MSK_RES_ERR_INVALID_SYM_MAT_DIM,
  MSK_RES_ERR_INVALID_TASK,
  MSK_RES_ERR_INVALID_UTF8,
  MSK_RES_ERR_INVALID_VAR_NAME,
  MSK_RES_ERR_INVALID_WCHAR,
  MSK_RES_ERR_INVALID_WHICHSOL,
  MSK_RES_ERR_LAST,
  MSK_RES_ERR_LASTI,
  MSK_RES_ERR_LASTJ,
  MSK_RES_ERR_LAU_ARG_K,
  MSK_RES_ERR_LAU_ARG_M,
  MSK_RES_ERR_LAU_ARG_N,
  MSK_RES_ERR_LAU_ARG_TRANS,
  MSK_RES_ERR_LAU_ARG_TRANSA,
  MSK_RES_ERR_LAU_ARG_TRANSB,
  MSK_RES_ERR_LAU_ARG_UPLO,
  MSK_RES_ERR_LAU_SINGULAR_MATRIX,
  MSK_RES_ERR_LAU_UNKNOWN,
  MSK_RES_ERR_LICENSE,
  MSK_RES_ERR_LICENSE_CANNOT_ALLOCATE,
  MSK_RES_ERR_LICENSE_CANNOT_CONNECT,
  MSK_RES_ERR_LICENSE_EXPIRED,
  MSK_RES_ERR_LICENSE_FEATURE,
  MSK_RES_ERR_LICENSE_INVALID_HOSTID,
  MSK_RES_ERR_LICENSE_MAX,
  MSK_RES_ERR_LICENSE_MOSEKLM_DAEMON,
  MSK_RES_ERR_LICENSE_NO_SERVER_LINE,
  MSK_RES_ERR_LICENSE_NO_SERVER_SUPPORT,
  MSK_RES_ERR_LICENSE_SERVER,
  MSK_RES_ERR_LICENSE_SERVER_VERSION,
  MSK_RES_ERR_LICENSE_VERSION,
  MSK_RES_ERR_LINK_FILE_DLL,
  MSK_RES_ERR_LIVING_TASKS,
  MSK_RES_ERR_LOWER_BOUND_IS_A_NAN,
  MSK_RES_ERR_LP_DUP_SLACK_NAME,
  MSK_RES_ERR_LP_EMPTY,
  MSK_RES_ERR_LP_FILE_FORMAT,
  MSK_RES_ERR_LP_FORMAT,
  MSK_RES_ERR_LP_FREE_CONSTRAINT,
  MSK_RES_ERR_LP_INCOMPATIBLE,
  MSK_RES_ERR_LP_INVALID_CON_NAME,
  MSK_RES_ERR_LP_INVALID_VAR_NAME,
  MSK_RES_ERR_LP_WRITE_CONIC_PROBLEM,
  MSK_RES_ERR_LP_WRITE_GECO_PROBLEM,
  MSK_RES_ERR_LU_MAX_NUM_TRIES,
  MSK_RES_ERR_MAX_LEN_IS_TOO_SMALL,
  MSK_RES_ERR_MAXNUMBARVAR,
  MSK_RES_ERR_MAXNUMCON,
  MSK_RES_ERR_MAXNUMCONE,
  MSK_RES_ERR_MAXNUMQNZ,
  MSK_RES_ERR_MAXNUMVAR,
  MSK_RES_ERR_MBT_INCOMPATIBLE,
  MSK_RES_ERR_MBT_INVALID,
  MSK_RES_ERR_MIO_INTERNAL,
  MSK_RES_ERR_MIO_INVALID_NODE_OPTIMIZER,
  MSK_RES_ERR_MIO_INVALID_ROOT_OPTIMIZER,
  MSK_RES_ERR_MIO_NO_OPTIMIZER,
  MSK_RES_ERR_MIO_NOT_LOADED,
  MSK_RES_ERR_MISSING_LICENSE_FILE,
  MSK_RES_ERR_MIXED_PROBLEM,
  MSK_RES_ERR_MPS_CONE_OVERLAP,
  MSK_RES_ERR_MPS_CONE_REPEAT,
  MSK_RES_ERR_MPS_CONE_TYPE,
  MSK_RES_ERR_MPS_DUPLICATE_Q_ELEMENT,
  MSK_RES_ERR_MPS_FILE,
  MSK_RES_ERR_MPS_INV_BOUND_KEY,
  MSK_RES_ERR_MPS_INV_CON_KEY,
  MSK_RES_ERR_MPS_INV_FIELD,
  MSK_RES_ERR_MPS_INV_MARKER,
  MSK_RES_ERR_MPS_INV_SEC_NAME,
  MSK_RES_ERR_MPS_INV_SEC_ORDER,
  MSK_RES_ERR_MPS_INVALID_OBJ_NAME,
  MSK_RES_ERR_MPS_INVALID_OBJSENSE,
  MSK_RES_ERR_MPS_MUL_CON_NAME,
  MSK_RES_ERR_MPS_MUL_CSEC,
  MSK_RES_ERR_MPS_MUL_QOBJ,
  MSK_RES_ERR_MPS_MUL_QSEC,
  MSK_RES_ERR_MPS_NO_OBJECTIVE,
  MSK_RES_ERR_MPS_NON_SYMMETRIC_Q,
  MSK_RES_ERR_MPS_NULL_CON_NAME,
  MSK_RES_ERR_MPS_NULL_VAR_NAME,
  MSK_RES_ERR_MPS_SPLITTED_VAR,
  MSK_RES_ERR_MPS_TAB_IN_FIELD2,
  MSK_RES_ERR_MPS_TAB_IN_FIELD3,
  MSK_RES_ERR_MPS_TAB_IN_FIELD5,
  MSK_RES_ERR_MPS_UNDEF_CON_NAME,
  MSK_RES_ERR_MPS_UNDEF_VAR_NAME,
  MSK_RES_ERR_MUL_A_ELEMENT,
  MSK_RES_ERR_NAME_IS_NULL,
  MSK_RES_ERR_NAME_MAX_LEN,
  MSK_RES_ERR_NAN_IN_BLC,
  MSK_RES_ERR_NAN_IN_BLX,
  MSK_RES_ERR_NAN_IN_BUC,
  MSK_RES_ERR_NAN_IN_BUX,
  MSK_RES_ERR_NAN_IN_C,
  MSK_RES_ERR_NAN_IN_DOUBLE_DATA,
  MSK_RES_ERR_NEGATIVE_APPEND,
  MSK_RES_ERR_NEGATIVE_SURPLUS,
  MSK_RES_ERR_NEWER_DLL,
  MSK_RES_ERR_NO_BARS_FOR_SOLUTION,
  MSK_RES_ERR_NO_BARX_FOR_SOLUTION,
  MSK_RES_ERR_NO_BASIS_SOL,
  MSK_RES_ERR_NO_DUAL_FOR_ITG_SOL,
  MSK_RES_ERR_NO_DUAL_INFEAS_CER,
  MSK_RES_ERR_NO_DUAL_INFO_FOR_ITG_SOL,
  MSK_RES_ERR_NO_INIT_ENV,
  MSK_RES_ERR_NO_OPTIMIZER_VAR_TYPE,
  MSK_RES_ERR_NO_PRIMAL_INFEAS_CER,
  MSK_RES_ERR_NO_SNX_FOR_BAS_SOL,
  MSK_RES_ERR_NO_SOLUTION_IN_CALLBACK,
  MSK_RES_ERR_NON_UNIQUE_ARRAY,
  MSK_RES_ERR_NONCONVEX,
  MSK_RES_ERR_NONLINEAR_EQUALITY,
  MSK_RES_ERR_NONLINEAR_FUNCTIONS_NOT_ALLOWED,
  MSK_RES_ERR_NONLINEAR_RANGED,
  MSK_RES_ERR_NR_ARGUMENTS,
  MSK_RES_ERR_NULL_ENV,
  MSK_RES_ERR_NULL_POINTER,
  MSK_RES_ERR_NULL_TASK,
  MSK_RES_ERR_NUMCONLIM,
  MSK_RES_ERR_NUMVARLIM,
  MSK_RES_ERR_OBJ_Q_NOT_NSD,
  MSK_RES_ERR_OBJ_Q_NOT_PSD,
  MSK_RES_ERR_OBJECTIVE_RANGE,
  MSK_RES_ERR_OLDER_DLL,
  MSK_RES_ERR_OPEN_DL,
  MSK_RES_ERR_OPF_FORMAT,
  MSK_RES_ERR_OPF_NEW_VARIABLE,
  MSK_RES_ERR_OPF_PREMATURE_EOF,
  MSK_RES_ERR_OPTIMIZER_LICENSE,
  MSK_RES_ERR_ORD_INVALID,
  MSK_RES_ERR_ORD_INVALID_BRANCH_DIR,
  MSK_RES_ERR_OVERFLOW,
  MSK_RES_ERR_PARAM_INDEX,
  MSK_RES_ERR_PARAM_IS_TOO_LARGE,
  MSK_RES_ERR_PARAM_IS_TOO_SMALL,
  MSK_RES_ERR_PARAM_NAME,
  MSK_RES_ERR_PARAM_NAME_DOU,
  MSK_RES_ERR_PARAM_NAME_INT,
  MSK_RES_ERR_PARAM_NAME_STR,
  MSK_RES_ERR_PARAM_TYPE,
  MSK_RES_ERR_PARAM_VALUE_STR,
  MSK_RES_ERR_PLATFORM_NOT_LICENSED,
  MSK_RES_ERR_POSTSOLVE,
  MSK_RES_ERR_PRO_ITEM,
  MSK_RES_ERR_PROB_LICENSE,
  MSK_RES_ERR_QCON_SUBI_TOO_LARGE,
  MSK_RES_ERR_QCON_SUBI_TOO_SMALL,
  MSK_RES_ERR_QCON_UPPER_TRIANGLE,
  MSK_RES_ERR_QOBJ_UPPER_TRIANGLE,
  MSK_RES_ERR_READ_FORMAT,
  MSK_RES_ERR_READ_LP_MISSING_END_TAG,
  MSK_RES_ERR_READ_LP_NONEXISTING_NAME,
  MSK_RES_ERR_REMOVE_CONE_VARIABLE,
  MSK_RES_ERR_REPAIR_INVALID_PROBLEM,
  MSK_RES_ERR_REPAIR_OPTIMIZATION_FAILED,
  MSK_RES_ERR_SEN_BOUND_INVALID_LO,
  MSK_RES_ERR_SEN_BOUND_INVALID_UP,
  MSK_RES_ERR_SEN_FORMAT,
  MSK_RES_ERR_SEN_INDEX_INVALID,
  MSK_RES_ERR_SEN_INDEX_RANGE,
  MSK_RES_ERR_SEN_INVALID_REGEXP,
  MSK_RES_ERR_SEN_NUMERICAL,
  MSK_RES_ERR_SEN_SOLUTION_STATUS,
  MSK_RES_ERR_SEN_UNDEF_NAME,
  MSK_RES_ERR_SEN_UNHANDLED_PROBLEM_TYPE,
  MSK_RES_ERR_SIZE_LICENSE,
  MSK_RES_ERR_SIZE_LICENSE_CON,
  MSK_RES_ERR_SIZE_LICENSE_INTVAR,
  MSK_RES_ERR_SIZE_LICENSE_NUMCORES,
  MSK_RES_ERR_SIZE_LICENSE_VAR,
  MSK_RES_ERR_SOL_FILE_INVALID_NUMBER,
  MSK_RES_ERR_SOLITEM,
  MSK_RES_ERR_SOLVER_PROBTYPE,
  MSK_RES_ERR_SPACE,
  MSK_RES_ERR_SPACE_LEAKING,
  MSK_RES_ERR_SPACE_NO_INFO,
  MSK_RES_ERR_SYM_MAT_DUPLICATE,
  MSK_RES_ERR_SYM_MAT_INVALID_COL_INDEX,
  MSK_RES_ERR_SYM_MAT_INVALID_ROW_INDEX,
  MSK_RES_ERR_SYM_MAT_INVALID_VALUE,
  MSK_RES_ERR_SYM_MAT_NOT_LOWER_TRINGULAR,
  MSK_RES_ERR_TASK_INCOMPATIBLE,
  MSK_RES_ERR_TASK_INVALID,
  MSK_RES_ERR_THREAD_COND_INIT,
  MSK_RES_ERR_THREAD_CREATE,
  MSK_RES_ERR_THREAD_MUTEX_INIT,
  MSK_RES_ERR_THREAD_MUTEX_LOCK,
  MSK_RES_ERR_THREAD_MUTEX_UNLOCK,
  MSK_RES_ERR_TOCONIC_CONVERSION_FAIL,
  MSK_RES_ERR_TOO_MANY_CONCURRENT_TASKS,
  MSK_RES_ERR_TOO_SMALL_MAX_NUM_NZ,
  MSK_RES_ERR_TOO_SMALL_MAXNUMANZ,
  MSK_RES_ERR_UNB_STEP_SIZE,
  MSK_RES_ERR_UNDEF_SOLUTION,
  MSK_RES_ERR_UNDEFINED_OBJECTIVE_SENSE,
  MSK_RES_ERR_UNHANDLED_SOLUTION_STATUS,
  MSK_RES_ERR_UNKNOWN,
  MSK_RES_ERR_UPPER_BOUND_IS_A_NAN,
  MSK_RES_ERR_UPPER_TRIANGLE,
  MSK_RES_ERR_USER_FUNC_RET,
  MSK_RES_ERR_USER_FUNC_RET_DATA,
  MSK_RES_ERR_USER_NLO_EVAL,
  MSK_RES_ERR_USER_NLO_EVAL_HESSUBI,
  MSK_RES_ERR_USER_NLO_EVAL_HESSUBJ,
  MSK_RES_ERR_USER_NLO_FUNC,
  MSK_RES_ERR_WHICHITEM_NOT_ALLOWED,
  MSK_RES_ERR_WHICHSOL,
  MSK_RES_ERR_WRITE_LP_FORMAT,
  MSK_RES_ERR_WRITE_LP_NON_UNIQUE_NAME,
  MSK_RES_ERR_WRITE_MPS_INVALID_NAME,
  MSK_RES_ERR_WRITE_OPF_INVALID_VAR_NAME,
  MSK_RES_ERR_WRITING_FILE,
  MSK_RES_ERR_XML_INVALID_PROBLEM_TYPE,
  MSK_RES_ERR_Y_IS_UNDEFINED,
  MSK_RES_OK,
  MSK_RES_TRM_INTERNAL,
  MSK_RES_TRM_INTERNAL_STOP,
  MSK_RES_TRM_MAX_ITERATIONS,
  MSK_RES_TRM_MAX_NUM_SETBACKS,
  MSK_RES_TRM_MAX_TIME,
  MSK_RES_TRM_MIO_NEAR_ABS_GAP,
  MSK_RES_TRM_MIO_NEAR_REL_GAP,
  MSK_RES_TRM_MIO_NUM_BRANCHES,
  MSK_RES_TRM_MIO_NUM_RELAXS,
  MSK_RES_TRM_NUM_MAX_NUM_INT_SOLUTIONS,
  MSK_RES_TRM_NUMERICAL_PROBLEM,
  MSK_RES_TRM_OBJECTIVE_RANGE,
  MSK_RES_TRM_STALL,
  MSK_RES_TRM_USER_CALLBACK,
  MSK_RES_WRN_ANA_ALMOST_INT_BOUNDS,
  MSK_RES_WRN_ANA_C_ZERO,
  MSK_RES_WRN_ANA_CLOSE_BOUNDS,
  MSK_RES_WRN_ANA_EMPTY_COLS,
  MSK_RES_WRN_ANA_LARGE_BOUNDS,
  MSK_RES_WRN_CONSTRUCT_INVALID_SOL_ITG,
  MSK_RES_WRN_CONSTRUCT_NO_SOL_ITG,
  MSK_RES_WRN_CONSTRUCT_SOLUTION_INFEAS,
  MSK_RES_WRN_DROPPED_NZ_QOBJ,
  MSK_RES_WRN_DUPLICATE_BARVARIABLE_NAMES,
  MSK_RES_WRN_DUPLICATE_CONE_NAMES,
  MSK_RES_WRN_DUPLICATE_CONSTRAINT_NAMES,
  MSK_RES_WRN_DUPLICATE_VARIABLE_NAMES,
  MSK_RES_WRN_ELIMINATOR_SPACE,
  MSK_RES_WRN_EMPTY_NAME,
  MSK_RES_WRN_IGNORE_INTEGER,
  MSK_RES_WRN_INCOMPLETE_LINEAR_DEPENDENCY_CHECK,
  MSK_RES_WRN_LARGE_AIJ,
  MSK_RES_WRN_LARGE_BOUND,
  MSK_RES_WRN_LARGE_CJ,
  MSK_RES_WRN_LARGE_CON_FX,
  MSK_RES_WRN_LARGE_LO_BOUND,
  MSK_RES_WRN_LARGE_UP_BOUND,
  MSK_RES_WRN_LICENSE_EXPIRE,
  MSK_RES_WRN_LICENSE_FEATURE_EXPIRE,
  MSK_RES_WRN_LICENSE_SERVER,
  MSK_RES_WRN_LP_DROP_VARIABLE,
  MSK_RES_WRN_LP_OLD_QUAD_FORMAT,
  MSK_RES_WRN_MIO_INFEASIBLE_FINAL,
  MSK_RES_WRN_MPS_SPLIT_BOU_VECTOR,
  MSK_RES_WRN_MPS_SPLIT_RAN_VECTOR,
  MSK_RES_WRN_MPS_SPLIT_RHS_VECTOR,
  MSK_RES_WRN_NAME_MAX_LEN,
  MSK_RES_WRN_NO_DUALIZER,
  MSK_RES_WRN_NO_GLOBAL_OPTIMIZER,
  MSK_RES_WRN_NO_NONLINEAR_FUNCTION_WRITE,
  MSK_RES_WRN_NZ_IN_UPR_TRI,
  MSK_RES_WRN_OPEN_PARAM_FILE,
  MSK_RES_WRN_PARAM_IGNORED_CMIO,
  MSK_RES_WRN_PARAM_NAME_DOU,
  MSK_RES_WRN_PARAM_NAME_INT,
  MSK_RES_WRN_PARAM_NAME_STR,
  MSK_RES_WRN_PARAM_STR_VALUE,
  MSK_RES_WRN_PRESOLVE_OUTOFSPACE,
  MSK_RES_WRN_QUAD_CONES_WITH_ROOT_FIXED_AT_ZERO,
  MSK_RES_WRN_RQUAD_CONES_WITH_ROOT_FIXED_AT_ZERO,
  MSK_RES_WRN_SOL_FILE_IGNORED_CON,
  MSK_RES_WRN_SOL_FILE_IGNORED_VAR,
  MSK_RES_WRN_SOL_FILTER,
  MSK_RES_WRN_SPAR_MAX_LEN,
  MSK_RES_WRN_TOO_FEW_BASIS_VARS,
  MSK_RES_WRN_TOO_MANY_BASIS_VARS,
  MSK_RES_WRN_TOO_MANY_THREADS_CONCURRENT,
  MSK_RES_WRN_UNDEF_SOL_FILE_NAME,
  MSK_RES_WRN_USING_GENERIC_NAMES,
  MSK_RES_WRN_WRITE_CHANGED_NAMES,
  MSK_RES_WRN_WRITE_DISCARDED_CFIX,
  MSK_RES_WRN_ZERO_AIJ,
  MSK_RES_WRN_ZEROS_IN_SPARSE_COL,
  MSK_RES_WRN_ZEROS_IN_SPARSE_ROW,
  MSK_MIO_NODE_SELECTION_BEST,
  MSK_MIO_NODE_SELECTION_FIRST,
  MSK_MIO_NODE_SELECTION_FREE,
  MSK_MIO_NODE_SELECTION_HYBRID,
  MSK_MIO_NODE_SELECTION_PSEUDO,
  MSK_MIO_NODE_SELECTION_WORST,
  MSK_MIO_NODE_SELECTION_BEGIN,
  MSK_MIO_NODE_SELECTION_END,
  MSK_TRANSPOSE_NO,
  MSK_TRANSPOSE_YES,
  MSK_TRANSPOSE_BEGIN,
  MSK_TRANSPOSE_END,
  MSK_OFF,
  MSK_ON,
  MSK_SIM_DEGEN_AGGRESSIVE,
  MSK_SIM_DEGEN_FREE,
  MSK_SIM_DEGEN_MINIMUM,
  MSK_SIM_DEGEN_MODERATE,
  MSK_SIM_DEGEN_NONE,
  MSK_SIM_DEGEN_BEGIN,
  MSK_SIM_DEGEN_END,
  MSK_DATA_FORMAT_CB,
  MSK_DATA_FORMAT_EXTENSION,
  MSK_DATA_FORMAT_FREE_MPS,
  MSK_DATA_FORMAT_LP,
  MSK_DATA_FORMAT_MPS,
  MSK_DATA_FORMAT_OP,
  MSK_DATA_FORMAT_TASK,
  MSK_DATA_FORMAT_XML,
  MSK_DATA_FORMAT_BEGIN,
  MSK_DATA_FORMAT_END,
  MSK_ORDER_METHOD_APPMINLOC,
  MSK_ORDER_METHOD_EXPERIMENTAL,
  MSK_ORDER_METHOD_FORCE_GRAPHPAR,
  MSK_ORDER_METHOD_FREE,
  MSK_ORDER_METHOD_NONE,
  MSK_ORDER_METHOD_TRY_GRAPHPAR,
  MSK_ORDER_METHOD_BEGIN,
  MSK_ORDER_METHOD_END,
  MSK_PROBTYPE_CONIC,
  MSK_PROBTYPE_GECO,
  MSK_PROBTYPE_LO,
  MSK_PROBTYPE_MIXED,
  MSK_PROBTYPE_QCQO,
  MSK_PROBTYPE_QO,
  MSK_PROBTYPE_BEGIN,
  MSK_PROBTYPE_END,
  MSK_INF_DOU_TYPE,
  MSK_INF_INT_TYPE,
  MSK_INF_LINT_TYPE,
  MSK_INF_BEGIN,
  MSK_INF_END,
  MSK_DPAR_ANA_SOL_INFEAS_TOL,
  MSK_DPAR_BASIS_REL_TOL_S,
  MSK_DPAR_BASIS_TOL_S,
  MSK_DPAR_BASIS_TOL_X,
  MSK_DPAR_CHECK_CONVEXITY_REL_TOL,
  MSK_DPAR_DATA_TOL_AIJ,
  MSK_DPAR_DATA_TOL_AIJ_HUGE,
  MSK_DPAR_DATA_TOL_AIJ_LARGE,
  MSK_DPAR_DATA_TOL_BOUND_INF,
  MSK_DPAR_DATA_TOL_BOUND_WRN,
  MSK_DPAR_DATA_TOL_C_HUGE,
  MSK_DPAR_DATA_TOL_CJ_LARGE,
  MSK_DPAR_DATA_TOL_QIJ,
  MSK_DPAR_DATA_TOL_X,
  MSK_DPAR_FEASREPAIR_TOL,
  MSK_DPAR_INTPNT_CO_TOL_DFEAS,
  MSK_DPAR_INTPNT_CO_TOL_INFEAS,
  MSK_DPAR_INTPNT_CO_TOL_MU_RED,
  MSK_DPAR_INTPNT_CO_TOL_NEAR_REL,
  MSK_DPAR_INTPNT_CO_TOL_PFEAS,
  MSK_DPAR_INTPNT_CO_TOL_REL_GAP,
  MSK_DPAR_INTPNT_NL_MERIT_BAL,
  MSK_DPAR_INTPNT_NL_TOL_DFEAS,
  MSK_DPAR_INTPNT_NL_TOL_MU_RED,
  MSK_DPAR_INTPNT_NL_TOL_NEAR_REL,
  MSK_DPAR_INTPNT_NL_TOL_PFEAS,
  MSK_DPAR_INTPNT_NL_TOL_REL_GAP,
  MSK_DPAR_INTPNT_NL_TOL_REL_STEP,
  MSK_DPAR_INTPNT_TOL_DFEAS,
  MSK_DPAR_INTPNT_TOL_DSAFE,
  MSK_DPAR_INTPNT_TOL_INFEAS,
  MSK_DPAR_INTPNT_TOL_MU_RED,
  MSK_DPAR_INTPNT_TOL_PATH,
  MSK_DPAR_INTPNT_TOL_PFEAS,
  MSK_DPAR_INTPNT_TOL_PSAFE,
  MSK_DPAR_INTPNT_TOL_REL_GAP,
  MSK_DPAR_INTPNT_TOL_REL_STEP,
  MSK_DPAR_INTPNT_TOL_STEP_SIZE,
  MSK_DPAR_LOWER_OBJ_CUT,
  MSK_DPAR_LOWER_OBJ_CUT_FINITE_TRH,
  MSK_DPAR_MIO_DISABLE_TERM_TIME,
  MSK_DPAR_MIO_HEURISTIC_TIME,
  MSK_DPAR_MIO_MAX_TIME,
  MSK_DPAR_MIO_MAX_TIME_APRX_OPT,
  MSK_DPAR_MIO_NEAR_TOL_ABS_GAP,
  MSK_DPAR_MIO_NEAR_TOL_REL_GAP,
  MSK_DPAR_MIO_REL_ADD_CUT_LIMITED,
  MSK_DPAR_MIO_REL_GAP_CONST,
  MSK_DPAR_MIO_TOL_ABS_GAP,
  MSK_DPAR_MIO_TOL_ABS_RELAX_INT,
  MSK_DPAR_MIO_TOL_FEAS,
  MSK_DPAR_MIO_TOL_MAX_CUT_FRAC_RHS,
  MSK_DPAR_MIO_TOL_MIN_CUT_FRAC_RHS,
  MSK_DPAR_MIO_TOL_REL_DUAL_BOUND_IMPROVEMENT,
  MSK_DPAR_MIO_TOL_REL_GAP,
  MSK_DPAR_MIO_TOL_REL_RELAX_INT,
  MSK_DPAR_MIO_TOL_X,
  MSK_DPAR_NONCONVEX_TOL_FEAS,
  MSK_DPAR_NONCONVEX_TOL_OPT,
  MSK_DPAR_OPTIMIZER_MAX_TIME,
  MSK_DPAR_PRESOLVE_TOL_ABS_LINDEP,
  MSK_DPAR_PRESOLVE_TOL_AIJ,
  MSK_DPAR_PRESOLVE_TOL_REL_LINDEP,
  MSK_DPAR_PRESOLVE_TOL_S,
  MSK_DPAR_PRESOLVE_TOL_X,
  MSK_DPAR_QCQO_REFORMULATE_REL_DROP_TOL,
  MSK_DPAR_SIM_LU_TOL_REL_PIV,
  MSK_DPAR_SIMPLEX_ABS_TOL_PIV,
  MSK_DPAR_UPPER_OBJ_CUT,
  MSK_DPAR_UPPER_OBJ_CUT_FINITE_TRH,
  MSK_DPAR_BEGIN,
  MSK_DPAR_END,
  MSK_SIM_EXPLOIT_DUPVEC_FREE,
  MSK_SIM_EXPLOIT_DUPVEC_OFF,
  MSK_SIM_EXPLOIT_DUPVEC_ON,
  MSK_SIM_EXPLOIT_DUPVEC_BEGIN,
  MSK_SIM_EXPLOIT_DUPVEC_END,
  MSK_COMPRESS_FREE,
  MSK_COMPRESS_GZIP,
  MSK_COMPRESS_NONE,
  MSK_COMPRESS_BEGIN,
  MSK_COMPRESS_END,
  MSK_NAME_TYPE_GEN,
  MSK_NAME_TYPE_LP,
  MSK_NAME_TYPE_MPS,
  MSK_NAME_TYPE_BEGIN,
  MSK_NAME_TYPE_END,
  MSK_MPS_FORMAT_FREE,
  MSK_MPS_FORMAT_RELAXED,
  MSK_MPS_FORMAT_STRICT,
  MSK_MPS_FORMAT_BEGIN,
  MSK_MPS_FORMAT_END,
  MSK_VAR_TYPE_CONT,
  MSK_VAR_TYPE_INT,
  MSK_VAR_BEGIN,
  MSK_VAR_END,
  MSK_CHECK_CONVEXITY_FULL,
  MSK_CHECK_CONVEXITY_NONE,
  MSK_CHECK_CONVEXITY_SIMPLE,
  MSK_CHECK_CONVEXITY_BEGIN,
  MSK_CHECK_CONVEXITY_END,
  MSK_LANG_DAN,
  MSK_LANG_ENG,
  MSK_LANG_BEGIN,
  MSK_LANG_END,
  MSK_STARTING_POINT_CONSTANT,
  MSK_STARTING_POINT_FREE,
  MSK_STARTING_POINT_GUESS,
  MSK_STARTING_POINT_SATISFY_BOUNDS,
  MSK_STARTING_POINT_BEGIN,
  MSK_STARTING_POINT_END,
  MSK_SOL_BAS,
  MSK_SOL_ITG,
  MSK_SOL_ITR,
  MSK_SOL_BEGIN,
  MSK_SOL_END,
  MSK_SCALING_METHOD_FREE,
  MSK_SCALING_METHOD_POW2,
  MSK_SCALING_METHOD_BEGIN,
  MSK_SCALING_METHOD_END,
  MSK_LICENSE_BUFFER_LENGTH,
  MSK_MAX_STR_LEN,
  MSK_SK_BAS,
  MSK_SK_FIX,
  MSK_SK_INF,
  MSK_SK_LOW,
  MSK_SK_SUPBAS,
  MSK_SK_UNK,
  MSK_SK_UPR,
  MSK_SK_BEGIN,
  MSK_SK_END,
  MSK_SIM_REFORMULATION_AGGRESSIVE,
  MSK_SIM_REFORMULATION_FREE,
  MSK_SIM_REFORMULATION_OFF,
  MSK_SIM_REFORMULATION_ON,
  MSK_SIM_REFORMULATION_BEGIN,
  MSK_SIM_REFORMULATION_END,
  MSK_IINF_ANA_PRO_NUM_CON,
  MSK_IINF_ANA_PRO_NUM_CON_EQ,
  MSK_IINF_ANA_PRO_NUM_CON_FR,
  MSK_IINF_ANA_PRO_NUM_CON_LO,
  MSK_IINF_ANA_PRO_NUM_CON_RA,
  MSK_IINF_ANA_PRO_NUM_CON_UP,
  MSK_IINF_ANA_PRO_NUM_VAR,
  MSK_IINF_ANA_PRO_NUM_VAR_BIN,
  MSK_IINF_ANA_PRO_NUM_VAR_CONT,
  MSK_IINF_ANA_PRO_NUM_VAR_EQ,
  MSK_IINF_ANA_PRO_NUM_VAR_FR,
  MSK_IINF_ANA_PRO_NUM_VAR_INT,
  MSK_IINF_ANA_PRO_NUM_VAR_LO,
  MSK_IINF_ANA_PRO_NUM_VAR_RA,
  MSK_IINF_ANA_PRO_NUM_VAR_UP,
  MSK_IINF_CONCURRENT_FASTEST_OPTIMIZER,
  MSK_IINF_INTPNT_FACTOR_DIM_DENSE,
  MSK_IINF_INTPNT_ITER,
  MSK_IINF_INTPNT_NUM_THREADS,
  MSK_IINF_INTPNT_SOLVE_DUAL,
  MSK_IINF_MIO_CONSTRUCT_NUM_ROUNDINGS,
  MSK_IINF_MIO_CONSTRUCT_SOLUTION,
  MSK_IINF_MIO_INITIAL_SOLUTION,
  MSK_IINF_MIO_NUM_ACTIVE_NODES,
  MSK_IINF_MIO_NUM_BASIS_CUTS,
  MSK_IINF_MIO_NUM_BRANCH,
  MSK_IINF_MIO_NUM_CARDGUB_CUTS,
  MSK_IINF_MIO_NUM_CLIQUE_CUTS,
  MSK_IINF_MIO_NUM_COEF_REDC_CUTS,
  MSK_IINF_MIO_NUM_CONTRA_CUTS,
  MSK_IINF_MIO_NUM_DISAGG_CUTS,
  MSK_IINF_MIO_NUM_FLOW_COVER_CUTS,
  MSK_IINF_MIO_NUM_GCD_CUTS,
  MSK_IINF_MIO_NUM_GOMORY_CUTS,
  MSK_IINF_MIO_NUM_GUB_COVER_CUTS,
  MSK_IINF_MIO_NUM_INT_SOLUTIONS,
  MSK_IINF_MIO_NUM_KNAPSUR_COVER_CUTS,
  MSK_IINF_MIO_NUM_LATTICE_CUTS,
  MSK_IINF_MIO_NUM_LIFT_CUTS,
  MSK_IINF_MIO_NUM_OBJ_CUTS,
  MSK_IINF_MIO_NUM_PLAN_LOC_CUTS,
  MSK_IINF_MIO_NUM_RELAX,
  MSK_IINF_MIO_NUMCON,
  MSK_IINF_MIO_NUMINT,
  MSK_IINF_MIO_NUMVAR,
  MSK_IINF_MIO_OBJ_BOUND_DEFINED,
  MSK_IINF_MIO_TOTAL_NUM_CUTS,
  MSK_IINF_MIO_USER_OBJ_CUT,
  MSK_IINF_OPT_NUMCON,
  MSK_IINF_OPT_NUMVAR,
  MSK_IINF_OPTIMIZE_RESPONSE,
  MSK_IINF_RD_NUMBARVAR,
  MSK_IINF_RD_NUMCON,
  MSK_IINF_RD_NUMCONE,
  MSK_IINF_RD_NUMINTVAR,
  MSK_IINF_RD_NUMQ,
  MSK_IINF_RD_NUMVAR,
  MSK_IINF_RD_PROTYPE,
  MSK_IINF_SIM_DUAL_DEG_ITER,
  MSK_IINF_SIM_DUAL_HOTSTART,
  MSK_IINF_SIM_DUAL_HOTSTART_LU,
  MSK_IINF_SIM_DUAL_INF_ITER,
  MSK_IINF_SIM_DUAL_ITER,
  MSK_IINF_SIM_NETWORK_DUAL_DEG_ITER,
  MSK_IINF_SIM_NETWORK_DUAL_HOTSTART,
  MSK_IINF_SIM_NETWORK_DUAL_HOTSTART_LU,
  MSK_IINF_SIM_NETWORK_DUAL_INF_ITER,
  MSK_IINF_SIM_NETWORK_DUAL_ITER,
  MSK_IINF_SIM_NETWORK_PRIMAL_DEG_ITER,
  MSK_IINF_SIM_NETWORK_PRIMAL_HOTSTART,
  MSK_IINF_SIM_NETWORK_PRIMAL_HOTSTART_LU,
  MSK_IINF_SIM_NETWORK_PRIMAL_INF_ITER,
  MSK_IINF_SIM_NETWORK_PRIMAL_ITER,
  MSK_IINF_SIM_NUMCON,
  MSK_IINF_SIM_NUMVAR,
  MSK_IINF_SIM_PRIMAL_DEG_ITER,
  MSK_IINF_SIM_PRIMAL_DUAL_DEG_ITER,
  MSK_IINF_SIM_PRIMAL_DUAL_HOTSTART,
  MSK_IINF_SIM_PRIMAL_DUAL_HOTSTART_LU,
  MSK_IINF_SIM_PRIMAL_DUAL_INF_ITER,
  MSK_IINF_SIM_PRIMAL_DUAL_ITER,
  MSK_IINF_SIM_PRIMAL_HOTSTART,
  MSK_IINF_SIM_PRIMAL_HOTSTART_LU,
  MSK_IINF_SIM_PRIMAL_INF_ITER,
  MSK_IINF_SIM_PRIMAL_ITER,
  MSK_IINF_SIM_SOLVE_DUAL,
  MSK_IINF_SOL_BAS_PROSTA,
  MSK_IINF_SOL_BAS_SOLSTA,
  MSK_IINF_SOL_INT_PROSTA,
  MSK_IINF_SOL_INT_SOLSTA,
  MSK_IINF_SOL_ITG_PROSTA,
  MSK_IINF_SOL_ITG_SOLSTA,
  MSK_IINF_SOL_ITR_PROSTA,
  MSK_IINF_SOL_ITR_SOLSTA,
  MSK_IINF_STO_NUM_A_CACHE_FLUSHES,
  MSK_IINF_STO_NUM_A_REALLOC,
  MSK_IINF_STO_NUM_A_TRANSPOSES,
  MSK_IINF_BEGIN,
  MSK_IINF_END,
  MSK_WRITE_XML_MODE_COL,
  MSK_WRITE_XML_MODE_ROW,
  MSK_WRITE_XML_MODE_BEGIN,
  MSK_WRITE_XML_MODE_END,
  MSK_OPTIMIZER_CONCURRENT,
  MSK_OPTIMIZER_CONIC,
  MSK_OPTIMIZER_DUAL_SIMPLEX,
  MSK_OPTIMIZER_FREE,
  MSK_OPTIMIZER_FREE_SIMPLEX,
  MSK_OPTIMIZER_INTPNT,
  MSK_OPTIMIZER_MIXED_INT,
  MSK_OPTIMIZER_MIXED_INT_CONIC,
  MSK_OPTIMIZER_NETWORK_PRIMAL_SIMPLEX,
  MSK_OPTIMIZER_NONCONVEX,
  MSK_OPTIMIZER_PRIMAL_DUAL_SIMPLEX,
  MSK_OPTIMIZER_PRIMAL_SIMPLEX,
  MSK_OPTIMIZER_BEGIN,
  MSK_OPTIMIZER_END,
  MSK_PRESOLVE_MODE_FREE,
  MSK_PRESOLVE_MODE_OFF,
  MSK_PRESOLVE_MODE_ON,
  MSK_PRESOLVE_MODE_BEGIN,
  MSK_PRESOLVE_MODE_END,
  MSK_MIO_CONT_SOL_ITG,
  MSK_MIO_CONT_SOL_ITG_REL,
  MSK_MIO_CONT_SOL_NONE,
  MSK_MIO_CONT_SOL_ROOT,
  MSK_MIO_CONT_SOL_BEGIN,
  MSK_MIO_CONT_SOL_END

# enum solveform
MSK_SOLVE_DUAL = int32(2)
MSK_SOLVE_FREE = int32(0)
MSK_SOLVE_PRIMAL = int32(1)

  MSK_SOLVE_BEGIN = int32(0)
  MSK_SOLVE_END   = int32(3)

# enum problemitem
MSK_PI_CON = int32(1)
MSK_PI_CONE = int32(2)
MSK_PI_VAR = int32(0)

  MSK_PI_BEGIN = int32(0)
  MSK_PI_END   = int32(3)

# enum accmode
MSK_ACC_CON = int32(1)
MSK_ACC_VAR = int32(0)

  MSK_ACC_BEGIN = int32(0)
  MSK_ACC_END   = int32(2)

# enum sensitivitytype
MSK_SENSITIVITY_TYPE_BASIS = int32(0)
MSK_SENSITIVITY_TYPE_OPTIMAL_PARTITION = int32(1)

  MSK_SENSITIVITY_TYPE_BEGIN = int32(0)
  MSK_SENSITIVITY_TYPE_END   = int32(2)

# enum uplo
MSK_UPLO_LO = int32(0)
MSK_UPLO_UP = int32(1)

  MSK_UPLO_BEGIN = int32(0)
  MSK_UPLO_END   = int32(2)

# enum intpnthotstart
MSK_INTPNT_HOTSTART_DUAL = int32(2)
MSK_INTPNT_HOTSTART_NONE = int32(0)
MSK_INTPNT_HOTSTART_PRIMAL = int32(1)
MSK_INTPNT_HOTSTART_PRIMAL_DUAL = int32(3)

  MSK_INTPNT_HOTSTART_BEGIN = int32(0)
  MSK_INTPNT_HOTSTART_END   = int32(4)

# enum sparam
MSK_SPAR_BAS_SOL_FILE_NAME = int32(0)
MSK_SPAR_DATA_FILE_NAME = int32(1)
MSK_SPAR_DEBUG_FILE_NAME = int32(2)
MSK_SPAR_FEASREPAIR_NAME_PREFIX = int32(3)
MSK_SPAR_FEASREPAIR_NAME_SEPARATOR = int32(4)
MSK_SPAR_FEASREPAIR_NAME_WSUMVIOL = int32(5)
MSK_SPAR_INT_SOL_FILE_NAME = int32(6)
MSK_SPAR_ITR_SOL_FILE_NAME = int32(7)
MSK_SPAR_MIO_DEBUG_STRING = int32(8)
MSK_SPAR_PARAM_COMMENT_SIGN = int32(9)
MSK_SPAR_PARAM_READ_FILE_NAME = int32(10)
MSK_SPAR_PARAM_WRITE_FILE_NAME = int32(11)
MSK_SPAR_READ_MPS_BOU_NAME = int32(12)
MSK_SPAR_READ_MPS_OBJ_NAME = int32(13)
MSK_SPAR_READ_MPS_RAN_NAME = int32(14)
MSK_SPAR_READ_MPS_RHS_NAME = int32(15)
MSK_SPAR_SENSITIVITY_FILE_NAME = int32(16)
MSK_SPAR_SENSITIVITY_RES_FILE_NAME = int32(17)
MSK_SPAR_SOL_FILTER_XC_LOW = int32(18)
MSK_SPAR_SOL_FILTER_XC_UPR = int32(19)
MSK_SPAR_SOL_FILTER_XX_LOW = int32(20)
MSK_SPAR_SOL_FILTER_XX_UPR = int32(21)
MSK_SPAR_STAT_FILE_NAME = int32(22)
MSK_SPAR_STAT_KEY = int32(23)
MSK_SPAR_STAT_NAME = int32(24)
MSK_SPAR_WRITE_LP_GEN_VAR_NAME = int32(25)

  MSK_SPAR_BEGIN = int32(0)
  MSK_SPAR_END   = int32(26)

# enum iparam
MSK_IPAR_ALLOC_ADD_QNZ = int32(0)
MSK_IPAR_ANA_SOL_BASIS = int32(1)
MSK_IPAR_ANA_SOL_PRINT_VIOLATED = int32(2)
MSK_IPAR_AUTO_SORT_A_BEFORE_OPT = int32(3)
MSK_IPAR_AUTO_UPDATE_SOL_INFO = int32(4)
MSK_IPAR_BASIS_SOLVE_USE_PLUS_ONE = int32(5)
MSK_IPAR_BI_CLEAN_OPTIMIZER = int32(6)
MSK_IPAR_BI_IGNORE_MAX_ITER = int32(7)
MSK_IPAR_BI_IGNORE_NUM_ERROR = int32(8)
MSK_IPAR_BI_MAX_ITERATIONS = int32(9)
MSK_IPAR_CACHE_LICENSE = int32(10)
MSK_IPAR_CHECK_CONVEXITY = int32(11)
MSK_IPAR_COMPRESS_STATFILE = int32(12)
MSK_IPAR_CONCURRENT_NUM_OPTIMIZERS = int32(13)
MSK_IPAR_CONCURRENT_PRIORITY_DUAL_SIMPLEX = int32(14)
MSK_IPAR_CONCURRENT_PRIORITY_FREE_SIMPLEX = int32(15)
MSK_IPAR_CONCURRENT_PRIORITY_INTPNT = int32(16)
MSK_IPAR_CONCURRENT_PRIORITY_PRIMAL_SIMPLEX = int32(17)
MSK_IPAR_FEASREPAIR_OPTIMIZE = int32(18)
MSK_IPAR_INFEAS_GENERIC_NAMES = int32(19)
MSK_IPAR_INFEAS_PREFER_PRIMAL = int32(20)
MSK_IPAR_INFEAS_REPORT_AUTO = int32(21)
MSK_IPAR_INFEAS_REPORT_LEVEL = int32(22)
MSK_IPAR_INTPNT_BASIS = int32(23)
MSK_IPAR_INTPNT_DIFF_STEP = int32(24)
MSK_IPAR_INTPNT_FACTOR_DEBUG_LVL = int32(25)
MSK_IPAR_INTPNT_FACTOR_METHOD = int32(26)
MSK_IPAR_INTPNT_HOTSTART = int32(27)
MSK_IPAR_INTPNT_MAX_ITERATIONS = int32(28)
MSK_IPAR_INTPNT_MAX_NUM_COR = int32(29)
MSK_IPAR_INTPNT_MAX_NUM_REFINEMENT_STEPS = int32(30)
MSK_IPAR_INTPNT_OFF_COL_TRH = int32(31)
MSK_IPAR_INTPNT_ORDER_METHOD = int32(32)
MSK_IPAR_INTPNT_REGULARIZATION_USE = int32(33)
MSK_IPAR_INTPNT_SCALING = int32(34)
MSK_IPAR_INTPNT_SOLVE_FORM = int32(35)
MSK_IPAR_INTPNT_STARTING_POINT = int32(36)
MSK_IPAR_LIC_TRH_EXPIRY_WRN = int32(37)
MSK_IPAR_LICENSE_DEBUG = int32(38)
MSK_IPAR_LICENSE_PAUSE_TIME = int32(39)
MSK_IPAR_LICENSE_SUPPRESS_EXPIRE_WRNS = int32(40)
MSK_IPAR_LICENSE_WAIT = int32(41)
MSK_IPAR_LOG = int32(42)
MSK_IPAR_LOG_BI = int32(43)
MSK_IPAR_LOG_BI_FREQ = int32(44)
MSK_IPAR_LOG_CHECK_CONVEXITY = int32(45)
MSK_IPAR_LOG_CONCURRENT = int32(46)
MSK_IPAR_LOG_CUT_SECOND_OPT = int32(47)
MSK_IPAR_LOG_EXPAND = int32(48)
MSK_IPAR_LOG_FACTOR = int32(49)
MSK_IPAR_LOG_FEAS_REPAIR = int32(50)
MSK_IPAR_LOG_FILE = int32(51)
MSK_IPAR_LOG_HEAD = int32(52)
MSK_IPAR_LOG_INFEAS_ANA = int32(53)
MSK_IPAR_LOG_INTPNT = int32(54)
MSK_IPAR_LOG_MIO = int32(55)
MSK_IPAR_LOG_MIO_FREQ = int32(56)
MSK_IPAR_LOG_NONCONVEX = int32(57)
MSK_IPAR_LOG_OPTIMIZER = int32(58)
MSK_IPAR_LOG_ORDER = int32(59)
MSK_IPAR_LOG_PARAM = int32(60)
MSK_IPAR_LOG_PRESOLVE = int32(61)
MSK_IPAR_LOG_RESPONSE = int32(62)
MSK_IPAR_LOG_SENSITIVITY = int32(63)
MSK_IPAR_LOG_SENSITIVITY_OPT = int32(64)
MSK_IPAR_LOG_SIM = int32(65)
MSK_IPAR_LOG_SIM_FREQ = int32(66)
MSK_IPAR_LOG_SIM_MINOR = int32(67)
MSK_IPAR_LOG_SIM_NETWORK_FREQ = int32(68)
MSK_IPAR_LOG_STORAGE = int32(69)
MSK_IPAR_MAX_NUM_WARNINGS = int32(70)
MSK_IPAR_MIO_BRANCH_DIR = int32(71)
MSK_IPAR_MIO_BRANCH_PRIORITIES_USE = int32(72)
MSK_IPAR_MIO_CONSTRUCT_SOL = int32(73)
MSK_IPAR_MIO_CONT_SOL = int32(74)
MSK_IPAR_MIO_CUT_CG = int32(75)
MSK_IPAR_MIO_CUT_CMIR = int32(76)
MSK_IPAR_MIO_CUT_LEVEL_ROOT = int32(77)
MSK_IPAR_MIO_CUT_LEVEL_TREE = int32(78)
MSK_IPAR_MIO_FEASPUMP_LEVEL = int32(79)
MSK_IPAR_MIO_HEURISTIC_LEVEL = int32(80)
MSK_IPAR_MIO_HOTSTART = int32(81)
MSK_IPAR_MIO_KEEP_BASIS = int32(82)
MSK_IPAR_MIO_LOCAL_BRANCH_NUMBER = int32(83)
MSK_IPAR_MIO_MAX_NUM_BRANCHES = int32(84)
MSK_IPAR_MIO_MAX_NUM_RELAXS = int32(85)
MSK_IPAR_MIO_MAX_NUM_SOLUTIONS = int32(86)
MSK_IPAR_MIO_MODE = int32(87)
MSK_IPAR_MIO_MT_USER_CB = int32(88)
MSK_IPAR_MIO_NODE_OPTIMIZER = int32(89)
MSK_IPAR_MIO_NODE_SELECTION = int32(90)
MSK_IPAR_MIO_OPTIMIZER_MODE = int32(91)
MSK_IPAR_MIO_PRESOLVE_AGGREGATE = int32(92)
MSK_IPAR_MIO_PRESOLVE_PROBING = int32(93)
MSK_IPAR_MIO_PRESOLVE_USE = int32(94)
MSK_IPAR_MIO_PROBING_LEVEL = int32(95)
MSK_IPAR_MIO_RINS_MAX_NODES = int32(96)
MSK_IPAR_MIO_ROOT_OPTIMIZER = int32(97)
MSK_IPAR_MIO_STRONG_BRANCH = int32(98)
MSK_IPAR_MIO_USE_MULTITHREADED_OPTIMIZER = int32(99)
MSK_IPAR_MT_SPINCOUNT = int32(100)
MSK_IPAR_NONCONVEX_MAX_ITERATIONS = int32(101)
MSK_IPAR_NUM_THREADS = int32(102)
MSK_IPAR_OPF_MAX_TERMS_PER_LINE = int32(103)
MSK_IPAR_OPF_WRITE_HEADER = int32(104)
MSK_IPAR_OPF_WRITE_HINTS = int32(105)
MSK_IPAR_OPF_WRITE_PARAMETERS = int32(106)
MSK_IPAR_OPF_WRITE_PROBLEM = int32(107)
MSK_IPAR_OPF_WRITE_SOL_BAS = int32(108)
MSK_IPAR_OPF_WRITE_SOL_ITG = int32(109)
MSK_IPAR_OPF_WRITE_SOL_ITR = int32(110)
MSK_IPAR_OPF_WRITE_SOLUTIONS = int32(111)
MSK_IPAR_OPTIMIZER = int32(112)
MSK_IPAR_PARAM_READ_CASE_NAME = int32(113)
MSK_IPAR_PARAM_READ_IGN_ERROR = int32(114)
MSK_IPAR_PRESOLVE_ELIM_FILL = int32(115)
MSK_IPAR_PRESOLVE_ELIMINATOR_MAX_NUM_TRIES = int32(116)
MSK_IPAR_PRESOLVE_ELIMINATOR_USE = int32(117)
MSK_IPAR_PRESOLVE_LEVEL = int32(118)
MSK_IPAR_PRESOLVE_LINDEP_ABS_WORK_TRH = int32(119)
MSK_IPAR_PRESOLVE_LINDEP_REL_WORK_TRH = int32(120)
MSK_IPAR_PRESOLVE_LINDEP_USE = int32(121)
MSK_IPAR_PRESOLVE_MAX_NUM_REDUCTIONS = int32(122)
MSK_IPAR_PRESOLVE_USE = int32(123)
MSK_IPAR_PRIMAL_REPAIR_OPTIMIZER = int32(124)
MSK_IPAR_QO_SEPARABLE_REFORMULATION = int32(125)
MSK_IPAR_READ_ANZ = int32(126)
MSK_IPAR_READ_CON = int32(127)
MSK_IPAR_READ_CONE = int32(128)
MSK_IPAR_READ_DATA_COMPRESSED = int32(129)
MSK_IPAR_READ_DATA_FORMAT = int32(130)
MSK_IPAR_READ_DEBUG = int32(131)
MSK_IPAR_READ_KEEP_FREE_CON = int32(132)
MSK_IPAR_READ_LP_DROP_NEW_VARS_IN_BOU = int32(133)
MSK_IPAR_READ_LP_QUOTED_NAMES = int32(134)
MSK_IPAR_READ_MPS_FORMAT = int32(135)
MSK_IPAR_READ_MPS_KEEP_INT = int32(136)
MSK_IPAR_READ_MPS_OBJ_SENSE = int32(137)
MSK_IPAR_READ_MPS_RELAX = int32(138)
MSK_IPAR_READ_MPS_WIDTH = int32(139)
MSK_IPAR_READ_QNZ = int32(140)
MSK_IPAR_READ_TASK_IGNORE_PARAM = int32(141)
MSK_IPAR_READ_VAR = int32(142)
MSK_IPAR_SENSITIVITY_ALL = int32(143)
MSK_IPAR_SENSITIVITY_OPTIMIZER = int32(144)
MSK_IPAR_SENSITIVITY_TYPE = int32(145)
MSK_IPAR_SIM_BASIS_FACTOR_USE = int32(146)
MSK_IPAR_SIM_DEGEN = int32(147)
MSK_IPAR_SIM_DUAL_CRASH = int32(148)
MSK_IPAR_SIM_DUAL_PHASEONE_METHOD = int32(149)
MSK_IPAR_SIM_DUAL_RESTRICT_SELECTION = int32(150)
MSK_IPAR_SIM_DUAL_SELECTION = int32(151)
MSK_IPAR_SIM_EXPLOIT_DUPVEC = int32(152)
MSK_IPAR_SIM_HOTSTART = int32(153)
MSK_IPAR_SIM_HOTSTART_LU = int32(154)
MSK_IPAR_SIM_INTEGER = int32(155)
MSK_IPAR_SIM_MAX_ITERATIONS = int32(156)
MSK_IPAR_SIM_MAX_NUM_SETBACKS = int32(157)
MSK_IPAR_SIM_NON_SINGULAR = int32(158)
MSK_IPAR_SIM_PRIMAL_CRASH = int32(159)
MSK_IPAR_SIM_PRIMAL_PHASEONE_METHOD = int32(160)
MSK_IPAR_SIM_PRIMAL_RESTRICT_SELECTION = int32(161)
MSK_IPAR_SIM_PRIMAL_SELECTION = int32(162)
MSK_IPAR_SIM_REFACTOR_FREQ = int32(163)
MSK_IPAR_SIM_REFORMULATION = int32(164)
MSK_IPAR_SIM_SAVE_LU = int32(165)
MSK_IPAR_SIM_SCALING = int32(166)
MSK_IPAR_SIM_SCALING_METHOD = int32(167)
MSK_IPAR_SIM_SOLVE_FORM = int32(168)
MSK_IPAR_SIM_STABILITY_PRIORITY = int32(169)
MSK_IPAR_SIM_SWITCH_OPTIMIZER = int32(170)
MSK_IPAR_SOL_FILTER_KEEP_BASIC = int32(171)
MSK_IPAR_SOL_FILTER_KEEP_RANGED = int32(172)
MSK_IPAR_SOL_READ_NAME_WIDTH = int32(173)
MSK_IPAR_SOL_READ_WIDTH = int32(174)
MSK_IPAR_SOLUTION_CALLBACK = int32(175)
MSK_IPAR_TIMING_LEVEL = int32(176)
MSK_IPAR_WARNING_LEVEL = int32(177)
MSK_IPAR_WRITE_BAS_CONSTRAINTS = int32(178)
MSK_IPAR_WRITE_BAS_HEAD = int32(179)
MSK_IPAR_WRITE_BAS_VARIABLES = int32(180)
MSK_IPAR_WRITE_DATA_COMPRESSED = int32(181)
MSK_IPAR_WRITE_DATA_FORMAT = int32(182)
MSK_IPAR_WRITE_DATA_PARAM = int32(183)
MSK_IPAR_WRITE_FREE_CON = int32(184)
MSK_IPAR_WRITE_GENERIC_NAMES = int32(185)
MSK_IPAR_WRITE_GENERIC_NAMES_IO = int32(186)
MSK_IPAR_WRITE_IGNORE_INCOMPATIBLE_CONIC_ITEMS = int32(187)
MSK_IPAR_WRITE_IGNORE_INCOMPATIBLE_ITEMS = int32(188)
MSK_IPAR_WRITE_IGNORE_INCOMPATIBLE_NL_ITEMS = int32(189)
MSK_IPAR_WRITE_IGNORE_INCOMPATIBLE_PSD_ITEMS = int32(190)
MSK_IPAR_WRITE_INT_CONSTRAINTS = int32(191)
MSK_IPAR_WRITE_INT_HEAD = int32(192)
MSK_IPAR_WRITE_INT_VARIABLES = int32(193)
MSK_IPAR_WRITE_LP_LINE_WIDTH = int32(194)
MSK_IPAR_WRITE_LP_QUOTED_NAMES = int32(195)
MSK_IPAR_WRITE_LP_STRICT_FORMAT = int32(196)
MSK_IPAR_WRITE_LP_TERMS_PER_LINE = int32(197)
MSK_IPAR_WRITE_MPS_INT = int32(198)
MSK_IPAR_WRITE_PRECISION = int32(199)
MSK_IPAR_WRITE_SOL_BARVARIABLES = int32(200)
MSK_IPAR_WRITE_SOL_CONSTRAINTS = int32(201)
MSK_IPAR_WRITE_SOL_HEAD = int32(202)
MSK_IPAR_WRITE_SOL_IGNORE_INVALID_NAMES = int32(203)
MSK_IPAR_WRITE_SOL_VARIABLES = int32(204)
MSK_IPAR_WRITE_TASK_INC_SOL = int32(205)
MSK_IPAR_WRITE_XML_MODE = int32(206)

  MSK_IPAR_BEGIN = int32(0)
  MSK_IPAR_END   = int32(207)

# enum solsta
MSK_SOL_STA_DUAL_FEAS = int32(3)
MSK_SOL_STA_DUAL_INFEAS_CER = int32(6)
MSK_SOL_STA_INTEGER_OPTIMAL = int32(14)
MSK_SOL_STA_NEAR_DUAL_FEAS = int32(10)
MSK_SOL_STA_NEAR_DUAL_INFEAS_CER = int32(13)
MSK_SOL_STA_NEAR_INTEGER_OPTIMAL = int32(15)
MSK_SOL_STA_NEAR_OPTIMAL = int32(8)
MSK_SOL_STA_NEAR_PRIM_AND_DUAL_FEAS = int32(11)
MSK_SOL_STA_NEAR_PRIM_FEAS = int32(9)
MSK_SOL_STA_NEAR_PRIM_INFEAS_CER = int32(12)
MSK_SOL_STA_OPTIMAL = int32(1)
MSK_SOL_STA_PRIM_AND_DUAL_FEAS = int32(4)
MSK_SOL_STA_PRIM_FEAS = int32(2)
MSK_SOL_STA_PRIM_INFEAS_CER = int32(5)
MSK_SOL_STA_UNKNOWN = int32(0)

  MSK_SOL_STA_BEGIN = int32(0)
  MSK_SOL_STA_END   = int32(16)

# enum objsense
MSK_OBJECTIVE_SENSE_MAXIMIZE = int32(1)
MSK_OBJECTIVE_SENSE_MINIMIZE = int32(0)

  MSK_OBJECTIVE_SENSE_BEGIN = int32(0)
  MSK_OBJECTIVE_SENSE_END   = int32(2)

# enum solitem
MSK_SOL_ITEM_SLC = int32(3)
MSK_SOL_ITEM_SLX = int32(5)
MSK_SOL_ITEM_SNX = int32(7)
MSK_SOL_ITEM_SUC = int32(4)
MSK_SOL_ITEM_SUX = int32(6)
MSK_SOL_ITEM_XC = int32(0)
MSK_SOL_ITEM_XX = int32(1)
MSK_SOL_ITEM_Y = int32(2)

  MSK_SOL_ITEM_BEGIN = int32(0)
  MSK_SOL_ITEM_END   = int32(8)

# enum boundkey
MSK_BK_FR = int32(3)
MSK_BK_FX = int32(2)
MSK_BK_LO = int32(0)
MSK_BK_RA = int32(4)
MSK_BK_UP = int32(1)

  MSK_BK_BEGIN = int32(0)
  MSK_BK_END   = int32(5)

# enum basindtype
MSK_BI_ALWAYS = int32(1)
MSK_BI_IF_FEASIBLE = int32(3)
MSK_BI_NEVER = int32(0)
MSK_BI_NO_ERROR = int32(2)
MSK_BI_RESERVERED = int32(4)

  MSK_BI_BEGIN = int32(0)
  MSK_BI_END   = int32(5)

# enum branchdir
MSK_BRANCH_DIR_DOWN = int32(2)
MSK_BRANCH_DIR_FREE = int32(0)
MSK_BRANCH_DIR_UP = int32(1)

  MSK_BRANCH_DIR_BEGIN = int32(0)
  MSK_BRANCH_DIR_END   = int32(3)

# enum liinfitem
MSK_LIINF_BI_CLEAN_DUAL_DEG_ITER = int32(0)
MSK_LIINF_BI_CLEAN_DUAL_ITER = int32(1)
MSK_LIINF_BI_CLEAN_PRIMAL_DEG_ITER = int32(2)
MSK_LIINF_BI_CLEAN_PRIMAL_DUAL_DEG_ITER = int32(3)
MSK_LIINF_BI_CLEAN_PRIMAL_DUAL_ITER = int32(4)
MSK_LIINF_BI_CLEAN_PRIMAL_DUAL_SUB_ITER = int32(5)
MSK_LIINF_BI_CLEAN_PRIMAL_ITER = int32(6)
MSK_LIINF_BI_DUAL_ITER = int32(7)
MSK_LIINF_BI_PRIMAL_ITER = int32(8)
MSK_LIINF_INTPNT_FACTOR_NUM_NZ = int32(9)
MSK_LIINF_MIO_INTPNT_ITER = int32(10)
MSK_LIINF_MIO_SIMPLEX_ITER = int32(11)
MSK_LIINF_RD_NUMANZ = int32(12)
MSK_LIINF_RD_NUMQNZ = int32(13)

  MSK_LIINF_BEGIN = int32(0)
  MSK_LIINF_END   = int32(14)

# enum streamtype
MSK_STREAM_ERR = int32(2)
MSK_STREAM_LOG = int32(0)
MSK_STREAM_MSG = int32(1)
MSK_STREAM_WRN = int32(3)

  MSK_STREAM_BEGIN = int32(0)
  MSK_STREAM_END   = int32(4)

# enum simhotstart
MSK_SIM_HOTSTART_FREE = int32(1)
MSK_SIM_HOTSTART_NONE = int32(0)
MSK_SIM_HOTSTART_STATUS_KEYS = int32(2)

  MSK_SIM_HOTSTART_BEGIN = int32(0)
  MSK_SIM_HOTSTART_END   = int32(3)

# enum callbackcode
MSK_CALLBACK_BEGIN_BI = int32(0)
MSK_CALLBACK_BEGIN_CONCURRENT = int32(1)
MSK_CALLBACK_BEGIN_CONIC = int32(2)
MSK_CALLBACK_BEGIN_DUAL_BI = int32(3)
MSK_CALLBACK_BEGIN_DUAL_SENSITIVITY = int32(4)
MSK_CALLBACK_BEGIN_DUAL_SETUP_BI = int32(5)
MSK_CALLBACK_BEGIN_DUAL_SIMPLEX = int32(6)
MSK_CALLBACK_BEGIN_DUAL_SIMPLEX_BI = int32(7)
MSK_CALLBACK_BEGIN_FULL_CONVEXITY_CHECK = int32(8)
MSK_CALLBACK_BEGIN_INFEAS_ANA = int32(9)
MSK_CALLBACK_BEGIN_INTPNT = int32(10)
MSK_CALLBACK_BEGIN_LICENSE_WAIT = int32(11)
MSK_CALLBACK_BEGIN_MIO = int32(12)
MSK_CALLBACK_BEGIN_NETWORK_DUAL_SIMPLEX = int32(13)
MSK_CALLBACK_BEGIN_NETWORK_PRIMAL_SIMPLEX = int32(14)
MSK_CALLBACK_BEGIN_NETWORK_SIMPLEX = int32(15)
MSK_CALLBACK_BEGIN_NONCONVEX = int32(16)
MSK_CALLBACK_BEGIN_OPTIMIZER = int32(17)
MSK_CALLBACK_BEGIN_PRESOLVE = int32(18)
MSK_CALLBACK_BEGIN_PRIMAL_BI = int32(19)
MSK_CALLBACK_BEGIN_PRIMAL_DUAL_SIMPLEX = int32(20)
MSK_CALLBACK_BEGIN_PRIMAL_DUAL_SIMPLEX_BI = int32(21)
MSK_CALLBACK_BEGIN_PRIMAL_REPAIR = int32(22)
MSK_CALLBACK_BEGIN_PRIMAL_SENSITIVITY = int32(23)
MSK_CALLBACK_BEGIN_PRIMAL_SETUP_BI = int32(24)
MSK_CALLBACK_BEGIN_PRIMAL_SIMPLEX = int32(25)
MSK_CALLBACK_BEGIN_PRIMAL_SIMPLEX_BI = int32(26)
MSK_CALLBACK_BEGIN_QCQO_REFORMULATE = int32(27)
MSK_CALLBACK_BEGIN_READ = int32(28)
MSK_CALLBACK_BEGIN_SIMPLEX = int32(29)
MSK_CALLBACK_BEGIN_SIMPLEX_BI = int32(30)
MSK_CALLBACK_BEGIN_SIMPLEX_NETWORK_DETECT = int32(31)
MSK_CALLBACK_BEGIN_WRITE = int32(32)
MSK_CALLBACK_CONIC = int32(33)
MSK_CALLBACK_DUAL_SIMPLEX = int32(34)
MSK_CALLBACK_END_BI = int32(35)
MSK_CALLBACK_END_CONCURRENT = int32(36)
MSK_CALLBACK_END_CONIC = int32(37)
MSK_CALLBACK_END_DUAL_BI = int32(38)
MSK_CALLBACK_END_DUAL_SENSITIVITY = int32(39)
MSK_CALLBACK_END_DUAL_SETUP_BI = int32(40)
MSK_CALLBACK_END_DUAL_SIMPLEX = int32(41)
MSK_CALLBACK_END_DUAL_SIMPLEX_BI = int32(42)
MSK_CALLBACK_END_FULL_CONVEXITY_CHECK = int32(43)
MSK_CALLBACK_END_INFEAS_ANA = int32(44)
MSK_CALLBACK_END_INTPNT = int32(45)
MSK_CALLBACK_END_LICENSE_WAIT = int32(46)
MSK_CALLBACK_END_MIO = int32(47)
MSK_CALLBACK_END_NETWORK_DUAL_SIMPLEX = int32(48)
MSK_CALLBACK_END_NETWORK_PRIMAL_SIMPLEX = int32(49)
MSK_CALLBACK_END_NETWORK_SIMPLEX = int32(50)
MSK_CALLBACK_END_NONCONVEX = int32(51)
MSK_CALLBACK_END_OPTIMIZER = int32(52)
MSK_CALLBACK_END_PRESOLVE = int32(53)
MSK_CALLBACK_END_PRIMAL_BI = int32(54)
MSK_CALLBACK_END_PRIMAL_DUAL_SIMPLEX = int32(55)
MSK_CALLBACK_END_PRIMAL_DUAL_SIMPLEX_BI = int32(56)
MSK_CALLBACK_END_PRIMAL_REPAIR = int32(57)
MSK_CALLBACK_END_PRIMAL_SENSITIVITY = int32(58)
MSK_CALLBACK_END_PRIMAL_SETUP_BI = int32(59)
MSK_CALLBACK_END_PRIMAL_SIMPLEX = int32(60)
MSK_CALLBACK_END_PRIMAL_SIMPLEX_BI = int32(61)
MSK_CALLBACK_END_QCQO_REFORMULATE = int32(62)
MSK_CALLBACK_END_READ = int32(63)
MSK_CALLBACK_END_SIMPLEX = int32(64)
MSK_CALLBACK_END_SIMPLEX_BI = int32(65)
MSK_CALLBACK_END_SIMPLEX_NETWORK_DETECT = int32(66)
MSK_CALLBACK_END_WRITE = int32(67)
MSK_CALLBACK_IM_BI = int32(68)
MSK_CALLBACK_IM_CONIC = int32(69)
MSK_CALLBACK_IM_DUAL_BI = int32(70)
MSK_CALLBACK_IM_DUAL_SENSIVITY = int32(71)
MSK_CALLBACK_IM_DUAL_SIMPLEX = int32(72)
MSK_CALLBACK_IM_FULL_CONVEXITY_CHECK = int32(73)
MSK_CALLBACK_IM_INTPNT = int32(74)
MSK_CALLBACK_IM_LICENSE_WAIT = int32(75)
MSK_CALLBACK_IM_LU = int32(76)
MSK_CALLBACK_IM_MIO = int32(77)
MSK_CALLBACK_IM_MIO_DUAL_SIMPLEX = int32(78)
MSK_CALLBACK_IM_MIO_INTPNT = int32(79)
MSK_CALLBACK_IM_MIO_PRESOLVE = int32(80)
MSK_CALLBACK_IM_MIO_PRIMAL_SIMPLEX = int32(81)
MSK_CALLBACK_IM_NETWORK_DUAL_SIMPLEX = int32(82)
MSK_CALLBACK_IM_NETWORK_PRIMAL_SIMPLEX = int32(83)
MSK_CALLBACK_IM_NONCONVEX = int32(84)
MSK_CALLBACK_IM_ORDER = int32(85)
MSK_CALLBACK_IM_PRESOLVE = int32(86)
MSK_CALLBACK_IM_PRIMAL_BI = int32(87)
MSK_CALLBACK_IM_PRIMAL_DUAL_SIMPLEX = int32(88)
MSK_CALLBACK_IM_PRIMAL_SENSIVITY = int32(89)
MSK_CALLBACK_IM_PRIMAL_SIMPLEX = int32(90)
MSK_CALLBACK_IM_QO_REFORMULATE = int32(91)
MSK_CALLBACK_IM_READ = int32(92)
MSK_CALLBACK_IM_SIMPLEX = int32(93)
MSK_CALLBACK_IM_SIMPLEX_BI = int32(94)
MSK_CALLBACK_INTPNT = int32(95)
MSK_CALLBACK_NEW_INT_MIO = int32(96)
MSK_CALLBACK_NONCOVEX = int32(97)
MSK_CALLBACK_PRIMAL_SIMPLEX = int32(98)
MSK_CALLBACK_READ_OPF = int32(99)
MSK_CALLBACK_READ_OPF_SECTION = int32(100)
MSK_CALLBACK_UPDATE_DUAL_BI = int32(101)
MSK_CALLBACK_UPDATE_DUAL_SIMPLEX = int32(102)
MSK_CALLBACK_UPDATE_DUAL_SIMPLEX_BI = int32(103)
MSK_CALLBACK_UPDATE_NETWORK_DUAL_SIMPLEX = int32(104)
MSK_CALLBACK_UPDATE_NETWORK_PRIMAL_SIMPLEX = int32(105)
MSK_CALLBACK_UPDATE_NONCONVEX = int32(106)
MSK_CALLBACK_UPDATE_PRESOLVE = int32(107)
MSK_CALLBACK_UPDATE_PRIMAL_BI = int32(108)
MSK_CALLBACK_UPDATE_PRIMAL_DUAL_SIMPLEX = int32(109)
MSK_CALLBACK_UPDATE_PRIMAL_DUAL_SIMPLEX_BI = int32(110)
MSK_CALLBACK_UPDATE_PRIMAL_SIMPLEX = int32(111)
MSK_CALLBACK_UPDATE_PRIMAL_SIMPLEX_BI = int32(112)
MSK_CALLBACK_WRITE_OPF = int32(113)

  MSK_CALLBACK_BEGIN = int32(0)
  MSK_CALLBACK_END   = int32(114)

# enum symmattype
MSK_SYMMAT_TYPE_SPARSE = int32(0)

  MSK_SYMMAT_TYPE_BEGIN = int32(0)
  MSK_SYMMAT_TYPE_END   = int32(1)

# enum feature
MSK_FEATURE_PTOM = int32(2)
MSK_FEATURE_PTON = int32(1)
MSK_FEATURE_PTOX = int32(3)
MSK_FEATURE_PTS = int32(0)

  MSK_FEATURE_BEGIN = int32(0)
  MSK_FEATURE_END   = int32(4)

# enum mark
MSK_MARK_LO = int32(0)
MSK_MARK_UP = int32(1)

  MSK_MARK_BEGIN = int32(0)
  MSK_MARK_END   = int32(2)

# enum conetype
MSK_CT_QUAD = int32(0)
MSK_CT_RQUAD = int32(1)

  MSK_CT_BEGIN = int32(0)
  MSK_CT_END   = int32(2)

# enum feasrepairtype
MSK_FEASREPAIR_OPTIMIZE_COMBINED = int32(2)
MSK_FEASREPAIR_OPTIMIZE_NONE = int32(0)
MSK_FEASREPAIR_OPTIMIZE_PENALTY = int32(1)

  MSK_FEASREPAIR_BEGIN = int32(0)
  MSK_FEASREPAIR_END   = int32(3)

# enum iomode
MSK_IOMODE_READ = int32(0)
MSK_IOMODE_READWRITE = int32(2)
MSK_IOMODE_WRITE = int32(1)

  MSK_IOMODE_BEGIN = int32(0)
  MSK_IOMODE_END   = int32(3)

# enum simseltype
MSK_SIM_SELECTION_ASE = int32(2)
MSK_SIM_SELECTION_DEVEX = int32(3)
MSK_SIM_SELECTION_FREE = int32(0)
MSK_SIM_SELECTION_FULL = int32(1)
MSK_SIM_SELECTION_PARTIAL = int32(5)
MSK_SIM_SELECTION_SE = int32(4)

  MSK_SIM_SELECTION_BEGIN = int32(0)
  MSK_SIM_SELECTION_END   = int32(6)

# enum msgkey
MSK_MSG_MPS_SELECTED = int32(1100)
MSK_MSG_READING_FILE = int32(1000)
MSK_MSG_WRITING_FILE = int32(1001)

# enum miomode
MSK_MIO_MODE_IGNORED = int32(0)
MSK_MIO_MODE_LAZY = int32(2)
MSK_MIO_MODE_SATISFIED = int32(1)

  MSK_MIO_MODE_BEGIN = int32(0)
  MSK_MIO_MODE_END   = int32(3)

# enum dinfitem
MSK_DINF_BI_CLEAN_DUAL_TIME = int32(0)
MSK_DINF_BI_CLEAN_PRIMAL_DUAL_TIME = int32(1)
MSK_DINF_BI_CLEAN_PRIMAL_TIME = int32(2)
MSK_DINF_BI_CLEAN_TIME = int32(3)
MSK_DINF_BI_DUAL_TIME = int32(4)
MSK_DINF_BI_PRIMAL_TIME = int32(5)
MSK_DINF_BI_TIME = int32(6)
MSK_DINF_CONCURRENT_TIME = int32(7)
MSK_DINF_INTPNT_DUAL_FEAS = int32(8)
MSK_DINF_INTPNT_DUAL_OBJ = int32(9)
MSK_DINF_INTPNT_FACTOR_NUM_FLOPS = int32(10)
MSK_DINF_INTPNT_OPT_STATUS = int32(11)
MSK_DINF_INTPNT_ORDER_TIME = int32(12)
MSK_DINF_INTPNT_PRIMAL_FEAS = int32(13)
MSK_DINF_INTPNT_PRIMAL_OBJ = int32(14)
MSK_DINF_INTPNT_TIME = int32(15)
MSK_DINF_MIO_CG_SEPERATION_TIME = int32(16)
MSK_DINF_MIO_CMIR_SEPERATION_TIME = int32(17)
MSK_DINF_MIO_CONSTRUCT_SOLUTION_OBJ = int32(18)
MSK_DINF_MIO_DUAL_BOUND_AFTER_PRESOLVE = int32(19)
MSK_DINF_MIO_HEURISTIC_TIME = int32(20)
MSK_DINF_MIO_OBJ_ABS_GAP = int32(21)
MSK_DINF_MIO_OBJ_BOUND = int32(22)
MSK_DINF_MIO_OBJ_INT = int32(23)
MSK_DINF_MIO_OBJ_REL_GAP = int32(24)
MSK_DINF_MIO_OPTIMIZER_TIME = int32(25)
MSK_DINF_MIO_PROBING_TIME = int32(26)
MSK_DINF_MIO_ROOT_CUTGEN_TIME = int32(27)
MSK_DINF_MIO_ROOT_OPTIMIZER_TIME = int32(28)
MSK_DINF_MIO_ROOT_PRESOLVE_TIME = int32(29)
MSK_DINF_MIO_TIME = int32(30)
MSK_DINF_MIO_USER_OBJ_CUT = int32(31)
MSK_DINF_OPTIMIZER_TIME = int32(32)
MSK_DINF_PRESOLVE_ELI_TIME = int32(33)
MSK_DINF_PRESOLVE_LINDEP_TIME = int32(34)
MSK_DINF_PRESOLVE_TIME = int32(35)
MSK_DINF_PRIMAL_REPAIR_PENALTY_OBJ = int32(36)
MSK_DINF_QCQO_REFORMULATE_TIME = int32(37)
MSK_DINF_RD_TIME = int32(38)
MSK_DINF_SIM_DUAL_TIME = int32(39)
MSK_DINF_SIM_FEAS = int32(40)
MSK_DINF_SIM_NETWORK_DUAL_TIME = int32(41)
MSK_DINF_SIM_NETWORK_PRIMAL_TIME = int32(42)
MSK_DINF_SIM_NETWORK_TIME = int32(43)
MSK_DINF_SIM_OBJ = int32(44)
MSK_DINF_SIM_PRIMAL_DUAL_TIME = int32(45)
MSK_DINF_SIM_PRIMAL_TIME = int32(46)
MSK_DINF_SIM_TIME = int32(47)
MSK_DINF_SOL_BAS_DUAL_OBJ = int32(48)
MSK_DINF_SOL_BAS_DVIOLCON = int32(49)
MSK_DINF_SOL_BAS_DVIOLVAR = int32(50)
MSK_DINF_SOL_BAS_PRIMAL_OBJ = int32(51)
MSK_DINF_SOL_BAS_PVIOLCON = int32(52)
MSK_DINF_SOL_BAS_PVIOLVAR = int32(53)
MSK_DINF_SOL_ITG_PRIMAL_OBJ = int32(54)
MSK_DINF_SOL_ITG_PVIOLBARVAR = int32(55)
MSK_DINF_SOL_ITG_PVIOLCON = int32(56)
MSK_DINF_SOL_ITG_PVIOLCONES = int32(57)
MSK_DINF_SOL_ITG_PVIOLITG = int32(58)
MSK_DINF_SOL_ITG_PVIOLVAR = int32(59)
MSK_DINF_SOL_ITR_DUAL_OBJ = int32(60)
MSK_DINF_SOL_ITR_DVIOLBARVAR = int32(61)
MSK_DINF_SOL_ITR_DVIOLCON = int32(62)
MSK_DINF_SOL_ITR_DVIOLCONES = int32(63)
MSK_DINF_SOL_ITR_DVIOLVAR = int32(64)
MSK_DINF_SOL_ITR_PRIMAL_OBJ = int32(65)
MSK_DINF_SOL_ITR_PVIOLBARVAR = int32(66)
MSK_DINF_SOL_ITR_PVIOLCON = int32(67)
MSK_DINF_SOL_ITR_PVIOLCONES = int32(68)
MSK_DINF_SOL_ITR_PVIOLVAR = int32(69)

  MSK_DINF_BEGIN = int32(0)
  MSK_DINF_END   = int32(70)

# enum parametertype
MSK_PAR_DOU_TYPE = int32(1)
MSK_PAR_INT_TYPE = int32(2)
MSK_PAR_INVALID_TYPE = int32(0)
MSK_PAR_STR_TYPE = int32(3)

  MSK_PAR_BEGIN = int32(0)
  MSK_PAR_END   = int32(4)

# enum rescodetype
MSK_RESPONSE_ERR = int32(3)
MSK_RESPONSE_OK = int32(0)
MSK_RESPONSE_TRM = int32(2)
MSK_RESPONSE_UNK = int32(4)
MSK_RESPONSE_WRN = int32(1)

  MSK_RESPONSE_BEGIN = int32(0)
  MSK_RESPONSE_END   = int32(5)

# enum prosta
MSK_PRO_STA_DUAL_FEAS = int32(3)
MSK_PRO_STA_DUAL_INFEAS = int32(5)
MSK_PRO_STA_ILL_POSED = int32(7)
MSK_PRO_STA_NEAR_DUAL_FEAS = int32(10)
MSK_PRO_STA_NEAR_PRIM_AND_DUAL_FEAS = int32(8)
MSK_PRO_STA_NEAR_PRIM_FEAS = int32(9)
MSK_PRO_STA_PRIM_AND_DUAL_FEAS = int32(1)
MSK_PRO_STA_PRIM_AND_DUAL_INFEAS = int32(6)
MSK_PRO_STA_PRIM_FEAS = int32(2)
MSK_PRO_STA_PRIM_INFEAS = int32(4)
MSK_PRO_STA_PRIM_INFEAS_OR_UNBOUNDED = int32(11)
MSK_PRO_STA_UNKNOWN = int32(0)

  MSK_PRO_STA_BEGIN = int32(0)
  MSK_PRO_STA_END   = int32(12)

# enum scalingtype
MSK_SCALING_AGGRESSIVE = int32(3)
MSK_SCALING_FREE = int32(0)
MSK_SCALING_MODERATE = int32(2)
MSK_SCALING_NONE = int32(1)

  MSK_SCALING_BEGIN = int32(0)
  MSK_SCALING_END   = int32(4)

# enum rescode
MSK_RES_ERR_AD_INVALID_CODELIST = int32(3102)
MSK_RES_ERR_AD_INVALID_OPERAND = int32(3104)
MSK_RES_ERR_AD_INVALID_OPERATOR = int32(3103)
MSK_RES_ERR_AD_MISSING_OPERAND = int32(3105)
MSK_RES_ERR_AD_MISSING_RETURN = int32(3106)
MSK_RES_ERR_API_ARRAY_TOO_SMALL = int32(3001)
MSK_RES_ERR_API_CB_CONNECT = int32(3002)
MSK_RES_ERR_API_FATAL_ERROR = int32(3005)
MSK_RES_ERR_API_INTERNAL = int32(3999)
MSK_RES_ERR_ARG_IS_TOO_LARGE = int32(1227)
MSK_RES_ERR_ARG_IS_TOO_SMALL = int32(1226)
MSK_RES_ERR_ARGUMENT_DIMENSION = int32(1201)
MSK_RES_ERR_ARGUMENT_IS_TOO_LARGE = int32(5005)
MSK_RES_ERR_ARGUMENT_LENNEQ = int32(1197)
MSK_RES_ERR_ARGUMENT_PERM_ARRAY = int32(1299)
MSK_RES_ERR_ARGUMENT_TYPE = int32(1198)
MSK_RES_ERR_BAR_VAR_DIM = int32(3920)
MSK_RES_ERR_BASIS = int32(1266)
MSK_RES_ERR_BASIS_FACTOR = int32(1610)
MSK_RES_ERR_BASIS_SINGULAR = int32(1615)
MSK_RES_ERR_BLANK_NAME = int32(1070)
MSK_RES_ERR_CANNOT_CLONE_NL = int32(2505)
MSK_RES_ERR_CANNOT_HANDLE_NL = int32(2506)
MSK_RES_ERR_CBF_DUPLICATE_ACOORD = int32(7116)
MSK_RES_ERR_CBF_DUPLICATE_BCOORD = int32(7115)
MSK_RES_ERR_CBF_DUPLICATE_CON = int32(7108)
MSK_RES_ERR_CBF_DUPLICATE_INT = int32(7110)
MSK_RES_ERR_CBF_DUPLICATE_OBJ = int32(7107)
MSK_RES_ERR_CBF_DUPLICATE_OBJACOORD = int32(7114)
MSK_RES_ERR_CBF_DUPLICATE_VAR = int32(7109)
MSK_RES_ERR_CBF_INVALID_CON_TYPE = int32(7112)
MSK_RES_ERR_CBF_INVALID_DOMAIN_DIMENSION = int32(7113)
MSK_RES_ERR_CBF_INVALID_INT_INDEX = int32(7121)
MSK_RES_ERR_CBF_INVALID_VAR_TYPE = int32(7111)
MSK_RES_ERR_CBF_NO_VARIABLES = int32(7102)
MSK_RES_ERR_CBF_NO_VERSION_SPECIFIED = int32(7105)
MSK_RES_ERR_CBF_OBJ_SENSE = int32(7101)
MSK_RES_ERR_CBF_PARSE = int32(7100)
MSK_RES_ERR_CBF_SYNTAX = int32(7106)
MSK_RES_ERR_CBF_TOO_FEW_CONSTRAINTS = int32(7118)
MSK_RES_ERR_CBF_TOO_FEW_INTS = int32(7119)
MSK_RES_ERR_CBF_TOO_FEW_VARIABLES = int32(7117)
MSK_RES_ERR_CBF_TOO_MANY_CONSTRAINTS = int32(7103)
MSK_RES_ERR_CBF_TOO_MANY_INTS = int32(7120)
MSK_RES_ERR_CBF_TOO_MANY_VARIABLES = int32(7104)
MSK_RES_ERR_CBF_UNSUPPORTED = int32(7122)
MSK_RES_ERR_CON_Q_NOT_NSD = int32(1294)
MSK_RES_ERR_CON_Q_NOT_PSD = int32(1293)
MSK_RES_ERR_CONCURRENT_OPTIMIZER = int32(3059)
MSK_RES_ERR_CONE_INDEX = int32(1300)
MSK_RES_ERR_CONE_OVERLAP = int32(1302)
MSK_RES_ERR_CONE_OVERLAP_APPEND = int32(1307)
MSK_RES_ERR_CONE_REP_VAR = int32(1303)
MSK_RES_ERR_CONE_SIZE = int32(1301)
MSK_RES_ERR_CONE_TYPE = int32(1305)
MSK_RES_ERR_CONE_TYPE_STR = int32(1306)
MSK_RES_ERR_DATA_FILE_EXT = int32(1055)
MSK_RES_ERR_DUP_NAME = int32(1071)
MSK_RES_ERR_DUPLICATE_BARVARIABLE_NAMES = int32(4502)
MSK_RES_ERR_DUPLICATE_CONE_NAMES = int32(4503)
MSK_RES_ERR_DUPLICATE_CONSTRAINT_NAMES = int32(4500)
MSK_RES_ERR_DUPLICATE_VARIABLE_NAMES = int32(4501)
MSK_RES_ERR_END_OF_FILE = int32(1059)
MSK_RES_ERR_FACTOR = int32(1650)
MSK_RES_ERR_FEASREPAIR_CANNOT_RELAX = int32(1700)
MSK_RES_ERR_FEASREPAIR_INCONSISTENT_BOUND = int32(1702)
MSK_RES_ERR_FEASREPAIR_SOLVING_RELAXED = int32(1701)
MSK_RES_ERR_FILE_LICENSE = int32(1007)
MSK_RES_ERR_FILE_OPEN = int32(1052)
MSK_RES_ERR_FILE_READ = int32(1053)
MSK_RES_ERR_FILE_WRITE = int32(1054)
MSK_RES_ERR_FIRST = int32(1261)
MSK_RES_ERR_FIRSTI = int32(1285)
MSK_RES_ERR_FIRSTJ = int32(1287)
MSK_RES_ERR_FIXED_BOUND_VALUES = int32(1425)
MSK_RES_ERR_FLEXLM = int32(1014)
MSK_RES_ERR_GLOBAL_INV_CONIC_PROBLEM = int32(1503)
MSK_RES_ERR_HUGE_AIJ = int32(1380)
MSK_RES_ERR_HUGE_C = int32(1375)
MSK_RES_ERR_IDENTICAL_TASKS = int32(3101)
MSK_RES_ERR_IN_ARGUMENT = int32(1200)
MSK_RES_ERR_INDEX = int32(1235)
MSK_RES_ERR_INDEX_ARR_IS_TOO_LARGE = int32(1222)
MSK_RES_ERR_INDEX_ARR_IS_TOO_SMALL = int32(1221)
MSK_RES_ERR_INDEX_IS_TOO_LARGE = int32(1204)
MSK_RES_ERR_INDEX_IS_TOO_SMALL = int32(1203)
MSK_RES_ERR_INF_DOU_INDEX = int32(1219)
MSK_RES_ERR_INF_DOU_NAME = int32(1230)
MSK_RES_ERR_INF_INT_INDEX = int32(1220)
MSK_RES_ERR_INF_INT_NAME = int32(1231)
MSK_RES_ERR_INF_LINT_INDEX = int32(1225)
MSK_RES_ERR_INF_LINT_NAME = int32(1234)
MSK_RES_ERR_INF_TYPE = int32(1232)
MSK_RES_ERR_INFEAS_UNDEFINED = int32(3910)
MSK_RES_ERR_INFINITE_BOUND = int32(1400)
MSK_RES_ERR_INT64_TO_INT32_CAST = int32(3800)
MSK_RES_ERR_INTERNAL = int32(3000)
MSK_RES_ERR_INTERNAL_TEST_FAILED = int32(3500)
MSK_RES_ERR_INV_APTRE = int32(1253)
MSK_RES_ERR_INV_BK = int32(1255)
MSK_RES_ERR_INV_BKC = int32(1256)
MSK_RES_ERR_INV_BKX = int32(1257)
MSK_RES_ERR_INV_CONE_TYPE = int32(1272)
MSK_RES_ERR_INV_CONE_TYPE_STR = int32(1271)
MSK_RES_ERR_INV_CONIC_PROBLEM = int32(1502)
MSK_RES_ERR_INV_MARKI = int32(2501)
MSK_RES_ERR_INV_MARKJ = int32(2502)
MSK_RES_ERR_INV_NAME_ITEM = int32(1280)
MSK_RES_ERR_INV_NUMI = int32(2503)
MSK_RES_ERR_INV_NUMJ = int32(2504)
MSK_RES_ERR_INV_OPTIMIZER = int32(1550)
MSK_RES_ERR_INV_PROBLEM = int32(1500)
MSK_RES_ERR_INV_QCON_SUBI = int32(1405)
MSK_RES_ERR_INV_QCON_SUBJ = int32(1406)
MSK_RES_ERR_INV_QCON_SUBK = int32(1404)
MSK_RES_ERR_INV_QCON_VAL = int32(1407)
MSK_RES_ERR_INV_QOBJ_SUBI = int32(1401)
MSK_RES_ERR_INV_QOBJ_SUBJ = int32(1402)
MSK_RES_ERR_INV_QOBJ_VAL = int32(1403)
MSK_RES_ERR_INV_SK = int32(1270)
MSK_RES_ERR_INV_SK_STR = int32(1269)
MSK_RES_ERR_INV_SKC = int32(1267)
MSK_RES_ERR_INV_SKN = int32(1274)
MSK_RES_ERR_INV_SKX = int32(1268)
MSK_RES_ERR_INV_VAR_TYPE = int32(1258)
MSK_RES_ERR_INVALID_ACCMODE = int32(2520)
MSK_RES_ERR_INVALID_AIJ = int32(1473)
MSK_RES_ERR_INVALID_AMPL_STUB = int32(3700)
MSK_RES_ERR_INVALID_BARVAR_NAME = int32(1079)
MSK_RES_ERR_INVALID_BRANCH_DIRECTION = int32(3200)
MSK_RES_ERR_INVALID_BRANCH_PRIORITY = int32(3201)
MSK_RES_ERR_INVALID_COMPRESSION = int32(1800)
MSK_RES_ERR_INVALID_CON_NAME = int32(1076)
MSK_RES_ERR_INVALID_CONE_NAME = int32(1078)
MSK_RES_ERR_INVALID_FILE_FORMAT_FOR_CONES = int32(4005)
MSK_RES_ERR_INVALID_FILE_FORMAT_FOR_GENERAL_NL = int32(4010)
MSK_RES_ERR_INVALID_FILE_FORMAT_FOR_SYM_MAT = int32(4000)
MSK_RES_ERR_INVALID_FILE_NAME = int32(1056)
MSK_RES_ERR_INVALID_FORMAT_TYPE = int32(1283)
MSK_RES_ERR_INVALID_IDX = int32(1246)
MSK_RES_ERR_INVALID_IOMODE = int32(1801)
MSK_RES_ERR_INVALID_MAX_NUM = int32(1247)
MSK_RES_ERR_INVALID_NAME_IN_SOL_FILE = int32(1170)
MSK_RES_ERR_INVALID_NETWORK_PROBLEM = int32(1504)
MSK_RES_ERR_INVALID_OBJ_NAME = int32(1075)
MSK_RES_ERR_INVALID_OBJECTIVE_SENSE = int32(1445)
MSK_RES_ERR_INVALID_PROBLEM_TYPE = int32(6000)
MSK_RES_ERR_INVALID_SOL_FILE_NAME = int32(1057)
MSK_RES_ERR_INVALID_STREAM = int32(1062)
MSK_RES_ERR_INVALID_SURPLUS = int32(1275)
MSK_RES_ERR_INVALID_SYM_MAT_DIM = int32(3950)
MSK_RES_ERR_INVALID_TASK = int32(1064)
MSK_RES_ERR_INVALID_UTF8 = int32(2900)
MSK_RES_ERR_INVALID_VAR_NAME = int32(1077)
MSK_RES_ERR_INVALID_WCHAR = int32(2901)
MSK_RES_ERR_INVALID_WHICHSOL = int32(1228)
MSK_RES_ERR_LAST = int32(1262)
MSK_RES_ERR_LASTI = int32(1286)
MSK_RES_ERR_LASTJ = int32(1288)
MSK_RES_ERR_LAU_ARG_K = int32(7004)
MSK_RES_ERR_LAU_ARG_M = int32(7002)
MSK_RES_ERR_LAU_ARG_N = int32(7003)
MSK_RES_ERR_LAU_ARG_TRANS = int32(7008)
MSK_RES_ERR_LAU_ARG_TRANSA = int32(7005)
MSK_RES_ERR_LAU_ARG_TRANSB = int32(7006)
MSK_RES_ERR_LAU_ARG_UPLO = int32(7007)
MSK_RES_ERR_LAU_SINGULAR_MATRIX = int32(7000)
MSK_RES_ERR_LAU_UNKNOWN = int32(7001)
MSK_RES_ERR_LICENSE = int32(1000)
MSK_RES_ERR_LICENSE_CANNOT_ALLOCATE = int32(1020)
MSK_RES_ERR_LICENSE_CANNOT_CONNECT = int32(1021)
MSK_RES_ERR_LICENSE_EXPIRED = int32(1001)
MSK_RES_ERR_LICENSE_FEATURE = int32(1018)
MSK_RES_ERR_LICENSE_INVALID_HOSTID = int32(1025)
MSK_RES_ERR_LICENSE_MAX = int32(1016)
MSK_RES_ERR_LICENSE_MOSEKLM_DAEMON = int32(1017)
MSK_RES_ERR_LICENSE_NO_SERVER_LINE = int32(1028)
MSK_RES_ERR_LICENSE_NO_SERVER_SUPPORT = int32(1027)
MSK_RES_ERR_LICENSE_SERVER = int32(1015)
MSK_RES_ERR_LICENSE_SERVER_VERSION = int32(1026)
MSK_RES_ERR_LICENSE_VERSION = int32(1002)
MSK_RES_ERR_LINK_FILE_DLL = int32(1040)
MSK_RES_ERR_LIVING_TASKS = int32(1066)
MSK_RES_ERR_LOWER_BOUND_IS_A_NAN = int32(1390)
MSK_RES_ERR_LP_DUP_SLACK_NAME = int32(1152)
MSK_RES_ERR_LP_EMPTY = int32(1151)
MSK_RES_ERR_LP_FILE_FORMAT = int32(1157)
MSK_RES_ERR_LP_FORMAT = int32(1160)
MSK_RES_ERR_LP_FREE_CONSTRAINT = int32(1155)
MSK_RES_ERR_LP_INCOMPATIBLE = int32(1150)
MSK_RES_ERR_LP_INVALID_CON_NAME = int32(1171)
MSK_RES_ERR_LP_INVALID_VAR_NAME = int32(1154)
MSK_RES_ERR_LP_WRITE_CONIC_PROBLEM = int32(1163)
MSK_RES_ERR_LP_WRITE_GECO_PROBLEM = int32(1164)
MSK_RES_ERR_LU_MAX_NUM_TRIES = int32(2800)
MSK_RES_ERR_MAX_LEN_IS_TOO_SMALL = int32(1289)
MSK_RES_ERR_MAXNUMBARVAR = int32(1242)
MSK_RES_ERR_MAXNUMCON = int32(1240)
MSK_RES_ERR_MAXNUMCONE = int32(1304)
MSK_RES_ERR_MAXNUMQNZ = int32(1243)
MSK_RES_ERR_MAXNUMVAR = int32(1241)
MSK_RES_ERR_MBT_INCOMPATIBLE = int32(2550)
MSK_RES_ERR_MBT_INVALID = int32(2551)
MSK_RES_ERR_MIO_INTERNAL = int32(5010)
MSK_RES_ERR_MIO_INVALID_NODE_OPTIMIZER = int32(7131)
MSK_RES_ERR_MIO_INVALID_ROOT_OPTIMIZER = int32(7130)
MSK_RES_ERR_MIO_NO_OPTIMIZER = int32(1551)
MSK_RES_ERR_MIO_NOT_LOADED = int32(1553)
MSK_RES_ERR_MISSING_LICENSE_FILE = int32(1008)
MSK_RES_ERR_MIXED_PROBLEM = int32(1501)
MSK_RES_ERR_MPS_CONE_OVERLAP = int32(1118)
MSK_RES_ERR_MPS_CONE_REPEAT = int32(1119)
MSK_RES_ERR_MPS_CONE_TYPE = int32(1117)
MSK_RES_ERR_MPS_DUPLICATE_Q_ELEMENT = int32(1121)
MSK_RES_ERR_MPS_FILE = int32(1100)
MSK_RES_ERR_MPS_INV_BOUND_KEY = int32(1108)
MSK_RES_ERR_MPS_INV_CON_KEY = int32(1107)
MSK_RES_ERR_MPS_INV_FIELD = int32(1101)
MSK_RES_ERR_MPS_INV_MARKER = int32(1102)
MSK_RES_ERR_MPS_INV_SEC_NAME = int32(1109)
MSK_RES_ERR_MPS_INV_SEC_ORDER = int32(1115)
MSK_RES_ERR_MPS_INVALID_OBJ_NAME = int32(1128)
MSK_RES_ERR_MPS_INVALID_OBJSENSE = int32(1122)
MSK_RES_ERR_MPS_MUL_CON_NAME = int32(1112)
MSK_RES_ERR_MPS_MUL_CSEC = int32(1116)
MSK_RES_ERR_MPS_MUL_QOBJ = int32(1114)
MSK_RES_ERR_MPS_MUL_QSEC = int32(1113)
MSK_RES_ERR_MPS_NO_OBJECTIVE = int32(1110)
MSK_RES_ERR_MPS_NON_SYMMETRIC_Q = int32(1120)
MSK_RES_ERR_MPS_NULL_CON_NAME = int32(1103)
MSK_RES_ERR_MPS_NULL_VAR_NAME = int32(1104)
MSK_RES_ERR_MPS_SPLITTED_VAR = int32(1111)
MSK_RES_ERR_MPS_TAB_IN_FIELD2 = int32(1125)
MSK_RES_ERR_MPS_TAB_IN_FIELD3 = int32(1126)
MSK_RES_ERR_MPS_TAB_IN_FIELD5 = int32(1127)
MSK_RES_ERR_MPS_UNDEF_CON_NAME = int32(1105)
MSK_RES_ERR_MPS_UNDEF_VAR_NAME = int32(1106)
MSK_RES_ERR_MUL_A_ELEMENT = int32(1254)
MSK_RES_ERR_NAME_IS_NULL = int32(1760)
MSK_RES_ERR_NAME_MAX_LEN = int32(1750)
MSK_RES_ERR_NAN_IN_BLC = int32(1461)
MSK_RES_ERR_NAN_IN_BLX = int32(1471)
MSK_RES_ERR_NAN_IN_BUC = int32(1462)
MSK_RES_ERR_NAN_IN_BUX = int32(1472)
MSK_RES_ERR_NAN_IN_C = int32(1470)
MSK_RES_ERR_NAN_IN_DOUBLE_DATA = int32(1450)
MSK_RES_ERR_NEGATIVE_APPEND = int32(1264)
MSK_RES_ERR_NEGATIVE_SURPLUS = int32(1263)
MSK_RES_ERR_NEWER_DLL = int32(1036)
MSK_RES_ERR_NO_BARS_FOR_SOLUTION = int32(3916)
MSK_RES_ERR_NO_BARX_FOR_SOLUTION = int32(3915)
MSK_RES_ERR_NO_BASIS_SOL = int32(1600)
MSK_RES_ERR_NO_DUAL_FOR_ITG_SOL = int32(2950)
MSK_RES_ERR_NO_DUAL_INFEAS_CER = int32(2001)
MSK_RES_ERR_NO_DUAL_INFO_FOR_ITG_SOL = int32(3300)
MSK_RES_ERR_NO_INIT_ENV = int32(1063)
MSK_RES_ERR_NO_OPTIMIZER_VAR_TYPE = int32(1552)
MSK_RES_ERR_NO_PRIMAL_INFEAS_CER = int32(2000)
MSK_RES_ERR_NO_SNX_FOR_BAS_SOL = int32(2953)
MSK_RES_ERR_NO_SOLUTION_IN_CALLBACK = int32(2500)
MSK_RES_ERR_NON_UNIQUE_ARRAY = int32(5000)
MSK_RES_ERR_NONCONVEX = int32(1291)
MSK_RES_ERR_NONLINEAR_EQUALITY = int32(1290)
MSK_RES_ERR_NONLINEAR_FUNCTIONS_NOT_ALLOWED = int32(1428)
MSK_RES_ERR_NONLINEAR_RANGED = int32(1292)
MSK_RES_ERR_NR_ARGUMENTS = int32(1199)
MSK_RES_ERR_NULL_ENV = int32(1060)
MSK_RES_ERR_NULL_POINTER = int32(1065)
MSK_RES_ERR_NULL_TASK = int32(1061)
MSK_RES_ERR_NUMCONLIM = int32(1250)
MSK_RES_ERR_NUMVARLIM = int32(1251)
MSK_RES_ERR_OBJ_Q_NOT_NSD = int32(1296)
MSK_RES_ERR_OBJ_Q_NOT_PSD = int32(1295)
MSK_RES_ERR_OBJECTIVE_RANGE = int32(1260)
MSK_RES_ERR_OLDER_DLL = int32(1035)
MSK_RES_ERR_OPEN_DL = int32(1030)
MSK_RES_ERR_OPF_FORMAT = int32(1168)
MSK_RES_ERR_OPF_NEW_VARIABLE = int32(1169)
MSK_RES_ERR_OPF_PREMATURE_EOF = int32(1172)
MSK_RES_ERR_OPTIMIZER_LICENSE = int32(1013)
MSK_RES_ERR_ORD_INVALID = int32(1131)
MSK_RES_ERR_ORD_INVALID_BRANCH_DIR = int32(1130)
MSK_RES_ERR_OVERFLOW = int32(1590)
MSK_RES_ERR_PARAM_INDEX = int32(1210)
MSK_RES_ERR_PARAM_IS_TOO_LARGE = int32(1215)
MSK_RES_ERR_PARAM_IS_TOO_SMALL = int32(1216)
MSK_RES_ERR_PARAM_NAME = int32(1205)
MSK_RES_ERR_PARAM_NAME_DOU = int32(1206)
MSK_RES_ERR_PARAM_NAME_INT = int32(1207)
MSK_RES_ERR_PARAM_NAME_STR = int32(1208)
MSK_RES_ERR_PARAM_TYPE = int32(1218)
MSK_RES_ERR_PARAM_VALUE_STR = int32(1217)
MSK_RES_ERR_PLATFORM_NOT_LICENSED = int32(1019)
MSK_RES_ERR_POSTSOLVE = int32(1580)
MSK_RES_ERR_PRO_ITEM = int32(1281)
MSK_RES_ERR_PROB_LICENSE = int32(1006)
MSK_RES_ERR_QCON_SUBI_TOO_LARGE = int32(1409)
MSK_RES_ERR_QCON_SUBI_TOO_SMALL = int32(1408)
MSK_RES_ERR_QCON_UPPER_TRIANGLE = int32(1417)
MSK_RES_ERR_QOBJ_UPPER_TRIANGLE = int32(1415)
MSK_RES_ERR_READ_FORMAT = int32(1090)
MSK_RES_ERR_READ_LP_MISSING_END_TAG = int32(1159)
MSK_RES_ERR_READ_LP_NONEXISTING_NAME = int32(1162)
MSK_RES_ERR_REMOVE_CONE_VARIABLE = int32(1310)
MSK_RES_ERR_REPAIR_INVALID_PROBLEM = int32(1710)
MSK_RES_ERR_REPAIR_OPTIMIZATION_FAILED = int32(1711)
MSK_RES_ERR_SEN_BOUND_INVALID_LO = int32(3054)
MSK_RES_ERR_SEN_BOUND_INVALID_UP = int32(3053)
MSK_RES_ERR_SEN_FORMAT = int32(3050)
MSK_RES_ERR_SEN_INDEX_INVALID = int32(3055)
MSK_RES_ERR_SEN_INDEX_RANGE = int32(3052)
MSK_RES_ERR_SEN_INVALID_REGEXP = int32(3056)
MSK_RES_ERR_SEN_NUMERICAL = int32(3058)
MSK_RES_ERR_SEN_SOLUTION_STATUS = int32(3057)
MSK_RES_ERR_SEN_UNDEF_NAME = int32(3051)
MSK_RES_ERR_SEN_UNHANDLED_PROBLEM_TYPE = int32(3080)
MSK_RES_ERR_SIZE_LICENSE = int32(1005)
MSK_RES_ERR_SIZE_LICENSE_CON = int32(1010)
MSK_RES_ERR_SIZE_LICENSE_INTVAR = int32(1012)
MSK_RES_ERR_SIZE_LICENSE_NUMCORES = int32(3900)
MSK_RES_ERR_SIZE_LICENSE_VAR = int32(1011)
MSK_RES_ERR_SOL_FILE_INVALID_NUMBER = int32(1350)
MSK_RES_ERR_SOLITEM = int32(1237)
MSK_RES_ERR_SOLVER_PROBTYPE = int32(1259)
MSK_RES_ERR_SPACE = int32(1051)
MSK_RES_ERR_SPACE_LEAKING = int32(1080)
MSK_RES_ERR_SPACE_NO_INFO = int32(1081)
MSK_RES_ERR_SYM_MAT_DUPLICATE = int32(3944)
MSK_RES_ERR_SYM_MAT_INVALID_COL_INDEX = int32(3941)
MSK_RES_ERR_SYM_MAT_INVALID_ROW_INDEX = int32(3940)
MSK_RES_ERR_SYM_MAT_INVALID_VALUE = int32(3943)
MSK_RES_ERR_SYM_MAT_NOT_LOWER_TRINGULAR = int32(3942)
MSK_RES_ERR_TASK_INCOMPATIBLE = int32(2560)
MSK_RES_ERR_TASK_INVALID = int32(2561)
MSK_RES_ERR_THREAD_COND_INIT = int32(1049)
MSK_RES_ERR_THREAD_CREATE = int32(1048)
MSK_RES_ERR_THREAD_MUTEX_INIT = int32(1045)
MSK_RES_ERR_THREAD_MUTEX_LOCK = int32(1046)
MSK_RES_ERR_THREAD_MUTEX_UNLOCK = int32(1047)
MSK_RES_ERR_TOCONIC_CONVERSION_FAIL = int32(7200)
MSK_RES_ERR_TOO_MANY_CONCURRENT_TASKS = int32(3090)
MSK_RES_ERR_TOO_SMALL_MAX_NUM_NZ = int32(1245)
MSK_RES_ERR_TOO_SMALL_MAXNUMANZ = int32(1252)
MSK_RES_ERR_UNB_STEP_SIZE = int32(3100)
MSK_RES_ERR_UNDEF_SOLUTION = int32(1265)
MSK_RES_ERR_UNDEFINED_OBJECTIVE_SENSE = int32(1446)
MSK_RES_ERR_UNHANDLED_SOLUTION_STATUS = int32(6010)
MSK_RES_ERR_UNKNOWN = int32(1050)
MSK_RES_ERR_UPPER_BOUND_IS_A_NAN = int32(1391)
MSK_RES_ERR_UPPER_TRIANGLE = int32(6020)
MSK_RES_ERR_USER_FUNC_RET = int32(1430)
MSK_RES_ERR_USER_FUNC_RET_DATA = int32(1431)
MSK_RES_ERR_USER_NLO_EVAL = int32(1433)
MSK_RES_ERR_USER_NLO_EVAL_HESSUBI = int32(1440)
MSK_RES_ERR_USER_NLO_EVAL_HESSUBJ = int32(1441)
MSK_RES_ERR_USER_NLO_FUNC = int32(1432)
MSK_RES_ERR_WHICHITEM_NOT_ALLOWED = int32(1238)
MSK_RES_ERR_WHICHSOL = int32(1236)
MSK_RES_ERR_WRITE_LP_FORMAT = int32(1158)
MSK_RES_ERR_WRITE_LP_NON_UNIQUE_NAME = int32(1161)
MSK_RES_ERR_WRITE_MPS_INVALID_NAME = int32(1153)
MSK_RES_ERR_WRITE_OPF_INVALID_VAR_NAME = int32(1156)
MSK_RES_ERR_WRITING_FILE = int32(1166)
MSK_RES_ERR_XML_INVALID_PROBLEM_TYPE = int32(3600)
MSK_RES_ERR_Y_IS_UNDEFINED = int32(1449)
MSK_RES_OK = int32(0)
MSK_RES_TRM_INTERNAL = int32(10030)
MSK_RES_TRM_INTERNAL_STOP = int32(10031)
MSK_RES_TRM_MAX_ITERATIONS = int32(10000)
MSK_RES_TRM_MAX_NUM_SETBACKS = int32(10020)
MSK_RES_TRM_MAX_TIME = int32(10001)
MSK_RES_TRM_MIO_NEAR_ABS_GAP = int32(10004)
MSK_RES_TRM_MIO_NEAR_REL_GAP = int32(10003)
MSK_RES_TRM_MIO_NUM_BRANCHES = int32(10009)
MSK_RES_TRM_MIO_NUM_RELAXS = int32(10008)
MSK_RES_TRM_NUM_MAX_NUM_INT_SOLUTIONS = int32(10015)
MSK_RES_TRM_NUMERICAL_PROBLEM = int32(10025)
MSK_RES_TRM_OBJECTIVE_RANGE = int32(10002)
MSK_RES_TRM_STALL = int32(10006)
MSK_RES_TRM_USER_CALLBACK = int32(10007)
MSK_RES_WRN_ANA_ALMOST_INT_BOUNDS = int32(904)
MSK_RES_WRN_ANA_C_ZERO = int32(901)
MSK_RES_WRN_ANA_CLOSE_BOUNDS = int32(903)
MSK_RES_WRN_ANA_EMPTY_COLS = int32(902)
MSK_RES_WRN_ANA_LARGE_BOUNDS = int32(900)
MSK_RES_WRN_CONSTRUCT_INVALID_SOL_ITG = int32(807)
MSK_RES_WRN_CONSTRUCT_NO_SOL_ITG = int32(810)
MSK_RES_WRN_CONSTRUCT_SOLUTION_INFEAS = int32(805)
MSK_RES_WRN_DROPPED_NZ_QOBJ = int32(201)
MSK_RES_WRN_DUPLICATE_BARVARIABLE_NAMES = int32(852)
MSK_RES_WRN_DUPLICATE_CONE_NAMES = int32(853)
MSK_RES_WRN_DUPLICATE_CONSTRAINT_NAMES = int32(850)
MSK_RES_WRN_DUPLICATE_VARIABLE_NAMES = int32(851)
MSK_RES_WRN_ELIMINATOR_SPACE = int32(801)
MSK_RES_WRN_EMPTY_NAME = int32(502)
MSK_RES_WRN_IGNORE_INTEGER = int32(250)
MSK_RES_WRN_INCOMPLETE_LINEAR_DEPENDENCY_CHECK = int32(800)
MSK_RES_WRN_LARGE_AIJ = int32(62)
MSK_RES_WRN_LARGE_BOUND = int32(51)
MSK_RES_WRN_LARGE_CJ = int32(57)
MSK_RES_WRN_LARGE_CON_FX = int32(54)
MSK_RES_WRN_LARGE_LO_BOUND = int32(52)
MSK_RES_WRN_LARGE_UP_BOUND = int32(53)
MSK_RES_WRN_LICENSE_EXPIRE = int32(500)
MSK_RES_WRN_LICENSE_FEATURE_EXPIRE = int32(505)
MSK_RES_WRN_LICENSE_SERVER = int32(501)
MSK_RES_WRN_LP_DROP_VARIABLE = int32(85)
MSK_RES_WRN_LP_OLD_QUAD_FORMAT = int32(80)
MSK_RES_WRN_MIO_INFEASIBLE_FINAL = int32(270)
MSK_RES_WRN_MPS_SPLIT_BOU_VECTOR = int32(72)
MSK_RES_WRN_MPS_SPLIT_RAN_VECTOR = int32(71)
MSK_RES_WRN_MPS_SPLIT_RHS_VECTOR = int32(70)
MSK_RES_WRN_NAME_MAX_LEN = int32(65)
MSK_RES_WRN_NO_DUALIZER = int32(950)
MSK_RES_WRN_NO_GLOBAL_OPTIMIZER = int32(251)
MSK_RES_WRN_NO_NONLINEAR_FUNCTION_WRITE = int32(450)
MSK_RES_WRN_NZ_IN_UPR_TRI = int32(200)
MSK_RES_WRN_OPEN_PARAM_FILE = int32(50)
MSK_RES_WRN_PARAM_IGNORED_CMIO = int32(516)
MSK_RES_WRN_PARAM_NAME_DOU = int32(510)
MSK_RES_WRN_PARAM_NAME_INT = int32(511)
MSK_RES_WRN_PARAM_NAME_STR = int32(512)
MSK_RES_WRN_PARAM_STR_VALUE = int32(515)
MSK_RES_WRN_PRESOLVE_OUTOFSPACE = int32(802)
MSK_RES_WRN_QUAD_CONES_WITH_ROOT_FIXED_AT_ZERO = int32(930)
MSK_RES_WRN_RQUAD_CONES_WITH_ROOT_FIXED_AT_ZERO = int32(931)
MSK_RES_WRN_SOL_FILE_IGNORED_CON = int32(351)
MSK_RES_WRN_SOL_FILE_IGNORED_VAR = int32(352)
MSK_RES_WRN_SOL_FILTER = int32(300)
MSK_RES_WRN_SPAR_MAX_LEN = int32(66)
MSK_RES_WRN_TOO_FEW_BASIS_VARS = int32(400)
MSK_RES_WRN_TOO_MANY_BASIS_VARS = int32(405)
MSK_RES_WRN_TOO_MANY_THREADS_CONCURRENT = int32(750)
MSK_RES_WRN_UNDEF_SOL_FILE_NAME = int32(350)
MSK_RES_WRN_USING_GENERIC_NAMES = int32(503)
MSK_RES_WRN_WRITE_CHANGED_NAMES = int32(803)
MSK_RES_WRN_WRITE_DISCARDED_CFIX = int32(804)
MSK_RES_WRN_ZERO_AIJ = int32(63)
MSK_RES_WRN_ZEROS_IN_SPARSE_COL = int32(710)
MSK_RES_WRN_ZEROS_IN_SPARSE_ROW = int32(705)

# enum mionodeseltype
MSK_MIO_NODE_SELECTION_BEST = int32(2)
MSK_MIO_NODE_SELECTION_FIRST = int32(1)
MSK_MIO_NODE_SELECTION_FREE = int32(0)
MSK_MIO_NODE_SELECTION_HYBRID = int32(4)
MSK_MIO_NODE_SELECTION_PSEUDO = int32(5)
MSK_MIO_NODE_SELECTION_WORST = int32(3)

  MSK_MIO_NODE_SELECTION_BEGIN = int32(0)
  MSK_MIO_NODE_SELECTION_END   = int32(6)

# enum transpose
MSK_TRANSPOSE_NO = int32(0)
MSK_TRANSPOSE_YES = int32(1)

  MSK_TRANSPOSE_BEGIN = int32(0)
  MSK_TRANSPOSE_END   = int32(2)

# enum onoffkey
MSK_OFF = int32(0)
MSK_ON = int32(1)

# enum simdegen
MSK_SIM_DEGEN_AGGRESSIVE = int32(2)
MSK_SIM_DEGEN_FREE = int32(1)
MSK_SIM_DEGEN_MINIMUM = int32(4)
MSK_SIM_DEGEN_MODERATE = int32(3)
MSK_SIM_DEGEN_NONE = int32(0)

  MSK_SIM_DEGEN_BEGIN = int32(0)
  MSK_SIM_DEGEN_END   = int32(5)

# enum dataformat
MSK_DATA_FORMAT_CB = int32(7)
MSK_DATA_FORMAT_EXTENSION = int32(0)
MSK_DATA_FORMAT_FREE_MPS = int32(5)
MSK_DATA_FORMAT_LP = int32(2)
MSK_DATA_FORMAT_MPS = int32(1)
MSK_DATA_FORMAT_OP = int32(3)
MSK_DATA_FORMAT_TASK = int32(6)
MSK_DATA_FORMAT_XML = int32(4)

  MSK_DATA_FORMAT_BEGIN = int32(0)
  MSK_DATA_FORMAT_END   = int32(8)

# enum orderingtype
MSK_ORDER_METHOD_APPMINLOC = int32(1)
MSK_ORDER_METHOD_EXPERIMENTAL = int32(2)
MSK_ORDER_METHOD_FORCE_GRAPHPAR = int32(4)
MSK_ORDER_METHOD_FREE = int32(0)
MSK_ORDER_METHOD_NONE = int32(5)
MSK_ORDER_METHOD_TRY_GRAPHPAR = int32(3)

  MSK_ORDER_METHOD_BEGIN = int32(0)
  MSK_ORDER_METHOD_END   = int32(6)

# enum problemtype
MSK_PROBTYPE_CONIC = int32(4)
MSK_PROBTYPE_GECO = int32(3)
MSK_PROBTYPE_LO = int32(0)
MSK_PROBTYPE_MIXED = int32(5)
MSK_PROBTYPE_QCQO = int32(2)
MSK_PROBTYPE_QO = int32(1)

  MSK_PROBTYPE_BEGIN = int32(0)
  MSK_PROBTYPE_END   = int32(6)

# enum inftype
MSK_INF_DOU_TYPE = int32(0)
MSK_INF_INT_TYPE = int32(1)
MSK_INF_LINT_TYPE = int32(2)

  MSK_INF_BEGIN = int32(0)
  MSK_INF_END   = int32(3)

# enum dparam
MSK_DPAR_ANA_SOL_INFEAS_TOL = int32(0)
MSK_DPAR_BASIS_REL_TOL_S = int32(1)
MSK_DPAR_BASIS_TOL_S = int32(2)
MSK_DPAR_BASIS_TOL_X = int32(3)
MSK_DPAR_CHECK_CONVEXITY_REL_TOL = int32(4)
MSK_DPAR_DATA_TOL_AIJ = int32(5)
MSK_DPAR_DATA_TOL_AIJ_HUGE = int32(6)
MSK_DPAR_DATA_TOL_AIJ_LARGE = int32(7)
MSK_DPAR_DATA_TOL_BOUND_INF = int32(8)
MSK_DPAR_DATA_TOL_BOUND_WRN = int32(9)
MSK_DPAR_DATA_TOL_C_HUGE = int32(10)
MSK_DPAR_DATA_TOL_CJ_LARGE = int32(11)
MSK_DPAR_DATA_TOL_QIJ = int32(12)
MSK_DPAR_DATA_TOL_X = int32(13)
MSK_DPAR_FEASREPAIR_TOL = int32(14)
MSK_DPAR_INTPNT_CO_TOL_DFEAS = int32(15)
MSK_DPAR_INTPNT_CO_TOL_INFEAS = int32(16)
MSK_DPAR_INTPNT_CO_TOL_MU_RED = int32(17)
MSK_DPAR_INTPNT_CO_TOL_NEAR_REL = int32(18)
MSK_DPAR_INTPNT_CO_TOL_PFEAS = int32(19)
MSK_DPAR_INTPNT_CO_TOL_REL_GAP = int32(20)
MSK_DPAR_INTPNT_NL_MERIT_BAL = int32(21)
MSK_DPAR_INTPNT_NL_TOL_DFEAS = int32(22)
MSK_DPAR_INTPNT_NL_TOL_MU_RED = int32(23)
MSK_DPAR_INTPNT_NL_TOL_NEAR_REL = int32(24)
MSK_DPAR_INTPNT_NL_TOL_PFEAS = int32(25)
MSK_DPAR_INTPNT_NL_TOL_REL_GAP = int32(26)
MSK_DPAR_INTPNT_NL_TOL_REL_STEP = int32(27)
MSK_DPAR_INTPNT_TOL_DFEAS = int32(28)
MSK_DPAR_INTPNT_TOL_DSAFE = int32(29)
MSK_DPAR_INTPNT_TOL_INFEAS = int32(30)
MSK_DPAR_INTPNT_TOL_MU_RED = int32(31)
MSK_DPAR_INTPNT_TOL_PATH = int32(32)
MSK_DPAR_INTPNT_TOL_PFEAS = int32(33)
MSK_DPAR_INTPNT_TOL_PSAFE = int32(34)
MSK_DPAR_INTPNT_TOL_REL_GAP = int32(35)
MSK_DPAR_INTPNT_TOL_REL_STEP = int32(36)
MSK_DPAR_INTPNT_TOL_STEP_SIZE = int32(37)
MSK_DPAR_LOWER_OBJ_CUT = int32(38)
MSK_DPAR_LOWER_OBJ_CUT_FINITE_TRH = int32(39)
MSK_DPAR_MIO_DISABLE_TERM_TIME = int32(40)
MSK_DPAR_MIO_HEURISTIC_TIME = int32(41)
MSK_DPAR_MIO_MAX_TIME = int32(42)
MSK_DPAR_MIO_MAX_TIME_APRX_OPT = int32(43)
MSK_DPAR_MIO_NEAR_TOL_ABS_GAP = int32(44)
MSK_DPAR_MIO_NEAR_TOL_REL_GAP = int32(45)
MSK_DPAR_MIO_REL_ADD_CUT_LIMITED = int32(46)
MSK_DPAR_MIO_REL_GAP_CONST = int32(47)
MSK_DPAR_MIO_TOL_ABS_GAP = int32(48)
MSK_DPAR_MIO_TOL_ABS_RELAX_INT = int32(49)
MSK_DPAR_MIO_TOL_FEAS = int32(50)
MSK_DPAR_MIO_TOL_MAX_CUT_FRAC_RHS = int32(51)
MSK_DPAR_MIO_TOL_MIN_CUT_FRAC_RHS = int32(52)
MSK_DPAR_MIO_TOL_REL_DUAL_BOUND_IMPROVEMENT = int32(53)
MSK_DPAR_MIO_TOL_REL_GAP = int32(54)
MSK_DPAR_MIO_TOL_REL_RELAX_INT = int32(55)
MSK_DPAR_MIO_TOL_X = int32(56)
MSK_DPAR_NONCONVEX_TOL_FEAS = int32(57)
MSK_DPAR_NONCONVEX_TOL_OPT = int32(58)
MSK_DPAR_OPTIMIZER_MAX_TIME = int32(59)
MSK_DPAR_PRESOLVE_TOL_ABS_LINDEP = int32(60)
MSK_DPAR_PRESOLVE_TOL_AIJ = int32(61)
MSK_DPAR_PRESOLVE_TOL_REL_LINDEP = int32(62)
MSK_DPAR_PRESOLVE_TOL_S = int32(63)
MSK_DPAR_PRESOLVE_TOL_X = int32(64)
MSK_DPAR_QCQO_REFORMULATE_REL_DROP_TOL = int32(65)
MSK_DPAR_SIM_LU_TOL_REL_PIV = int32(66)
MSK_DPAR_SIMPLEX_ABS_TOL_PIV = int32(67)
MSK_DPAR_UPPER_OBJ_CUT = int32(68)
MSK_DPAR_UPPER_OBJ_CUT_FINITE_TRH = int32(69)

  MSK_DPAR_BEGIN = int32(0)
  MSK_DPAR_END   = int32(70)

# enum simdupvec
MSK_SIM_EXPLOIT_DUPVEC_FREE = int32(2)
MSK_SIM_EXPLOIT_DUPVEC_OFF = int32(0)
MSK_SIM_EXPLOIT_DUPVEC_ON = int32(1)

  MSK_SIM_EXPLOIT_DUPVEC_BEGIN = int32(0)
  MSK_SIM_EXPLOIT_DUPVEC_END   = int32(3)

# enum compresstype
MSK_COMPRESS_FREE = int32(1)
MSK_COMPRESS_GZIP = int32(2)
MSK_COMPRESS_NONE = int32(0)

  MSK_COMPRESS_BEGIN = int32(0)
  MSK_COMPRESS_END   = int32(3)

# enum nametype
MSK_NAME_TYPE_GEN = int32(0)
MSK_NAME_TYPE_LP = int32(2)
MSK_NAME_TYPE_MPS = int32(1)

  MSK_NAME_TYPE_BEGIN = int32(0)
  MSK_NAME_TYPE_END   = int32(3)

# enum mpsformat
MSK_MPS_FORMAT_FREE = int32(2)
MSK_MPS_FORMAT_RELAXED = int32(1)
MSK_MPS_FORMAT_STRICT = int32(0)

  MSK_MPS_FORMAT_BEGIN = int32(0)
  MSK_MPS_FORMAT_END   = int32(3)

# enum variabletype
MSK_VAR_TYPE_CONT = int32(0)
MSK_VAR_TYPE_INT = int32(1)

  MSK_VAR_BEGIN = int32(0)
  MSK_VAR_END   = int32(2)

# enum checkconvexitytype
MSK_CHECK_CONVEXITY_FULL = int32(2)
MSK_CHECK_CONVEXITY_NONE = int32(0)
MSK_CHECK_CONVEXITY_SIMPLE = int32(1)

  MSK_CHECK_CONVEXITY_BEGIN = int32(0)
  MSK_CHECK_CONVEXITY_END   = int32(3)

# enum language
MSK_LANG_DAN = int32(1)
MSK_LANG_ENG = int32(0)

  MSK_LANG_BEGIN = int32(0)
  MSK_LANG_END   = int32(2)

# enum startpointtype
MSK_STARTING_POINT_CONSTANT = int32(2)
MSK_STARTING_POINT_FREE = int32(0)
MSK_STARTING_POINT_GUESS = int32(1)
MSK_STARTING_POINT_SATISFY_BOUNDS = int32(3)

  MSK_STARTING_POINT_BEGIN = int32(0)
  MSK_STARTING_POINT_END   = int32(4)

# enum soltype
MSK_SOL_BAS = int32(1)
MSK_SOL_ITG = int32(2)
MSK_SOL_ITR = int32(0)

  MSK_SOL_BEGIN = int32(0)
  MSK_SOL_END   = int32(3)

# enum scalingmethod
MSK_SCALING_METHOD_FREE = int32(1)
MSK_SCALING_METHOD_POW2 = int32(0)

  MSK_SCALING_METHOD_BEGIN = int32(0)
  MSK_SCALING_METHOD_END   = int32(2)

# enum value
MSK_LICENSE_BUFFER_LENGTH = int32(20)
MSK_MAX_STR_LEN = int32(1024)

# enum stakey
MSK_SK_BAS = int32(1)
MSK_SK_FIX = int32(5)
MSK_SK_INF = int32(6)
MSK_SK_LOW = int32(3)
MSK_SK_SUPBAS = int32(2)
MSK_SK_UNK = int32(0)
MSK_SK_UPR = int32(4)

  MSK_SK_BEGIN = int32(0)
  MSK_SK_END   = int32(7)

# enum simreform
MSK_SIM_REFORMULATION_AGGRESSIVE = int32(3)
MSK_SIM_REFORMULATION_FREE = int32(2)
MSK_SIM_REFORMULATION_OFF = int32(0)
MSK_SIM_REFORMULATION_ON = int32(1)

  MSK_SIM_REFORMULATION_BEGIN = int32(0)
  MSK_SIM_REFORMULATION_END   = int32(4)

# enum iinfitem
MSK_IINF_ANA_PRO_NUM_CON = int32(0)
MSK_IINF_ANA_PRO_NUM_CON_EQ = int32(1)
MSK_IINF_ANA_PRO_NUM_CON_FR = int32(2)
MSK_IINF_ANA_PRO_NUM_CON_LO = int32(3)
MSK_IINF_ANA_PRO_NUM_CON_RA = int32(4)
MSK_IINF_ANA_PRO_NUM_CON_UP = int32(5)
MSK_IINF_ANA_PRO_NUM_VAR = int32(6)
MSK_IINF_ANA_PRO_NUM_VAR_BIN = int32(7)
MSK_IINF_ANA_PRO_NUM_VAR_CONT = int32(8)
MSK_IINF_ANA_PRO_NUM_VAR_EQ = int32(9)
MSK_IINF_ANA_PRO_NUM_VAR_FR = int32(10)
MSK_IINF_ANA_PRO_NUM_VAR_INT = int32(11)
MSK_IINF_ANA_PRO_NUM_VAR_LO = int32(12)
MSK_IINF_ANA_PRO_NUM_VAR_RA = int32(13)
MSK_IINF_ANA_PRO_NUM_VAR_UP = int32(14)
MSK_IINF_CONCURRENT_FASTEST_OPTIMIZER = int32(15)
MSK_IINF_INTPNT_FACTOR_DIM_DENSE = int32(16)
MSK_IINF_INTPNT_ITER = int32(17)
MSK_IINF_INTPNT_NUM_THREADS = int32(18)
MSK_IINF_INTPNT_SOLVE_DUAL = int32(19)
MSK_IINF_MIO_CONSTRUCT_NUM_ROUNDINGS = int32(20)
MSK_IINF_MIO_CONSTRUCT_SOLUTION = int32(21)
MSK_IINF_MIO_INITIAL_SOLUTION = int32(22)
MSK_IINF_MIO_NUM_ACTIVE_NODES = int32(23)
MSK_IINF_MIO_NUM_BASIS_CUTS = int32(24)
MSK_IINF_MIO_NUM_BRANCH = int32(25)
MSK_IINF_MIO_NUM_CARDGUB_CUTS = int32(26)
MSK_IINF_MIO_NUM_CLIQUE_CUTS = int32(27)
MSK_IINF_MIO_NUM_COEF_REDC_CUTS = int32(28)
MSK_IINF_MIO_NUM_CONTRA_CUTS = int32(29)
MSK_IINF_MIO_NUM_DISAGG_CUTS = int32(30)
MSK_IINF_MIO_NUM_FLOW_COVER_CUTS = int32(31)
MSK_IINF_MIO_NUM_GCD_CUTS = int32(32)
MSK_IINF_MIO_NUM_GOMORY_CUTS = int32(33)
MSK_IINF_MIO_NUM_GUB_COVER_CUTS = int32(34)
MSK_IINF_MIO_NUM_INT_SOLUTIONS = int32(35)
MSK_IINF_MIO_NUM_KNAPSUR_COVER_CUTS = int32(36)
MSK_IINF_MIO_NUM_LATTICE_CUTS = int32(37)
MSK_IINF_MIO_NUM_LIFT_CUTS = int32(38)
MSK_IINF_MIO_NUM_OBJ_CUTS = int32(39)
MSK_IINF_MIO_NUM_PLAN_LOC_CUTS = int32(40)
MSK_IINF_MIO_NUM_RELAX = int32(41)
MSK_IINF_MIO_NUMCON = int32(42)
MSK_IINF_MIO_NUMINT = int32(43)
MSK_IINF_MIO_NUMVAR = int32(44)
MSK_IINF_MIO_OBJ_BOUND_DEFINED = int32(45)
MSK_IINF_MIO_TOTAL_NUM_CUTS = int32(46)
MSK_IINF_MIO_USER_OBJ_CUT = int32(47)
MSK_IINF_OPT_NUMCON = int32(48)
MSK_IINF_OPT_NUMVAR = int32(49)
MSK_IINF_OPTIMIZE_RESPONSE = int32(50)
MSK_IINF_RD_NUMBARVAR = int32(51)
MSK_IINF_RD_NUMCON = int32(52)
MSK_IINF_RD_NUMCONE = int32(53)
MSK_IINF_RD_NUMINTVAR = int32(54)
MSK_IINF_RD_NUMQ = int32(55)
MSK_IINF_RD_NUMVAR = int32(56)
MSK_IINF_RD_PROTYPE = int32(57)
MSK_IINF_SIM_DUAL_DEG_ITER = int32(58)
MSK_IINF_SIM_DUAL_HOTSTART = int32(59)
MSK_IINF_SIM_DUAL_HOTSTART_LU = int32(60)
MSK_IINF_SIM_DUAL_INF_ITER = int32(61)
MSK_IINF_SIM_DUAL_ITER = int32(62)
MSK_IINF_SIM_NETWORK_DUAL_DEG_ITER = int32(63)
MSK_IINF_SIM_NETWORK_DUAL_HOTSTART = int32(64)
MSK_IINF_SIM_NETWORK_DUAL_HOTSTART_LU = int32(65)
MSK_IINF_SIM_NETWORK_DUAL_INF_ITER = int32(66)
MSK_IINF_SIM_NETWORK_DUAL_ITER = int32(67)
MSK_IINF_SIM_NETWORK_PRIMAL_DEG_ITER = int32(68)
MSK_IINF_SIM_NETWORK_PRIMAL_HOTSTART = int32(69)
MSK_IINF_SIM_NETWORK_PRIMAL_HOTSTART_LU = int32(70)
MSK_IINF_SIM_NETWORK_PRIMAL_INF_ITER = int32(71)
MSK_IINF_SIM_NETWORK_PRIMAL_ITER = int32(72)
MSK_IINF_SIM_NUMCON = int32(73)
MSK_IINF_SIM_NUMVAR = int32(74)
MSK_IINF_SIM_PRIMAL_DEG_ITER = int32(75)
MSK_IINF_SIM_PRIMAL_DUAL_DEG_ITER = int32(76)
MSK_IINF_SIM_PRIMAL_DUAL_HOTSTART = int32(77)
MSK_IINF_SIM_PRIMAL_DUAL_HOTSTART_LU = int32(78)
MSK_IINF_SIM_PRIMAL_DUAL_INF_ITER = int32(79)
MSK_IINF_SIM_PRIMAL_DUAL_ITER = int32(80)
MSK_IINF_SIM_PRIMAL_HOTSTART = int32(81)
MSK_IINF_SIM_PRIMAL_HOTSTART_LU = int32(82)
MSK_IINF_SIM_PRIMAL_INF_ITER = int32(83)
MSK_IINF_SIM_PRIMAL_ITER = int32(84)
MSK_IINF_SIM_SOLVE_DUAL = int32(85)
MSK_IINF_SOL_BAS_PROSTA = int32(86)
MSK_IINF_SOL_BAS_SOLSTA = int32(87)
MSK_IINF_SOL_INT_PROSTA = int32(88)
MSK_IINF_SOL_INT_SOLSTA = int32(89)
MSK_IINF_SOL_ITG_PROSTA = int32(90)
MSK_IINF_SOL_ITG_SOLSTA = int32(91)
MSK_IINF_SOL_ITR_PROSTA = int32(92)
MSK_IINF_SOL_ITR_SOLSTA = int32(93)
MSK_IINF_STO_NUM_A_CACHE_FLUSHES = int32(94)
MSK_IINF_STO_NUM_A_REALLOC = int32(95)
MSK_IINF_STO_NUM_A_TRANSPOSES = int32(96)

  MSK_IINF_BEGIN = int32(0)
  MSK_IINF_END   = int32(97)

# enum xmlwriteroutputtype
MSK_WRITE_XML_MODE_COL = int32(1)
MSK_WRITE_XML_MODE_ROW = int32(0)

  MSK_WRITE_XML_MODE_BEGIN = int32(0)
  MSK_WRITE_XML_MODE_END   = int32(2)

# enum optimizertype
MSK_OPTIMIZER_CONCURRENT = int32(10)
MSK_OPTIMIZER_CONIC = int32(2)
MSK_OPTIMIZER_DUAL_SIMPLEX = int32(4)
MSK_OPTIMIZER_FREE = int32(0)
MSK_OPTIMIZER_FREE_SIMPLEX = int32(6)
MSK_OPTIMIZER_INTPNT = int32(1)
MSK_OPTIMIZER_MIXED_INT = int32(9)
MSK_OPTIMIZER_MIXED_INT_CONIC = int32(8)
MSK_OPTIMIZER_NETWORK_PRIMAL_SIMPLEX = int32(7)
MSK_OPTIMIZER_NONCONVEX = int32(11)
MSK_OPTIMIZER_PRIMAL_DUAL_SIMPLEX = int32(5)
MSK_OPTIMIZER_PRIMAL_SIMPLEX = int32(3)

  MSK_OPTIMIZER_BEGIN = int32(0)
  MSK_OPTIMIZER_END   = int32(12)

# enum presolvemode
MSK_PRESOLVE_MODE_FREE = int32(2)
MSK_PRESOLVE_MODE_OFF = int32(0)
MSK_PRESOLVE_MODE_ON = int32(1)

  MSK_PRESOLVE_MODE_BEGIN = int32(0)
  MSK_PRESOLVE_MODE_END   = int32(3)

# enum miocontsoltype
MSK_MIO_CONT_SOL_ITG = int32(2)
MSK_MIO_CONT_SOL_ITG_REL = int32(3)
MSK_MIO_CONT_SOL_NONE = int32(0)
MSK_MIO_CONT_SOL_ROOT = int32(1)

  MSK_MIO_CONT_SOL_BEGIN = int32(0)
  MSK_MIO_CONT_SOL_END   = int32(4)

